### ISSUE TITLE
Support for Partial Index Option in 3.2

### ISSUE THREAD

**Issue by amarcionek** [mongodb/morphia#1036]
Is there support for the [partial ](https://docs.mongodb.com/manual/core/index-partial/)index option in Mongo 3.2?  Tried reading the docs and only see the sparse option.  If not, is there a roadmap for adding this?

**Comment by evanchooly** [comment]
The solution for this is very similar to the document validation change currently under PR and dependent on the index refactoring also under review.  I don't think this will take long once the index stuff, at least, is merged to master.
