### ISSUE TITLE
$dec supports number argument

### ISSUE THREAD

**Issue by crzo** [mongodb/morphia#1054]
Hey there,

is there any plan to build a convenient overloaded interface + implementation such as:

dec(String field, Number amount) ?

For now i am forced to use inc(String field, Number amount) where the amount must be negative. Its okay for now, but somehow confusing. Morphia can of course use the inc(String, Number) method under the hood, but on the business layer i don't want to "invert all values".

Cheers,
Chris

**Comment by evanchooly** [comment]
Seems reasonable.  And simple enough.

**Comment by UlrichCech** [comment]
Have provided a merge-request for this issue

**Comment by evanchooly** [comment]
Thanks, @UlrichCech, for the PR.
