### ISSUE TITLE
When sorting on multiple fields, the second field is ignored in the order() call

### ISSUE THREAD

**Issue by blinder** [mongodb/morphia#1070]
I have a model that looks like:

    @Entity("users")
    @Indexes(@Index(fields = {@Field("lastName"), @Field("firstName")}))
    public class User extends Model {
        @Indexed public String email;
        public String firstName;
        @Indexed public String lastName;
        public String employer;
    }

and i have a query that looks like:

    q.field("employer").containsIgnoreCase(input);
    q.order("lastName,firstName");
    q.limit(25);
    q.offset(start);

What i've noticed is that the second field, in this case `firstName` is ignored. If i change the order, then `lastName` is ignored.

My objective is to sort on last name and first name, exactly how one might sort a phone book. 

Using morphia version: 1.2.1 and java mongodb driver: 3.2.2

I am not sure if i'm missing something, i do have a compound index, in the sort order i am looking for, and i do not get any exceptions.

**Comment by evanchooly** [comment]
I just pushed a test that verifies that `order()` works correctly.  If you're still seeing oddities, please post some sample docs and any output to the [mailing list](https://groups.google.com/forum/#!forum/morphia).
