### ISSUE TITLE
Mapper error updating Key array field with $set

### ISSUE THREAD

**Issue by d4nirod** [mongodb/morphia#1078]
Morphia 1.1.1
MongoDB Java Driver version: 2.14.0
MongoDB version: 3.0.12

### Error:
```
161122 15:26:53,310 ERROR [Mapper] Error converting value([]) to reference.
java.lang.NullPointerException
  at org.mongodb.morphia.mapping.Mapper.getDBRefs(Mapper.java:725)
  at org.mongodb.morphia.mapping.Mapper.toMongoObject(Mapper.java:559)
  at org.mongodb.morphia.query.UpdateOpsImpl.add(UpdateOpsImpl.java:216)
  at org.mongodb.morphia.query.UpdateOpsImpl.set(UpdateOpsImpl.java:155)
  at com.farmerswife.cloudwife.server.services.dao.AbstractDAO.set(AbstractDAO.java:146)
  at com.farmerswife.cloudwife.server.services.dao.TaskDAO.updateAssignees(TaskDAO.java:661)
  at com.farmerswife.cloudwife.server.services.utils.UserConsumerUtils.consumeTaskAssignments(UserConsumerUtils.java:358)
```
### `xxxDAO` methods on stack trace:
```java
public void updateAssignees(EntityId<CWTask> taskId, List<Key<? extends Assignable>> assignees) {
  set(taskId, ASSIGNEES_FIELD, assignees);
}
```

```java
protected boolean set(EntityId<T> entityId, String fieldExpr, Object value) {
  Query<T> q = q().field(Mapper.ID_KEY).equal(entityId);
  UpdateOperations<T> uops = ds.createUpdateOperations(entityClazz);
  uops.set(fieldExpr, value);	
  ds.update(q, uops);
  return true;
}
```
### Entities:
```java
@Entity(value = "cw_task")
@Converters(EntityIdConverter.class)
public class CWTask extends SyncableEntity implements Serializable {
   @Id
   private EntityId<CWTask> id;
   private String name;
   private String description;
   private Date dueDate;
   @Indexed 
   private EntityId<CWProject> projectId;

   private List<Key<? extends Assignable>> assignees = new ArrayList<>();
}
```
Note: 
`EntityId` basically extends `ObjectId` and  provides type-safety (I know this breaks after Morphia 1.2 as `ObjectId` has been made `final` but at this point it's not relevant).
`Assignable` is just a marker interface to restrict the type of entities that a CWTask can be assigned to, ie. CWUser, CWGroup, etc

---

The error is caused by [line 558](https://github.com/mongodb/morphia/blob/1.1.x/morphia/src/main/java/org/mongodb/morphia/mapping/Mapper.java#L558) of `org.mongodb.morphia.mapping.Mapper.toMongoObject(MappedField, MappedClass, Object)`:
```java
  if (mapped != null && (Key.class.isAssignableFrom(mapped.getClazz()) || mapped.getEntityAnnotation() != null))
```
where if we pass in an empty list as field value, being the `CWTask.assignees` field of type `List<Key>` with no annotation `(Key.class.isAssignableFrom(mapped.getClazz())` evals as `true` and `mapped.getEntityAnnotation() != null` evaluates as `false` so `getDBRefs()` is then invoked resulting in NPE [at line 725](https://github.com/mongodb/morphia/blob/1.1.x/morphia/src/main/java/org/mongodb/morphia/mapping/Mapper.java#L725)

**Comment by evanchooly** [comment]
Does the error remain with 1.3.0-rc0?

**Comment by d4nirod** [comment]
Can't easily tell as we can't go to version above 1.1.x without breaking the build due to the `ObjectId` been made final so we are stuck here until we find a work around for our `class EntityId extends ObjectId` thing or the Morphia devs _un-final_ it ;-P, in any case the offending line from `Mapper.toMongoObject()` is still there [now in line 616](https://github.com/mongodb/morphia/blob/r1.3.0-rc0/morphia/src/main/java/org/mongodb/morphia/mapping/Mapper.java#L616) and so is the `Mapper.getDBRefs()` which is unchanged so it would be quite safe to say it still happens.

**Comment by evanchooly** [comment]
`ObjectId` comes from the Java driver.  Morphia itself has no control over it's finalness.

**Comment by d4nirod** [comment]
Ah, yes of course... sorry. But that's not the main thing, let me clarify that as not to muddle the issue:

Just tested up to Morphia 1.2.1 and the mapping error using `$set` to update a **non-annotated** Key array field with an empty array is still happening as described earlier.

---

Note: can't test with Morphia 1.3.x since needs Java Driver 3.x which we can't use because it has made `ObjectId` final so it breaks our code.

**Comment by d4nirod** [comment]
Actually now that I dug a bit deeper I think that this is not related to an empty list, I think it all boils down to the fact that if one uses a `List` of `Key`s for an entity field `org.mongodb.morphia.mapping.Mapper` expects it to be **always annotated** with `@Reference` otherwise it will throw up an NPE:
```java
private Object getDBRefs(final MappedField field, final Iterable value) {
    final List<Object> refs = new ArrayList<Object>();
    boolean idOnly = field.getAnnotation(Reference.class).idOnly();  // <---HERE
    for (final Object o : value) {
        Key<?> key = (o instanceof Key) ? (Key<?>) o : getKey(o);
        refs.add(idOnly ? key.getId() : keyToDBRef(key));
    }
    return refs;
}
```
So is this a bug of a feature? meaning that one is only supposed to use `@Reference` annotated `Key` fields.. and if so why it only happens with `update()` (aka `$set`) and not with `save()` ?

**Comment by d4nirod** [comment]
@evanchooly: any comments on this?

**Comment by evanchooly** [comment]
I'm probably missing something but this seems to work on `master`.  Here's my attempt to reproduce your test case.  If it's not quite right let me know but everything seems ok so far.

```java
        CWTask task = new CWTask();
        task.id = new ObjectId();
        Key<CWTask> key = getDs().getKey(task);
        task.assignees = new ArrayList<Key<? extends CWTask>>(singletonList(key));
        getDs().save(task);

        getDs().update(getDs().find(CWTask.class),
                       getDs().createUpdateOperations(CWTask.class).set("assignees", task.assignees));
```

**Comment by d4nirod** [comment]
Ok, I still get the error. Pushed little standalone test to https://github.com/d4nirod/morphiatest (check that jdk >= 1.70)
Latest Morphia/Java driver
```
161129 18:08:05,842 INFO  [cluster] Cluster created with settings {hosts=[127.0.0.1:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
161129 18:08:05,942 INFO  [MorphiaLoggerFactory] LoggerImplFactory set to org.mongodb.morphia.logging.slf4j.SLF4JLoggerImplFactory
161129 18:08:05,967 INFO  [connection] Opened connection [connectionId{localValue:1, serverValue:754}] to 127.0.0.1:27017
161129 18:08:05,969 INFO  [cluster] Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 12]}, minWireVersion=0, maxWireVersion=3, maxDocumentSize=16777216, roundTripTimeNanos=752375}
161129 18:08:06,041 INFO  [connection] Opened connection [connectionId{localValue:2, serverValue:755}] to 127.0.0.1:27017
Using MongoDB version: 3.0.12
Using: mongo-java-driver version: 3.4.0
Using: Morphia Core version: 1.3.0.rc0
Configured MongoDB to URI: 'mongodb://127.0.0.1:27017', DB name: 'cloudwife
'Testing Mapper 2016-11-29T18:08:06.060' saved with ID: 583db5f6f3352d8dfd0546c2
161129 18:08:06,122 WARN  [MappedField] Parameterized types are treated as untyped Objects. See field 'type' on class org.mongodb.morphia.Key
161129 18:08:06,122 WARN  [MappedField] Parameterized types are treated as untyped Objects. See field 'id' on class org.mongodb.morphia.Key
161129 18:08:06,123 ERROR [Mapper] Error converting value([null]) to reference.
java.lang.NullPointerException
	at org.mongodb.morphia.mapping.Mapper.getDBRefs(Mapper.java:786)
	at org.mongodb.morphia.mapping.Mapper.toMongoObject(Mapper.java:617)
	at org.mongodb.morphia.query.UpdateOpsImpl.add(UpdateOpsImpl.java:285)
	at org.mongodb.morphia.query.UpdateOpsImpl.set(UpdateOpsImpl.java:223)
	at morphiatest.MapperIssueTest.main(MapperIssueTest.java:44)
```
Previous Morphia 1.2.1, driver 2.14
```
161129 18:05:41,369 INFO  [MorphiaLoggerFactory] LoggerImplFactory set to org.mongodb.morphia.logging.slf4j.SLF4JLoggerImplFactory
Using MongoDB version: 3.0.12
Using: MongoDB Java Driver version: 2.14.0.RELEASE
Using: Morphia Core version: 1.2.1
Configured MongoDB to URI: 'mongodb://127.0.0.1:27017', DB name: 'cloudwife
'Testing Mapper 2016-11-29T18:05:41.459' saved with ID: 583db5653acafa91ecbfb267
161129 18:05:41,512 WARN  [MappedField] Parameterized types are treated as untyped Objects. See field 'type' on class org.mongodb.morphia.Key
161129 18:05:41,512 WARN  [MappedField] Parameterized types are treated as untyped Objects. See field 'id' on class org.mongodb.morphia.Key
161129 18:05:41,513 ERROR [Mapper] Error converting value([null]) to reference.
java.lang.NullPointerException
	at org.mongodb.morphia.mapping.Mapper.getDBRefs(Mapper.java:750)
	at org.mongodb.morphia.mapping.Mapper.toMongoObject(Mapper.java:584)
	at org.mongodb.morphia.query.UpdateOpsImpl.add(UpdateOpsImpl.java:216)
	at org.mongodb.morphia.query.UpdateOpsImpl.set(UpdateOpsImpl.java:155)
	at morphiatest.MapperIssueTest.main(MapperIssueTest.java:44)
```
What's different?

**Comment by evanchooly** [comment]
This is actually working for me with Morphia 1.3.0, driver 3.4.0, and MongoDB 3.4.0-rc0.  Well, I'm not getting any exceptions at least.  `assignees` is always null which i'm exploring but definitely not seeing the exception you are.

**Comment by d4nirod** [comment]
@evanchooly do you mean you actually don't see the errors when running the little Maven project I posted? That would be puzzling... If not it might be a case of log levels or config in your log4j? 
Looking at the stack trace I could see that the exception was actually caught within `Mapper.toMongoObject(final MappedField mf, final MappedClass mc, final Object value)` if I remember correctly (away from my computer at the mo) which logs the "Error converting blah" message and then gets the mapped value from `Mapper.toMongoObject(final Object javaObj, final boolean includeClassName)` instead which may return `null` if empty array value or akternatively attempts some default conversion...?

**Comment by evanchooly** [comment]
When I step through that project with a debugger all is fine.  When I add new output, i see it all.

**Comment by d4nirod** [comment]
Ahh. Weird, well I put that project together quickly as a test case by taking our pom.xml and removing most of the stuff so it might be best if you could try reproduce on oneof your projects but at least we agree there is an issue here?

**Comment by d4nirod** [comment]
@evanchooly sorry there was I bug in the test code I pushed where the key in the assignees Key List was always assigned to `null` since `ds.getKey(task)` was returning `null`.
 I've fixed it and pushed it to the repo so now we can see the original error message I've been talking about all along: `ERROR [Mapper] Error converting value([Key{...}]) to reference. 
java.lang.NullPointerException` 
I've updated [my earlier post](https://github.com/mongodb/morphia/issues/1078#issuecomment-263634650) with the correct error messages.

**Comment by evanchooly** [comment]
I've rolled all the way back to mongodb 3.0.14.  I've used morphia 1.2.1 and 1.3.0.  I can't recreate your bug.  Even with your updated tests.

**Comment by d4nirod** [comment]
Hmm, there is something missing here ... I'm a bit in the dark with regards of the actual test output on your side but I strongly suspect it might be Log4J not working as this error is caught and logged inside Morphia's `Mapper.toMongoObject()`. If logging was not configured properly, you wouldn't see the error message, just the test program console output. 

What IDE are you using? I'm with Eclipse and it picked the `log4j.xml` file ok from it's original location but I think it wasn't very "standard" so I've moved it to `src/main/resources`. I believe both Eclipse and IntelliJ should pick it up now.
I've also replaced all `System.out.println()` calls for log calls so if logging doesn't work there won't be any messages from the test program and we'll know it's not working. (updated the output on the [earlier post ](https://github.com/mongodb/morphia/issues/1078#issuecomment-263634650)again to reflect what you should see).

Can you please pull the changes, re-run the test and paste the output?

Thank you.

**Comment by evanchooly** [comment]
That did it.  I see the NPE now.  I'll dig in to it.  Thanks.

**Comment by d4nirod** [comment]
Any chance to fix it also on v1.2.x?
We're stuck with Morphia `1.2.x` + Mongo Java Driver `2.14.x` until we can figure out how to workaround `ObjectId` [finalness introduced](https://github.com/mongodb/mongo-java-driver/commit/6fb1830a3dd42997efc4ed8068ec267c20a247be#diff-f7f229538ce532517ba2202d8aa1b244
) on Java Driver r3.0.0. 

---
Note: I've just remembered [discussing this with you in Groups](https://groups.google.com/d/msg/morphia/isndCXKISTQ/oCy5iRSpCQAJ) a while ago. The way we have started using `Key` in `CWTask.assignees` as a loose foreign key/entity reference it's our attempt to explore usage of said class to perhaps later substitute our `class EntityId<T> extends ObjectId` for `Key` as type-safe entity ID.

**Comment by d4nirod** [comment]
>Any chance to fix it also on v1.2.x?
We're stuck with Morphia 1.2.x + Mongo Java Driver 2.14.x until we can figure out how to workaround ObjectId finalness introduced on Java Driver r3.0.0.

@evanchooly: bump

**Comment by evanchooly** [comment]
I've opened https://github.com/mongodb/morphia/issues/1108 to backport this.

**Comment by evanchooly** [comment]
I just pushed 1.2.2 to maven central.  It should be available soon.

**Comment by d4nirod** [comment]
Thank you. Much obliged.
