### ISSUE TITLE
FieldEndImpl is now private and prevents me upgrading to 1.2.1

### ISSUE THREAD

**Issue by ymmark0** [mongodb/morphia#1080]
I'm struggling to upgrade from morphia 1.0.1 to 1.2.1. With 1.0.1 we had to override the morphia calls to equals() and other calls to throw an exception if the value being fetched was null. Doing that prevented a security hole where the first record in the database with a value of null was selected if the calls runs without an exception.

To do this, we overrode morphia.createDatastore() in the Guice module to return a special custom datastore. The special datastore returned a special Query object which returned a special FieldEnd when the Query.field() call was called. This FieldEnd did the exception checking.

That worked, however our special NotAllowingNullsFieldEnd class extended FieldEndImpl which is now private in 1.2.1 and so I have a problem.

We need a way to stop Queries from accepting null as a valid argument in the 1.2.1 world.

One solution would be to move NotAllowingNullsFieldEnd to the same package FieldEndImpl is in (org.mongodb.morphia.query) but that seems really hacky.

I'm NOT a morphia expert and actually I'm fairly new to java, so any expert input would be welcome.

Just FYI, the implementation of this was done before my time, so I don't have a lot to add about the in-depth reasons regarding why this path was chosen, I've just been asked to do the upgrade.

**Comment by ymmark0** [comment]
Guys, I note that the class is public but the constructor in 1.3.1 this is still package private.  Could you make it public also?

**Comment by evanchooly** [comment]
*facepalm*  well, i was planning a 1.3.2 anyway.  My apologies for missing that one.

**Comment by ymmark0** [comment]
Heh ) - I do it all the time too...

**Comment by ymmark0** [comment]
No pressure, but would you have an ETA for 1.3.2?
