### ISSUE TITLE
unsetting hashmap causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by umbreak** [mongodb/morphia#1089]
Hello,

Updating to morphia 1.3.0 gives me an error when I try to unset a whole hashMap. The line it is:

```java
UpdateOperations<User> updateOpts = User.datastore.createUpdateOperations(User.class).disableValidation()
updateOpts.unset("services.$.crmConfig");
```
_Caused by: **java.lang.ArrayIndexOutOfBoundsException: 3**
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at org.mongodb.morphia.internal.PathTarget.next(PathTarget.java:96)
	at org.mongodb.morphia.internal.PathTarget.resolve(PathTarget.java:115)_

The model is as follows:

```java
    @Entity(value = "user", noClassnameStored = true)
    public class User {
        public List<Services> services;
        
        @Embedded
        public static class Services{
            public Map<CRMAttribute, Boolean> crmConfig;
        }
    }
```

Debugging, I can see that the problem comes in the method **resolve()** on the class **TargetPath**
You can see that, if you have the string `services.$.crmConfig`, the second time it runs into the loop, it throws ArrayIndexOutOfBoundsException. You need to add some extra checks for the method `hasNext()` in the else case:

```java
                if (!field.isMap()) {
                    translate(field.getNameToStore());
                } else {
                    next();  // consume the map key segment
                }
```
Cause I want to unset the whole map, so I'm not specifying any key, as assumed in that code

**Comment by umbreak** [comment]
I'm not sure if it is enough just adding this check, or something else needs to be added.

**Comment by fabriziobonavita** [comment]
Thanks for fixing it. This is blocking us at the moment, is there any release date for 1.3.1?
