### ISSUE TITLE
IllegalArgumentException calling updateFirst

### ISSUE THREAD

**Issue by rlodge** [mongodb/morphia#1091]
When calling the updateFirst method that takes a query and an entity (~line 865 in DatastoreImpl), I (always?) receive an IllegalArgumentException if the entity in question is versioned.  The exception I get is:

```
java.lang.IllegalArgumentException: Invalid BSON field name $inc
	at org.bson.AbstractBsonWriter.writeName(AbstractBsonWriter.java:516)
	at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:129)
	at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:61)
	...
	at com.mongodb.Mongo.execute(Mongo.java:845)
	at com.mongodb.Mongo$2.execute(Mongo.java:828)
	at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:342)
	at com.mongodb.DBCollection.update(DBCollection.java:567)
	at org.mongodb.morphia.DatastoreImpl.update(DatastoreImpl.java:1552)
	at org.mongodb.morphia.DatastoreImpl.update(DatastoreImpl.java:1507)
	at org.mongodb.morphia.DatastoreImpl.updateFirst(DatastoreImpl.java:869)
```

This appears to be because the `org.mongodb.morphia.DatastoreImpl#update(org.mongodb.morphia.query.Query<T>, com.mongodb.DBObject, org.mongodb.morphia.UpdateOptions, boolean)` method assumes that the input is an update operations document and not a replacement.

**Comment by rlodge** [comment]
My concern about #1101 is that it changes the intent of the operation. By putting everything in a $set, it doesn't actually do a replace on the update.  Because the incoming DB object may not have all fields (since null ones might be absent, say), it will leave fields that aren't in the DBObject in place, only setting new ones.  I think that would make it (for instance) impossible to set a field to null using updateFirst.

**Comment by evanchooly** [comment]
I did some testing prior to this.  It only ever updated the field listed in the update object.  Any existing fields in the document that weren't in the update document were unchanged.

**Comment by rlodge** [comment]
My understanding is that when I call updateFirst() with an entity, it should issue an update as if I had done: `db.Versioned.update({foo: "bar"}, {foo: "bar", baz: "qux"})`, not `db.Versioned.update({foo: "bar"}, {$set: {foo: "bar", baz: "qux"}})`, because the intent and the results of the two operations is different.  If I'd wanted "$set", I would have used one of the updateFirst operations that takes an UpdateOperations instance.

Because $set only updates fields that are included, fields won't get nulled, even though I intend them to.  If you change the test to:

```java
    @Test
    public void testEntityUpdateWithoutUpdateOps() {
        final Datastore datastore = getDs();

        Versioned original = new Versioned();
        original.setName("Value 1");
        original.setCount(42);
        getDs().save(original);

        Versioned found = datastore.find(Versioned.class).field("name").equal("Value 1").get();
        assertEquals("Value 1", found.getName());
        assertEquals(1L, found.getVersion().longValue());

        Versioned update = new Versioned();
        update.setName("Value 2");
        update.setCount(9);

        datastore.updateFirst(
            datastore.find(Versioned.class).field("name").equal("Value 1"),
            update,
            true
        );

        Versioned found2 = datastore.find(Versioned.class).field("name").equal("Value 2").get();
        assertNotNull(found2);
        assertEquals(2L, found2.getVersion().longValue());
        assertEquals(9, found2.getCount().intValue());

        try {
            getDs().save(original);
            fail("Should get a ConcurrentModificationException");
        } catch (ConcurrentModificationException ignored) {
        }

        Versioned update2 = new Versioned();
        update2.setName("Value 3");

        assertFalse(getMorphia().getMapper().toDBObject(update2).containsField("count"));

        datastore.updateFirst(
            datastore.find(Versioned.class).field("name").equal("Value 2"),
            update2,
            false
        );

        Versioned found3 = datastore.find(Versioned.class).field("name").equal("Value 3").get();
        assertNotNull(found3);
        assertEquals(3L, found3.getVersion().longValue());
        assertNull(found3.getCount());
    }
```

You will see that the field doesn't get nulled in the DB.

I see your concern with the initial pull request not updating the version; I'm not sure how to reconcile the two.  Maybe the updateFirst that accepts the entity should add a version check to the query, just as the save() calls do?  But I'm concerned that changing it to a $set produces the unintended consequence of leaving values in the DB that I didn't expect to be there.

**Comment by evanchooly** [comment]
hrm.  you're right.  i apparently fat fingered my initial test...  I'm not convinced we can reconcile `updateFirst` and versioning, then.  At least not atomically.  One option is to query first to get that "first" document, then run the update with the ID and version info from that document.  Not entirely atomic but i'm not sure it matters functionally speaking.

**Comment by rlodge** [comment]
Yeah.  I'm not sure what the solution is.  I'd hate to loose atomicity; that's part of why we use the call.  We could do a "best attempt" at setting the version like in my PR, but it does leave the possibility that you would re-use the version or overwrite an object that had been previously updated.  Maybe it's just not possible and an updateFirst with a full entity shouldn't include versioning like that?  That is, in my PR, the "isReplace" option would just turn off the version incrementing.

(A side note, I was wondering if there should be a way to turn the update-verison-change off via QueryOptions).

**Comment by evanchooly** [comment]
Another option might be to do what I have in that PR but add `$unset` for every other field in the entity.  A little brute force but would clear out the other values.

**Comment by rlodge** [comment]
So long as it had the intended effect, I think that would work for me.

**Comment by evanchooly** [comment]
We kicked around this option among others and found no palatable solution.  This particular approach would leave any unmapped fields in the document which is not functionally equivalent.  Other solutions involve rolling back the version number or having to manually set it which violates the morphia-managed aspect of that field.  As such for now, we're opting to merely throw an `UnsupportedOperationException` when `updateFirst()` is called with a versioned entity.  There doesn't appear to be a reasonable resolution of these two features so for now, we'll just disallow it.
