### ISSUE TITLE
Add-Replace in an Inner Array

### ISSUE THREAD

**Issue by igorbakman** [mongodb/morphia#1096]
I would like to add-replace values in an inner array in a document.
Here is an example of the initial data, data to add and final result I wish to achieve:
**Initial data:**
`{
  "_id": "123qwe13qwe213",
  "doc_1": {
    "id": "123qwe13qwe213_doc_1",
    "languages": [
      {
        "en": "blabla Trump"
      },
      {
        "ru": "blabla Putin"
      }
    ]
  }
}
`
**Data to add:**
`{
  "languages": [
    {
      "en": "blabla Trump"
    },
    {
      "de": "blabla Merkel"
    }
  ]
}`

**Result to achieve:**
`{
  "_id": "123qwe13qwe213",
  "doc_1": {
    "id": "123qwe13qwe213_doc_1",
    "languages": [
      {
        "en": "blabla Trump"
      },
      {
        "ru": "blabla Putin"
      },
      {
        "de": "blabla Merkel"
      }
    ]
  }
}`

I'm having trouble to find the exact command to add-replace (upsert) to an inner array where the array is of composed parameters.
Any ideas?

**Comment by evanchooly** [comment]
You want `push()` on `UpdateOperations`.  If you have any problems or questions with that, please post your questions to the [mailing list](https://groups.google.com/forum/#!forum/morphia).
