### ISSUE TITLE
doesNotHaveThisElement() hardcodes the value for 'not'

### ISSUE THREAD

**Issue by evanchooly** [mongodb/morphia#1107]
Reading the code it seems unlikely this works as intended.

**Comment by evanchooly** [comment]
Rereading the code, the explicit boolean is correct if a bit misleading.  This is one of the reasons this method is listed as deprecated:  the language doesn't match well with the query language and interacts oddly with `$not`/`not()`.  Using `elemMatch()` is semantically a bit cleaner and more congruent with shell syntax.

**Comment by ipavkovicAtOtto** [comment]
Now there are two methods with different behavior. doesNotHaveThisElement(final Object val) vs hasThisElement(final Object val)

**Comment by evanchooly** [comment]
And both are deprecated.
