### ISSUE TITLE
Query result return Java Entity or JsonArray/JsonObject or org.bson.Document,  Can I make my own decisions ?

### ISSUE THREAD

**Issue by slieer** [mongodb/morphia#1109]
Now support?  I hope to get support.  thanks.
**This is work fine :**
	@Test
	public void getDeviceXXX(){
		int deviceId = 2;
		Date startDate = DateUtils.addMonths(new Date(), -3);
		String state = "event.XXX";
		Query<DeviceState> query = datastore.createQuery(DeviceXXX.class);
		List<DeviceState> list = query
				.filter("device_id =", deviceId)
				.filter(state + " exists", 1)
				.filter("time >=", startDate)										
				.order("-time")
				.asList();		
	}

**This is work bad :** 
	@Test
	public void getDevicexxx(){
		int deviceId = 2;
		Date startDate = DateUtils.addMonths(new Date(), -3);
		String state = "event.XXX";
		Query<**org.bson.Document**> query = datastore.createQuery(**org.bson.Document**.class);
		List<org.bson.Document> list = query
				.disableValidation()
				.filter("device_id =", deviceId)
				.filter(state + " exists", 1)
				.filter("time >=", startDate)										
				.order("-time")
				.disableValidation()
				.asList();
		
//		MongoConnectionUtil.getMongoDatabase().
		System.out.println(list);
	}

java.lang.Error: Unresolved compilation problems: 
	BasicBSONObject cannot be resolved to a type
	The method createQuery(Class<BasicBSONObject>) from the type Datastore refers to the missing type BasicBSONObject
	BasicBSONObject cannot be resolved to a type

	
**This is work bad too :** 
	@Test
	public void getDevicexxx(){
		int deviceId = 2;
		Date startDate = DateUtils.addMonths(new Date(), -3);
		String state = "event.xxx";
		Query<**com.google.gson.JsonObject**> query = datastore.createQuery(**com.google.gson.JsonObject**.class);
		List<com.google.gson.JsonObject> list = query
				.disableValidation()
				.filter("device_id =", deviceId)
				.filter(state + " exists", 1)
				.filter("time >=", startDate)										
				.order("-time")
				.disableValidation()
				.asList();
		
//		MongoConnectionUtil.getMongoDatabase().
		System.out.println(list);
	}

org.mongodb.morphia.query.ValidationException: The field 'event.driverSeatBelt' could not be found in 'com.google.gson.JsonObject'
	at org.mongodb.morphia.query.QueryValidator.validateQuery(QueryValidator.java:99)
	at org.mongodb.morphia.query.FieldCriteria.<init>(FieldCriteria.java:37)
	at org.mongodb.morphia.query.FieldCriteria.<init>(FieldCriteria.java:31)
	at org.mongodb.morphia.query.QueryImpl.filter(QueryImpl.java:334)

**Comment by evanchooly** [comment]
Can you please post this to the [mailing list](https://groups.google.com/forum/#!forum/morphia).  We can discuss it there.
