### ISSUE TITLE
Merging a complex query with a complex criteria

### ISSUE THREAD

**Issue by AmitHanoch** [mongodb/morphia#1116]
Hi,
I am converting filters from the client to a QueryImpl using the setQueryObject method.
When I try to add another complex criteria to that query my original query is moved to a field named baseQuery and the new criteria is the query field.
When the query is executed only the new criteria is used and the baseQuery is not used.  
It only happens when the client query is formatted like this: { "$or" : [{ "field1" : { "$regex" : "value1", "$options" : "i"}},...]}
and the new criteria is formatted in the same way(meaning an $or operation).
It seems that when I try to merge 2 $or queries it happens but when I merge $or with $and it concatenates the queries properly.
Am I using it wrong or is it a genuine bug?

**Comment by evanchooly** [comment]
Please post your question and test case to the [mailing list](https://groups.google.com/forum/#!forum/morphia).
