### ISSUE TITLE
Allow elemMatch as last segment in a Path

### ISSUE THREAD

**Issue by VPriesnitz** [mongodb/morphia#1127]
This is a request for bc compatibility. 

In PathTarget resolve, there is an explicit check that the elemMatch placeholder "$" is not the last segment of a path. Imho, this makes it impossible to elemMatch an array of primitives, as well as replacing a complex arrayElement completely. 

I think this check is unneeded since an arrayElement is a valid target.

**Comment by evanchooly** [comment]
fixed by #1128
