### ISSUE TITLE
Not creating compound index keys

### ISSUE THREAD

**Issue by abemammen** [mongodb/morphia#1148]
Using v1.3.1
@Entity("user")
@Indexes(@Index(fields = { @Field("firstName"), @Field("lastName") }, options = @IndexOptions(unique = true)))
public class User {
	@Id
	private ObjectId objectId;
	
	private String firstName;
	private String lastName;
	private Date birthDate;
	private boolean hasPremiumAccess;
	
	public User() {
	}
}

public class MorphiaService {
	private Morphia morphia;
	private Datastore datastore;
	
	public MorphiaService() {
		// Create mongo client that connects to mongodb on host
		MongoClient mongoClient = new MongoClient("127.0.0.1:27017");
		
		// Create morphia instance and connect to Mongo database
		this.morphia = new Morphia();
		String databaseName = "corpus";
		this.datastore = morphia.createDatastore(mongoClient, databaseName);
		this.datastore.ensureIndexes();
	}
}

public class App {
	
	private MorphiaService morphiaService;
	private Datastore datastore; 
	
	public App(){
		this.morphiaService = new MorphiaService();
		Morphia m = this.morphiaService.getMorphia();
		m.map(User.class);
		this.datastore = this.morphiaService.getDatastore();
	}
	
	public void saveEntity() {
		System.out.println("Save entity");
		
		User user1 = new User("Alex", "Foo", new Date(1978, 10, 10 ), true);
		User user2 = new User("Sacha", "Foo", new Date(1989, 2, 23), false);
		User user3 = new User("Alex", "Bar", new Date(1966, 5, 2), false);
		
		this.datastore.save(user1);
		this.datastore.save(user2);
		this.datastore.save(user3);
       }
}

using mongodb shell
mongo
>use corpus
> db.user.getIndexes()
[
	{
		"v" : 1,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "corpus.user"
	}
]
>>> don't see a compound unique key with 'firstName', 'lastName'
>>> I must be missing something.

**Comment by evanchooly** [comment]
You're not mapping your class first so Morphia doesn't know about that index definition.  You have to call `map()` with your classes before `ensureIndexes()`

**Comment by abemammen** [comment]
Ah I was calling map() after ensureIndexes().
Thanks I'll close.
