### ISSUE TITLE
Getting text score on entity when text searching

### ISSUE THREAD

**Issue by ctmay4** [mongodb/morphia#1243]
I didn't realized until recently that Morphia now supports the $meta property.  I have a ton of code in place to work around this so that is definitely good news to me.  I do have a question though.  I added this to my entity so that when score was returned from a query it would be added to the entity, but otherwise would not be saved.

```java
@Transient
private Double _score;
````

I query like this:

```java
q.search(params.getQuery()).project(Meta.textScore("score"));
q.order(Meta.textScore("score"));
```

The results are correct and in the correct order.  However the `score` is null.

I've tried a bunch of different things, but the only thing I found to work was switch the field to a `@Property` and null out the property on save.

So:

```java
@Property("score")
private Double _score;

@PreSave
public void preSave() {
     setScore(null);
}
```

This does work but it seems like I must be doing it wrong.

In addition, unless I specifically use "noClassnameStored = true" on the `@Entity`. the projection added on the query looks like this:

```
projection: { "textScore" : { "$meta" : "textScore"} , "className" : 1} 
```

Since "className" is added it returns no other fields.  That seems like a bug.  I worked around it by added the "noClassnameStored" but what if I needed it?

**Comment by evanchooly** [comment]
Try putting `@NotSaved` on that field.

**Comment by ctmay4** [comment]
I tried that before and it didn't work.  After looking more, I see the issue is my variable name.

```java
@NotSaved
private Double score;
```

works, but 

```java
@NotSaved
private Double _score;
```

do not.  The issue is that `@NotSaved` doesn't allow variable rename like `@Property`.  I will just rename the field in this case.  Thanks.

I'll close this issue, but any idea about the className?  If I have a class where I need to have className stored, the text score meta projection seems to automatically add the className which messes up what is returned.

**Comment by evanchooly** [comment]
I'll have to fire up a test case to look in to the `className` bits and $dayJob is interfering at the moment.  :)

**Comment by ctmay4** [comment]
No problem.  Thanks for taking the time to answer.  I'll close this out.

Fingers crossed they don't let this project die.  It's super useful and I dread having to convert this to another ORM (Spring Data I guess is the only option).

**Comment by evanchooly** [comment]
I'm working with the team at MongoDB to make sure this doesn't die.  I'm still an active user, too, and don't want to migrate.

**Comment by ctmay4** [comment]
Sorry to bring up an ancient issue, but this was previously working and I just noticed the score is no longer returned.  I don't know when it broke however.  In my quick test I wrote:

```java
    @Test
    public void testScoredReturned() {
        Query<NdcProduct> q = _ds.createQuery(NdcProduct.class);
        q.search("Quinidine");
        q.project(Meta.textScore("score"));
        q.order(Meta.textScore("score"));

        System.out.println(q);

        List<NdcProduct> products = q.find().toList();
        assertThat(products).isNotEmpty();
        assertThat(products.get(0).getScore()).isNotNull();
    }
```

The query returns the corrrect results and it does appear to be sorted by score.  The "score" field is not returned however.  The println shows the query as this:

```javascript
{ {"$text": {"$search": "Quinidine"}} , projection: {"score": {"$meta": "textScore"}} }
```

That doesn't even seem to valid.  When I try to run in manually:

```
> { {"$text": {"$search": "daklinza"}} , projection: {"score": {"$meta": "textScore"}} }
2020-01-16T14:29:42.816-0500 E  QUERY    [js] uncaught exception: SyntaxError: unexpected token: ':' :
@(shell):1:10
```

The sample in the documentation looks a bit different (but does correctly return the score).

```
> db.ndc.find(
...    { $text: { $search: "daklinza" } },
...    { score: { $meta: "textScore" } }
... )
{ "_id" : ObjectId("577fa0a4f938a4d9b6cf5e24"), "ndc" : "0003-0215", "labeler" : "00003", "product" : "0215", "type_name" : "HUMAN PRESCRIPTION DRUG", "prop_name" : "DAKLINZA", "non_prop_name" : [ "daclatasvir" ], "dosage_form_name" : "TABLET", "route_name" : [ "ORAL" ], "start_marketing_date" : "20150727", "end_marketing_date" : "20191231", "marketing_category_name" : "NDA", "application_number" : "NDA206843", "labeler_name" : "E.R. Squibb & Sons, L.L.C.", "substances" : [ { "name" : "DACLATASVIR DIHYDROCHLORIDE", "strength" : "60", "unit" : "mg/1" } ], "pharm_class" : [ "Hepatitis C Virus NS5A Inhibitor [EPC]", "P-Glycoprotein Inhibitors [MoA]", "Organic Anion Transporting Polypeptide 1B1 Inhibitors [MoA]", "Organic Anion Transporting Polypeptide 1B3 Inhibitors [MoA]", "Breast Cancer Resistance Protein Inhibitors [MoA]" ], "packages" : [ { "package" : "01", "description" : "28 TABLET in 1 BOTTLE (0003-0215-01) ", "start_marketing_date" : "20150727", "end_marketing_date" : "20191231" } ], "date_added" : ISODate("2016-07-08T12:46:27.670Z"), "date_modified" : ISODate("2019-04-28T03:00:32.432Z"), "score" : 1.1 }
```

Did something change in the Morphia implementation.  This was definitely working before and no longer does.  Thanks again!

**Comment by ctmay4** [comment]
I shouldn't have opened up an old issue.  I'll submit a new one with just this.
