### ISSUE TITLE
Cannot insert a field with '.' ('dot') in field name

### ISSUE THREAD

**Issue by elwin013** [mongodb/morphia#1244]
**Summary:**
Cannot insert any Map that contains e.g. mail (with dot) as a key. Tested on Morphia 1.3.2.

**Steps to reproduce:**
1. Create class containing map, e.g.:
```
class MyObjectWithMap {
        Map<String, String> map = Maps.newHashMap();
}
````
2. Try to save object:
```
MyObjectWithMap obj = new MyObjectWithMap();
obj.map.put("keyOk", "OK");
getDs().save(obj); // Works well
obj.map.put("key.notOK", "notOK");
getDs().save(obj); // Throws exception
```

3. See result:
```
java.lang.IllegalArgumentException: Invalid BSON field name key.notOK
	at org.bson.AbstractBsonWriter.writeName(AbstractBsonWriter.java:532)
	at com.mongodb.DBObjectCodec.encodeMap(DBObjectCodec.java:221)
	at com.mongodb.DBObjectCodec.writeValue(DBObjectCodec.java:198)
	at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:130)
	at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:61)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.operation.BulkWriteBatch$WriteRequestEncoder.encode(BulkWriteBatch.java:392)
(... cut ...)
```
**Additional info:**
MongoDB docs ( https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names ) allows "." char. Also adding a document containing field with "." from Mongo shell works well.

This is same problem to #827, but this time MongoDB (at least from 3.6) allows to use "." char in field names.

**Comment by elwin013** [comment]
Updates title and description to reflect reality - it is again about "."  (dot) char...

**Comment by Shad0wCore** [comment]
Run into the same issue right now. We've got 2018 and MongoDB nor Morphia is able to store a darn dot in the key. 💢👿 😡

**Comment by evanchooly** [comment]
This complaint is actually coming from the driver and not morphia.  morphia just passes the name down to the driver which is rejecting the name.  Consider filing a bug there.  You might also try a new version fo the java driver and see if that behavior persists.

**Comment by elwin013** [comment]
@evanchooly You're right! Sorry for messing up and filling it here. Closing it and going to complain on Mongo bug tracker. ;-)

**Comment by elwin013** [comment]
For everybody running into same problem - there is an issue on Mongo tracker:
https://jira.mongodb.org/browse/JAVA-2810
