### ISSUE TITLE
Cascading (update/delete) support for references [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#130]
This is [Issue 130](http://code.google.com/p/morphia/issues/detail?id=130) moved from a Google Code project.
Added by 2010-10-09T18:11:02.000Z by [jan.liev...@gmail.com](http://code.google.com/u/108782420348489347020/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, Component-Mapper, Milestone-Icebox

## Original description

The fact that the referenced object must have been saved in Mongo before saving the object referencing it is quite inconvenient and totally solvable through some code that also persists the referenced objects first before saving the referencing object. Something similar to CascadeType (PERSIST and REMOVE for starters) in the description on OneToMany or OneToOne relations. (This can be done in the DAO class on the save and remove methods)

**Comment by evanchooly** [comment]
managing referenced objects should be an application concern.  morphia is moving away from such transparent operations in favor of more explicit handling of references.
