### ISSUE TITLE
Add support for $slice in queries [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#138]
This is [Issue 138](http://code.google.com/p/morphia/issues/detail?id=138) moved from a Google Code project.
Added by 2010-10-24T15:36:08.000Z by [t.broyer](http://code.google.com/u/t.broyer/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, Milestone-Release1.0

## Original description

It could be as easy (from the user POV) as using a special syntax for the retrieveFields. For instance,
 - retrieveFields(true, "comments[0-2]") would map to {comments:{$slice:2}}
 - retrieveFields(true, "comments[5]") would map to {comments:{$slice:[5,1]}}
 - retrieveFields(true, "comments[-5-5]") would map to {comments:{$slice:-5}}
 - retrieveFields(true, "comments[20-10]") would map to {comments:{$slice:[20,10]}}
 - retrieveFields(true, "comments[-20-10]") would map to {comments:{$slice:[-20,10]}}
 - possibly, retrieveFields(true, "comments[0-2].id") could be used as a shorthand syntax and map to {comments:{$slice:2}, "comments.id":1}

This is one example of a syntax, but another one could be used, more directly mapping to the $slice values: [i] -> {$slice: i} and [i,j] -> {$slice:[i,j]}

Of course, retrieveFields could also be, instead or in addition, extended; for example, allowing it to be called several times, incrementally building the underlying DBObject, e.g.
 - retrieveFields(true, "comments", 2).retrieveFields(false, "comments.id")
   -> {comments:{$slice:2}, "comments.id":false}
 - retrieveFields(true, "comments", 2).retrieveFields(true, "comments.id")
   -> {comments:{$slice:2}, "comments.id":true}
and/or passing an object as argument (a bit similar to the new Criteria API for filters in queries):
   Fields fields = new Fields();
   fields.add("comments", 5); // or add("comments", 20, 10) for instance
   fields.add("comments.id", true");
   query = query.retrieveFields(fields);

**Comment by Karnifexx** [comment]
+1 for this asap. This is particularly usefull when there are large arrays and I only want part of it.

**Comment by elvis9xu** [comment]
+1 asap. I need to use this feature currently, is there any way to wind it？

**Comment by florianthievessen** [comment]
+1
