### ISSUE TITLE
add support for "distinct" [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#219]
This is [Issue 219](http://code.google.com/p/morphia/issues/detail?id=219) moved from a Google Code project.
Added by 2011-01-30T12:16:27.000Z by [88.ma...@gmail.com](http://code.google.com/u/107475744370200542693/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low

### Original description

    http://www.mongodb.org/display/DOCS/Aggregation#Aggregation-Distinct

**Comment by evanchooly** [comment]
can be done with aggregations and groups
