### ISSUE TITLE
AND queries does not allow several filters on the same criteria [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#225]
This is [Issue 225](http://code.google.com/p/morphia/issues/detail?id=225) moved from a Google Code project.
Added by 2011-02-09T13:33:03.000Z by [johan.se...@gmail.com](http://code.google.com/u/106047730092233227606/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Low

### Original description

For instance,
    
    query.and(
    	query.criteria("name").contains("Jack"),
            query.criteria("name").startsWithIgnoreCase("Hip")
    );
    
One would expect that the query would match names that start with Hip and also contains Jack.  The produced query however looks as follows:
    
    { "name" : { "$regex" : "^Hip" , "$options" : "i"}}
    
i.e. the first criteria is missing.
    
    
    
<b>What version are you using? (Morphia/Driver/MongoDB)</b>
morphia 1.0 snapshot / mongodb 1.6.5 / driver 2.4

**Comment by ndsurendra** [comment]
I'm using verison 1.0.1. Facing similar issue.
dbQuery.and(
                dbQuery.criteria("createdTime").greaterThanOrEq("2015-11-25"),
                dbQuery.criteria("createdTime").lessThan("2015-11-30")
        );

this is getting translated to:
{ "$and" : [ { "created_time" : { "$gte" : { "$date" : "2015-11-25"}}} , { "created_time" : { "$lt" : { "$date" : "2015-11-30"}}}]}

And I am getting empty response from the DB.

The query should have been somthing like:
{"created_time" : {"$gte" : ISODate("2015-11-25"), "$lt" : ISODate("2015-11-30")}}

Please correct me if I am wrong.

**Comment by evanchooly** [comment]
You're passing Strings when you should be passing Dates.

**Comment by ndsurendra** [comment]
Sorry for the mislead. I've changed the code snippet for brevity.

Below is the exact snippet where 'fromDate' and 'toDate' are of type java.util.Date
dbQuery.and(
                dbQuery.criteria("createdTime").greaterThanOrEq(fromDate),
                dbQuery.criteria("createdTime").lessThan(toDate)
        );

The issue remains the same.

**Comment by evanchooly** [comment]
This was cleaned up somewhere along the way.  No longer an issue.

**Comment by daibertdiego** [comment]
I'm having this problem using criterias in "_id" field twice. 
The final query has only the last criteria.
My morphia version is 1.3.2.
