### ISSUE TITLE
Problem with using many DataStores [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#230]
This is [Issue 230](http://code.google.com/p/morphia/issues/detail?id=230) moved from a Google Code project.
Added by 2011-02-24T07:54:40.000Z by [google-a...@codesmell.de](http://code.google.com/u/113306752357053708143/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

    
    package com.nexuus.jobs.data.repository;
    
    import java.net.UnknownHostException;
    
    import org.junit.Before;
    import org.junit.Test;
    
    import com.google.code.morphia.Datastore;
    import com.google.code.morphia.Morphia;
    import com.google.code.morphia.utils.Assert;
    import com.mongodb.DB;
    import com.mongodb.Mongo;
    import com.mongodb.MongoException;
    import com.nexuus.jobs.data.domain.Category;
    
    public class CategoryUweTest {
        private Category phoneCategory = new Category();
        private Category iphoneCategory = new Category();
        private Category appleCategory = new Category();
        private CategoryRepositoryDAO2 categoryDAO;
    
        protected Mongo mongo;
        protected Datastore ds;
        protected Morphia morphia = new Morphia();
    
        @Before
        public void setUp() {
            try {
                this.mongo = new Mongo();
            } catch (Exception e) {
               
            }
               
            this.ds = this.morphia.createDatastore(this.mongo, &quot;morphia_test&quot;);
            this.morphia.createDatastore(this.mongo, &quot;morphia_test2&quot;)
            this.categoryDAO = new CategoryRepositoryDAO2(ds);
        }
    
        @Test
        public void testCategoryTreeSavedAndRecovered() {
            phoneCategory.addChildrenCategory(appleCategory);
            appleCategory.setParentCategory(phoneCategory);
    
            appleCategory.addChildrenCategory(iphoneCategory);
            iphoneCategory.setParentCategory(appleCategory);
    
            categoryDAO.save(phoneCategory);
            categoryDAO.save(appleCategory);
            categoryDAO.save(iphoneCategory);
    
            phoneCategory = categoryDAO.get(phoneCategory.getId());
            appleCategory = categoryDAO.get(appleCategory.getId());
            iphoneCategory = categoryDAO.get(iphoneCategory.getId());
    
            Assert.isTrue(
                    phoneCategory.getChildrenCategories().contains(appleCategory),
                    &quot;Parent does not contain child&quot;);
    
            Assert.isTrue(appleCategory.getParentCategory().equals(phoneCategory),
                    &quot;Child has not expected parent&quot;);
    
            Assert.isTrue(
                    appleCategory.getChildrenCategories().contains(iphoneCategory),
                    &quot;Parent does not contain child&quot;);
    
            Assert.isTrue(iphoneCategory.getParentCategory().equals(appleCategory),
                    &quot;Child has not expected parent&quot;);
    
        }
    }
    
    I have highlighted in red the code that is causing the problem. As you can see what I am doing is:
    
       1. Creating an instance of Mongo
       2. Calling Morphia.createDataStore for one DB (morphia_test), which is the one I use for create the DAO.
       3. Calling Morphia.createDataStore of one DB (morphia_test2), which is not used.
       4. When the test run, I get the error.
    
    No mater if I create the DAO before the the second call to Morphia.createDataStore, the error will happen.
    
    In my code, I have this problem because Spring is calling a factory class for create the datastore via Morphia.createDataStore two times, one for a main database, and other for a &quot;historic&quot; db. This is the root of my problem.
    
    My question is: this is a bug? or I have understood something wrong?
    
    I have not reviewed the code of Morphia deeply, but browsing the source, it seems that DataStoreHolder class can only keep one copy of a datastore which makes me think why I am only getting the error with this class (which has references to it selfs) and not with other classes (without references).
    I guess it is happengin something  like this:
    
       1. On save, the DAO is using the datastore assigned to the DAO.
       2. On read, and with @Reference, Morphia is recovering somehow the DAO stored in DataStoreHolder, and is not finding the entities, simply because they are stored in the datastore assigned to the DAO.

**Comment by evanchooly** [comment]
I see I let that PR through without an explicit test.  That was my failure.  I'll add one now to confirm.

**Comment by ravikiran1226** [comment]
still i am having same problem with 1.0.1 version of morphia

**Comment by evanchooly** [comment]
See #757
