### ISSUE TITLE
Support geoNear command [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#287]
This is [Issue 287](http://code.google.com/p/morphia/issues/detail?id=287) moved from a Google Code project.
Added by 2011-06-17T12:25:14.000Z by [scotthernandez](http://code.google.com/u/scotthernandez/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low

### Original description

    Add geoNear command wich returns a geoResult<T> object which has distance for each entity.

**Comment by trishagee** [comment]
Is it mandatory to support the [geoNear command](http://docs.mongodb.org/manual/reference/command/geoNear/) when Morphia supports the [near query](http://docs.mongodb.org/manual/reference/operator/query/near/)?

**Comment by evanchooly** [comment]
I would say so, yes, as they have fairly different semantics and use cases.

**Comment by evanchooly** [comment]
Silly me, @trishagee.  I see what you're asking, and I'm going to say "no" unless someone specifically asks for this.  And maybe even then.  ;)
