### ISSUE TITLE
Add support for geo/2d compound indexes [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#290]
This is [Issue 290](http://code.google.com/p/morphia/issues/detail?id=290) moved from a Google Code project.
Added by 2011-06-24T01:33:12.000Z by [Drew.Kut...@gmail.com](http://code.google.com/u/114303736160637790482/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Low

### Original description

    The @Indexes annotation currently doesn't support 2d indexes.
    
    See: http://groups.google.com/group/morphia/browse_thread/thread/618ba13fb2a8a588

**Comment by trishagee** [comment]
If you go ahead with the proposed changes for Index annotations, that will provide a solution to this issue. I've implemented a test to see if that would work, and it passes: https://github.com/trishagee/morphia/commit/a5248aaab5920922c9ed84dc3d4832a152d41fab
