### ISSUE TITLE
Morphia should fail when .or() is used twice [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#292]
This is [Issue 292](http://code.google.com/p/morphia/issues/detail?id=292) moved from a Google Code project.
Added by 2011-06-29T19:48:26.000Z by [Pasko.Bo...@gmail.com](http://code.google.com/u/108027977969618508170/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Low
### Original description

morphia-0.99.jar, mongo-java-driver-2.5.3.jar, mongodb-10gen 1.8.1

MongoDB does not allow to have multiple "$or" conditions and Morphia just silently uses the last "$or" condition applied. Surprisingly enough, the rich Query API builds the whole query structure and then just blindly sets the "$or" field when building MongoDB query DBObject.

This should be detected either when
 a) When building MongoDB object (which is relatively easy - you just have to check "$or" field before setting it)
 b) When .or() is called.

I think that throwing UnsupportedOperationException is adequate response in this case.

**Comment by evanchooly** [comment]
multiple $or clauses are allowed.
