### ISSUE TITLE
Accessing @Entity("fs.files") types results in a ClassCastException [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#308]
This is [Issue 308](http://code.google.com/p/morphia/issues/detail?id=308) moved from a Google Code project.
Added by 2011-08-09T21:03:15.000Z by [raymond....@gmail.com](http://code.google.com/u/114363444664250641927/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Low

### Original description

    I am using Morphia trunk from today.
    Driver: mongo-2.5.1.jar
    Mongod 1.8.2 64bit
    
    Here is the exception:
    
    Exception in thread &quot;main&quot; java.lang.ClassCastException: com.mongodb.gridfs.GridFSDBFile cannot be cast to com.mongodb.BasicDBObject
    	at com.google.code.morphia.query.MorphiaIterator.getNext(MorphiaIterator.java:60)
    	at com.google.code.morphia.query.MorphiaIterator.next(MorphiaIterator.java:47)
    
    
    The solution is to not use BasicDBObject but the DBObject interface.
    
    I created a patch relative to the directory: http://morphia.googlecode.com/svn/trunk/morphia/src/main/java/com/google/code/morphia
    
    See attached.
    
    I grant that my use case is not a common on, but I would argue that using the interface is better than the implementation
    if one can....

**Comment by evanchooly** [comment]
#153 will clean this up
