### ISSUE TITLE
Don't complain when validating with positional operator or array ordinals [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#333]
This is [Issue 333](http://code.google.com/p/morphia/issues/detail?id=333) moved from a Google Code project.
Added by 2011-10-19T21:00:31.000Z by [scotthernandez](http://code.google.com/u/scotthernandez/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

When doing an update like this don't complain: "array.3.field"

**Comment by evanchooly** [comment]
fixed
