### ISSUE TITLE
No way to specify jsMode in Datastore.mapReduce [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#368]
This is [Issue 368](http://code.google.com/p/morphia/issues/detail?id=368) moved from a Google Code project.
Added by 2012-01-23T14:13:48.000Z by [n...@transmachina.com](http://code.google.com/u/107615077134874340240/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low

### Original description

This is supported in Mongo 2+ I believe. I need this to optimize the many small map/reduce calls I make.

**Comment by evanchooly** [comment]
If this is of interest to anyone, we can reopen.  Closing for now.
