### ISSUE TITLE
Cannot search using hasAnyOf when using a composite id and noClassNameStore=true [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#387]
This is [Issue 387](http://code.google.com/p/morphia/issues/detail?id=387) moved from a Google Code project.
Added by 2012-03-08T07:44:31.000Z by [johan.ha...@gmail.com](http://code.google.com/u/105676376875942041029/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Low
## Original description

Hi, 

I have an entity annotated with @Entity where noClassNameStored is set 
to true and the id of the entity is a composite id. When persisting 
the entity no class name is stored in Mongo neither for the entity or 
for the ID object. But when I search using the following query 

``` java
List<MyCompositeId> ids = ... 
List<MyEntity> entityList = find(createQuery().field("_id").hasAnyOf(ids)).asList(); 
```

Morphia inserts the class name of the composite id in the query and 
thus no entities are found. If I manually cut and paste the query and 
remove the className from the query it's successful. I assume that 
this is a bug? 

If I inspect `createQuery().field("_id").hasAnyOf(ids)` in the debugger the query looks like this:

``` json
{
    "_id": {
        "$in": [{
            "className": "com.x.y.MyCompositeId",
            "x": "x",
            "y": "y"
        }, {
            "className": "com.x.y.MyCompositeId",
            "x": "x",
            "y": "z"
        }]
    }
}
```

If I manually remove the className attribute from the query and execute in the the mongodb console it finds the entities.

My classes looks resembles this:

``` java
@Entity(noClassNameStored=true)
public class MyEntity {
   @Id
   private MyCompositeId myId;

   public MyEntity(String x, String y) {
    this.myId = new MyCompositeId(x, y);
   }

   ...
}

public class MyCompositeId {
   private String x;
   private String y;

   public MyCompositeId(String x, String y) {
        this.x = x;
    this.y = y;
   }
}
```

**Comment by evanchooly** [comment]
related #307
