### ISSUE TITLE
Combined greaterThan and lessThanOrEq generates poor query [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#391]
This is [Issue 391](http://code.google.com/p/morphia/issues/detail?id=391) moved from a Google Code project.
Added by 2012-03-19T19:31:29.000Z by [n...@transmachina.com](http://code.google.com/u/107615077134874340240/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Low
### Original description

Using Morphia 0.99, I have the following code:

```
q.field("wordCount").greaterThanOrEq(1);
q.field("wordCount").lessThanOrEq(2);
```

According to http://code.google.com/p/morphia/wiki/Query this should work, but it generates:

```
{ "wordCount" : { "$gte" : 1}} , { "wordCount" : { "$lte" : 2}} 
```

and the query parser ignores one of the bounds and I lose index efficiency. Shouldn't the generated query be:

```
{ "wordCount" : { "$gte" : 1, "$lte" : 2}} ?
```

Is there a way I can hardcode this into a Morphia Query object?

**Comment by evanchooly** [comment]
The query shape is certainly up for debate but the generated query *does* properly use an index so I'm closing this one out.
