### ISSUE TITLE
Support replacing "untypedTypeEncoders" in DefaultConverters class [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#420]
This is [Issue 420](http://code.google.com/p/morphia/issues/detail?id=420) moved from a Google Code project.
Added by 2012-07-22T10:29:48.000Z by [o...@eyeviewdigital.com](http://code.google.com/u/106568429197945420776/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Low

### Original description

    <b>What version are you using? (Morphia/Driver/MongoDB)</b>
    Morphia version : 0.99
    Mongo driver: 2.7.3
    
    Issue description:
    Currently, DefaultConverters class exposes two methods addConverter/removeConverter to allow adding/removing the converts, however in case of &quot;untyped&quot; converter (tc.getSupportedTypes() == null) these methods doesn't work as expected. 
    
    Steps to reproduce:
    I tried to replace the default EnumConverter with a custom Implementation (I extended the default EnumConverter implementation to support supplying a default value of the enum in case of decoding failure)
    Here's a snippet of what i did:
    morphia.getMapper().getConverters().removeConverter(new EnumConverter());
    morphia.getMapper().getConverters().addConverter(new CustomEnumConverter());
    
    Actual behavior:
    While debugging i noticed that the enum decoding was done by EnumConverter, although this converter was supposed to be removed.
    
    Expected behavior:
    Enum decoding should be done by the new custom enum decoder.
    
    Workaround:
    I accessed by reflection the &quot;untypedTypeEncoders&quot; list in DefaultConverters instance, 
    then replaced manually the EnumConverter with my CustomEnumConverter, and this did the trick for me.

**Comment by evanchooly** [comment]
fixed with #658

**Comment by evanchooly** [comment]
fixed with #612 instead
