### ISSUE TITLE
MappingException - Morphia ignores @Embedded when reading if the class implements Iterable

### ISSUE THREAD

**Issue by ThomasWidmann** [mongodb/morphia#580]
I just switched from com.google.code.morphia to org.mongodb.morphia:0.106. 
Now I run into a MappingException where I suspect that this is propably a bug.

I am able to store an object in a test case. this object embeds another object (class Period) which just contains 2  java.util.Date properties. Reading the same object in same test case leads to a mapping exception.

Environment:
OS: Mac OsX Mavericks and Windows7
java version: 1.7.0_21-b12 (Mac)
MongoDB version: 2.4.9
Location: Germany (just mentioned regarding time offset and Date handling)

Embedded Class which could not be materialized from db:
```
@Embedded
public class Period implements Comparable<Period>, Iterable<Date>, Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -9057973502087536590L;
	// ~ Static fields/initializers
	// -------------------------------------------------------------------

	// ~ Instance fields
	// ------------------------------------------------------------------------------
	protected Date from;
	protected Date until;
```
Document in Database:
```
{ "_id" : "7500af4c-e63e-4ef0-88ab-b7e289ce7fd4" , 
"className" : "de.widas.team.projektauftrag.model.Projektauftrag" , 
"projektbezeichnung" : "Test02: DSL Provisioning bei 1und1" , 
"year" : 2014 , "pnr" : 0 , "projekttypId" : "1.1.1" , "einsatzortId" : "01" ,
"geplanteProjektlaufzeit" : { "from" : { "$date" : "2014-01-31T23:00:00.000Z"} , "until" : { "$date" : "2014-06-29T22:00:00.000Z"}} , 
"paStatusId" : "01" , 
"finanzvolumen" : { "value" : 40000.0 , "currency" : { "currencyCharacter" : "EUR"} , "intPrecision" : 6 , "extPrecision" : 6} , "zeitvolumen" : { "wert" : { "unscaled" : 40 , "scale" : 0} , "timeUnitId" : "02" , "timeUnitScale" : "DEFAULT_SCALE"} , 
"auftragspositionen" : [ 
{ "uuid" : "98787519-832e-47f9-af5f-d87003b1b55e" , "userid" : "aUserId" , "bezeichnung" : "Test Position" , "zeitvolumen" : { "wert" : { "unscaled" : 1200 , "scale" : 0} , "timeUnitId" : "04"} , "maxLimit" : true , "rolle" : "Softwareentwickler" , "honorarsatz" : { "moneyAmount" : { "value" : 100.0 , "currency" : { "currencyCharacter" : "EUR"} , "intPrecision" : 6 , "extPrecision" : 6} , "timeUnitId" : "01" , "timeUnitScale" : "DEFAULT_SCALE"}} , 
{ "uuid" : "005c77f7-a169-4400-9427-b26ea396a158" , "userid" : "aUserId" , "bezeichnung" : "Test Position" , "zeitvolumen" : { "wert" : { "unscaled" : 2400 , "scale" : 0} , "timeUnitId" : "04"} , "maxLimit" : true , "rolle" : "Softwareentwickler" , "honorarsatz" : { "moneyAmount" : { "value" : 100.0 , "currency" : { "currencyCharacter" : "EUR"} , "intPrecision" : 6 , "extPrecision" : 6} , "timeUnitId" : "01" , "timeUnitScale" : "DEFAULT_SCALE"}}] , 
"creationTime" : { "$date" : "2014-02-26T07:28:32.113Z"}}
```

used in other class as property:
```
private Period geplanteProjektlaufzeit;
```

service to access and store data:
```
public class ProjektauftragRepositoryImpl extends BasicDAO<Projektauftrag, String> implements ProjektauftragRepository {

	@Inject
	public ProjektauftragRepositoryImpl(Morphia morphia, Mongo mongo, @Named("dbname") String dbname) {
		super(checkNotNull(mongo), checkNotNull(morphia), dbname);
		getDatastore().ensureIndexes();
		getDatastore().ensureCaps();
		LoggerFactory.getLogger(ProjektauftragRepositoryImpl.class).debug("Ensure Indexes and Caps!");
	}

	@Override
	public Projektauftrag findById(String pid) {
		Query<Projektauftrag> q = createQuery();
		q.criteria("_id").equal(pid);
		Projektauftrag pa = findOne(q);
		return pa;
	}
```

test case (excerpt)
```
...
PAREPO.save(lPA);
Projektauftrag foundPA = PAREPO.findById(lPA.getPid());
assertNotNull(foundPA);
..
```
exception when executing junit test:
```
java.lang.RuntimeException: org.mongodb.morphia.mapping.MappingException: Error setting value from converter (PassthroughConverter) for de.widas.team.projektauftrag.model.Projektauftrag.geplanteProjektlaufzeit to { "from" : { "$date" : "2014-01-31T23:00:00.000Z"} , "until" : { "$date" : "2014-06-29T22:00:00.000Z"}}
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:164)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:168)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:680)
	at org.mongodb.morphia.mapping.MappedField.setFieldValue(MappedField.java:568)
	at org.mongodb.morphia.converters.DefaultConverters.fromDBObject(DefaultConverters.java:134)
	at org.mongodb.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:155)
	at org.mongodb.morphia.mapping.Mapper.readMappedField(Mapper.java:606)
	at org.mongodb.morphia.mapping.Mapper.fromDb(Mapper.java:581)
	at org.mongodb.morphia.mapping.Mapper.fromDBObject(Mapper.java:296)
	at org.mongodb.morphia.query.MorphiaIterator.convertItem(MorphiaIterator.java:78)
	at org.mongodb.morphia.query.MorphiaIterator.processItem(MorphiaIterator.java:65)
	at org.mongodb.morphia.query.MorphiaIterator.next(MorphiaIterator.java:60)
	at org.mongodb.morphia.query.QueryImpl.get(QueryImpl.java:403)
	at org.mongodb.morphia.dao.BasicDAO.findOne(BasicDAO.java:251)
	at de.widas.team.projektauftrag.model.ProjektauftragRepositoryImpl.findById(ProjektauftragRepositoryImpl.java:36)
	at de.widas.team.projektauftrag.model.ProjektauftragRepositoryTest.test_ProjektauftragInBearbeitungMitZweiPositionenSpeichern(ProjektauftragRepositoryTest.java:46)
```

**Comment by ravindra1986** [comment]
Instantiation of [simple type, class org.bson.types.ObjectId] value failed: invalid hexadecimal representation of an ObjectId: [58abc704c1d24e05ce5851gt] (through reference chain: com.claix.resource.rest.model.Customer["id"])
Please Help Me ASAP.

**Comment by ravindra1986** [comment]
Hi,
I am new to mongo-morphia, i have wrote entity using marphia when i am trying to persist getting error.
my code snipet is given below.

---------------------------------------------------
public abstract class BaseEntity {
	@Id
    @Property("id")
    protected ObjectId id;
 
    @Version
    @Property("version")
    private Long version;
 
    public BaseEntity() {
        super();
    }
 
   //All getter and Setter
 
}
-------------------------------------------------------
@Entity
public class Customer extends BaseEntity{
	public Customer(){
		
	}
	
	  private String name;
	   
	   @Embedded
	   private Address address;
	    
	    
	 
	    public Customer(String name, Address address) {
			super();
			this.name = name;
			this.address = address;
		}
		 //All getter and Setter
}
-------------------------------------------------------
@Embedded
public class Address{
	
	private String number;
    private String street;
    private String town;
    private String postcode;
	 public Address(){
		 
	 }
    
    public Address(String number, String street, String town, String postcode) {
	this.number = number;
	this.street = street;
	this.town = town;
	this.postcode = postcode;
}
//All getter and Setter
}
----------------------------------------------------------------------------
In DAOimpl.
----------------------------------------------------------------------------
public class CustomerDAOImpl extends BasicDAO<Customer, ObjectId>
{

	private static final String COLLECTION_NAME="Customer";
	
	public CustomerDAOImpl(	MongoClient mongoClient, Morphia morphia, String dbName) {
		super( mongoClient, morphia, dbName);
	}
	
	
	public Key<Customer> save(Customer cust){
		return (Key<Customer>) ds.save(cust,COLLECTION_NAME);
	}
		
}
----------------------------------------------------------------------------------------
Getting exception 	 
	Instantiation of [simple type, class org.bson.types.ObjectId] value failed: invalid hexadecimal representation of an ObjectId: [58abc704c1d24e05ce5851gt] (through reference chain: com.claix.resource.rest.model.Customer["id"])
