### ISSUE TITLE
Lifecycle Method is called in Query.field().hasThisElement() when look up an element in embedded Array  

### ISSUE THREAD

**Issue by ghost** [mongodb/morphia#593]
As I create a local variable in the method hasThisElement() as below, it triggered the life cycle event 'prePersist' of the local variable which should only be called when persist to db.

```
createQuery(GroupChat.class).field("members").hasThisElement(new GroupMember(name,id));

```

it trigged a prePersist method defined in GroupMember, which would break the seach condition.

Morphia version: 0.107
JDK version: 1.7.0_07
Mongodb version: 2.11.4

**Comment by evanchooly** [comment]
related to #606
