### ISSUE TITLE
More flexibility for "untyped" converters

### ISSUE THREAD

**Issue by dkilmer** [mongodb/morphia#612]
This request is specifically geared toward Collection converters, but it could apply to other things. 

Basically, creating a general replacement for `IterableConverter` is not possible (unless I'm missing something, which is *always* possible), because `IterableConverter` will always get chosen first. You can create a "typed" converter for specific collection types (say, `List` or `Set`), but this causes lists or sets of embedded objects not to be converted from `DBObject` when put back into the chain with `DefaultConverters.decode()`.

There are a bunch of ways to address this, the easiest of which is to add new untyped converters to the top of `untypedTypeEncoders`. If that's likely to disrupt people who count on the current behavior, there could be a non-default `addConverter()` that specifically asks to be put on top. The beauty of this solution (IMO) is that proper use of `isSupported()` in custom converters could allow people to create custom converters depending on what is *contained* in a collection, as well as specific types of collections.

If anyone else besides me is interested in this feature, please say so. I'd be happy to do a pull request for the change.

**Comment by evanchooly** [comment]
fixed along with #658

**Comment by evanchooly** [comment]
I'd hoped to pick up both at once.  I was *so* close but I'm going to have split them up.

**Comment by evanchooly** [comment]
The return type of Mapper.getConverters() has changed from DefaultConverters to simply Converters.  (note the name clash with the annotation.  Unfortunate but I couldn't really thing of a better name)
