### ISSUE TITLE
Tech Debt: Simplify ProxiedReference 

### ISSUE THREAD

**Issue by trishagee** [mongodb/morphia#623]
Need to investigate the uses of `ProxiedReference` as it might be possible to simplify some of this and not have public methods that aren't really meant for public use.  The suppression of checkstyle and use of non-standard method names suggests there may be a cleaner way of doing this.

This will probably be a breaking change, as these methods are public although they are only meant for internal use

**Comment by evanchooly** [comment]
proxied references are going away
