### ISSUE TITLE
Mapper is not checking isMapped() 

### ISSUE THREAD

**Issue by rbordo** [mongodb/morphia#630]
Dear Morphia-Team,
during our current project we noticed, that Mapper.addMappedClass(...) is not checking if the given class has already been mapped. This leads to some nasty multiple (log) warnings. 

As a workaround we did something like this:

public class MorphiaMapper extends Mapper {

	public MorphiaMapper(MapperOptions options) {
		super(options);
	}
	
	@SuppressWarnings("rawtypes")
	@Override
	public MappedClass addMappedClass(Class c) {
		if(!isMapped(c)) {
			return super.addMappedClass(c);
		}
		return this.getMCMap().get(c.getName());
	}
}

But it would be great, if you added this check to the Mapper class itself.

Thanks in advance.

Best regards.

Robert

**Comment by evanchooly** [comment]
I think this was fixed with #713.  Can you download/build a new snapshot and confirm this fixes it for you?

**Comment by evanchooly** [comment]
This should be fixed now.  Please reopen if you find that's not the case.
