### ISSUE TITLE
Morphia and Play Framework 2.3.0

### ISSUE THREAD

**Issue by contiero-roberto** [mongodb/morphia#631]
Hi, I'm using Morphia 0.108 on my project built with Play Framework 2.3.0 (not as plugin but simply as imported library). If I use package mapping method to map my entities (i.e. morphia.mapPackage("models"); ), Morphia throws a <code>java.lang.ClassNotFoundException</code>. Instead, if I use the map entity by entity, it works fine.
Debugging the source code I think that I have found the problem: in the class ReflectionUtils, line 487, you retrieve the classes from package using classLoader <code>Thread.currentThread().getContextClassLoader()</code> that, in my case, is equal to <i>(play.PlayRun$$anonfun$11$$anon$2) ReloadableClassLoader(v1){file:/C:/Users/Roberto......</i>
Then, inside the getFromDirectory method (line 447), you create a new Class object using <code>Class.forName(name);</code> as you can see from java docs, Class.forName method loads the class using the class loader of the current class (ReflectionUtils in this case) that, in my case, is equal to <i>(play.PlayRun$$anonfun$10$$anon$1) PlayDependencyClassLoader{file:/C:/Users/Roberto.........</i>
Maybe, it would be more correct to pass the loader to the getFromDirectory method and load the class with a <code>Class.forName(name, true, loader)</code>.
By

Roberto

**Comment by evanchooly** [comment]
I've just pushed a change that should fix this for you.  If you don't mind, once jenkins has a chance to push a new snapshot build out, could you try 0.111-SNAPSHOT and verify this clears up the issue for you?  Thanks.  If you can't, that's fine.  We can reopen this issue after 0.111 ships and take another look.

**Comment by contiero-roberto** [comment]
Thank you for the fix. It seems to work.
By

Roberto
