### ISSUE TITLE
Accumulator sum

### ISSUE THREAD

**Issue by suman724** [mongodb/morphia#632]
I am using Morphia 0.108

I am trying to use the static method sum in the class org.mongodb.morphia.aggregation.Group. This method takes a string as a parameter and is returning an Accumulator. The parameter I want to pass is a constant instead of key.

For example - I am using this in an aggregation query to count customers by priority. 

{ $group : { "_id" : "$priority", "customersPerStatus" : { $sum : 1 } }} 

I did not find a way in Morphia framework to pass constants to the Sum accumulator. 

Any comments?

**Comment by evanchooly** [comment]
fixed with the merge of #666
