### ISSUE TITLE
Changing equal to contains when using Pattern.CASE_INSENSITIVE

### ISSUE THREAD

**Issue by defaultbr** [mongodb/morphia#638]
when you try to search a user with insensitive case

UserInDB: DefaultBR
User; default

morphia/mongodb doesnt allow you to search for insensitive case, so you have to make a pattern

Pattern patternLogin = Pattern.compile(login, Pattern.CASE_INSENSITIVE);

than do query/find using this patternLogin, it change the behaivor of equal to .contains
ex:

String searchFor = "def"
Pattern patternLogin = Pattern.compile(searchFor, Pattern.CASE_INSENSITIVE);
UserInDB = DefaultBR

using pattern if i try to using field("login").equal(patternLogin); it will return the DefaultBR, why?

to fix this i need to edit the pattern login for something like:

Pattern regexLogin = Pattern.compile("^" + searchFor+ "$", Pattern.CASE_INSENSITIVE);

i have to add the "^" and "$", is there a way to make morphia equals to do this trick or i have to make my own Pattern.Compiler class to add ^ and $ automatically?

**Comment by evanchooly** [comment]
You'll have to do that manually.  Not all case insensitive searches need those anchors.
