### ISSUE TITLE
Use Factory Pattern instead of new  [moved]

### ISSUE THREAD

**Issue by jyemin** [mongodb/morphia#65]
This is [Issue 65](http://code.google.com/p/morphia/issues/detail?id=65) moved from a Google Code project.
Added by 2010-06-12T14:46:26.000Z by [juri.ku...@gmail.com](http://code.google.com/u/100317089741718172347/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, Milestone-Release1.1

### Original description

    It would be nice if instances of mapped classes would be constructed using a factory.
    
    This would allow the use of dependency injection frameworks like Spring or Guice with morphia.
    
    Maybe MapperOptions could hold that factory, which by default just uses ReflectionUtils.createInstance() but can be overridden if necessary.
    
    The factory could also take care of constructor parameters (Issue 26)

**Comment by evanchooly** [comment]
This feature already exits:  org.mongodb.morphia.mapping.MapperOptions#getObjectFactory

The guice support makes use of this feature.
