### ISSUE TITLE
Embedded annotation documentation bug

### ISSUE THREAD

**Issue by yeefan** [mongodb/morphia#661]
I refer to the following page:
https://github.com/mongodb/morphia/wiki/EmbeddedAnnotation
There is this line:
"We just annotate the above classes with `@Property` and `@Embedded`"
Problem is, `@Property` is never found anywhere else on this page.

Additionally, it seems that the `@Embedded` annotation was never needed at the first place. If a class C has no annotations, and a document D contains an unannotated field of class C, then the instance of class C gets embedded into the document D when saved into the database.

**Comment by evanchooly** [comment]
updated the bottom of the page with some text discussing the optional nature of the annotation.
