### ISSUE TITLE
Query.retrievedFields() inserts "className" for entity with noClassnameStored=true

### ISSUE THREAD

**Issue by ks280first** [mongodb/morphia#670]
I have an entity annotated with noClassnameStored=true

However, when I use the Query object method retrievedFields(boolean include, String... fields), it is inserting an entry in the fields array for "className".  This causes problems, as I have an index that covers this query and is now not covered because of this extra field.

My Example:
Query<Report> q = datastore.createQuery(Report.class);
q.field("_id").equal( "FOO" );
q.retrievedFields(true , "_id", "reportType", "year", "quarter", "datePeriodEnd");
q.order("-datePeriodEnd");
logger.debug("db.report.find("+q.getQueryObject().toString()+","+q.getFieldsObject().toString()+");");

Prints:
db.report.find({ "_id" : "FOO"}, { "quarter" : 1 , "reportType" : 1 , "datePeriodEnd" : 1 , "year" : 1 , "className" : 1 , "_id" : 1});

**Comment by evanchooly** [comment]
possibly related #293
