### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by scottbessler** [mongodb/morphia#673]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with morphia. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable morphia on @Sourcegraph by going to https://sourcegraph.com/github.com/mongodb/morphia and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by evanchooly** [comment]
I don't think that repo is owned by any of us and so we lack the rights to update that.
