### ISSUE TITLE
Allow configuration without annotations

### ISSUE THREAD

**Issue by ctmay4** [mongodb/morphia#678]
Sometimes there have entities I would like to persist that I don't have control of.  Usually coming from a library I am using.  I could subclass them and add @Entity, @Id and @Embedded annotations, but if they are complex, deep structures that becomes difficult.  

Could there be a way I could programatically tell Morphia which classes are entities and which fields in each class are identifiers?

**Comment by fredericogg** [comment]
I think this is already partly possible. Look:

https://code.google.com/p/morphia/source/browse/trunk/morphia/src/test/java/com/google/code/morphia/ext/ExternalMapperExtTest.java

But if you use the BasicDAO class you will have a problem because it remaps the entities.

**Comment by evanchooly** [comment]
With the example shown above and the fix in #713, this should be already possible.
