### ISSUE TITLE
Unnecessary log?

### ISSUE THREAD

**Issue by Eemuli** [mongodb/morphia#680]
Hi!
I bumped into a possibly unnecessary warning log in org.mongodb.morphia.mapping.ReferenceMapper on line 289. Please find a case where it gets triggered unnecessarily:
https://github.com/Eemuli/MorphiaTest

This actually becomes a slight problem because it spams the logging system and shows unnecessary warnings. The reason for the desired entity architecture is that I use a library which contains several classes which I extend and modify slightly to be suitable for my use case. Therefore, I suggest that the log statement is removed or its level is changed to "info".

Could I have opinions on this?
Especially insights on which cases the warning is important to have.

**Comment by evanchooly** [comment]
This should be fixed in the latest master.  Can you confirm for me?

**Comment by Eemuli** [comment]
Yes, it is fixed. Big thanks!

**Comment by evanchooly** [comment]
Excellent.  I'll close this one out then.  Thanks.
