### ISSUE TITLE
Package mapping issue

### ISSUE THREAD

**Issue by rah77az** [mongodb/morphia#683]
On windows machine (under eclipse in Tomcat env) ReflectionUtils.getPackageName return -1 and Morphia initialization throws an IndexOutofBounds exception. 

private static String getPackageName(final String filename) {
      return filename.substring(0, filename.lastIndexOf(File.separator));
}

Even though the windows separator is backslash '\' under windows, file paths in jar file use forward slashes '/', and when supplied to the method an exception is thrown.

108 has no such issue.

Stacktrace:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1954) ~[?:1.8.0_25]
	at org.mongodb.morphia.utils.ReflectionUtils.getPackageName(ReflectionUtils.java:443) ~[morphia-0.109.jar:?]
	at org.mongodb.morphia.utils.ReflectionUtils.getFromJARFile(ReflectionUtils.java:469) ~[morphia-0.109.jar:?]
	at org.mongodb.morphia.utils.ReflectionUtils.getClasses(ReflectionUtils.java:512) ~[morphia-0.109.jar:?]
	at org.mongodb.morphia.utils.ReflectionUtils.getClasses(ReflectionUtils.java:484) ~[morphia-0.109.jar:?]
	at org.mongodb.morphia.Morphia.mapPackage(Morphia.java:108) ~[morphia-0.109.jar:?]

**Comment by evanchooly** [comment]
I don't have a windows box to test this with but here's the patched jar if you can give it a try:  https://www.dropbox.com/s/c7mxfx79ymoqjqy/morphia-0.110-SNAPSHOT.jar?dl=0

**Comment by rah77az** [comment]
Confirming 0.110-SNAPSHOT fixed the issue

**Comment by evanchooly** [comment]
Thanks.  i'll commit that change then.

**Comment by umbreak** [comment]
It crashes for me in the 0.110 too:

            morphia.mapPackage("models");
     

    Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1911)
	at org.mongodb.morphia.utils.ReflectionUtils.getPackageName(ReflectionUtils.java:439)
	at org.mongodb.morphia.utils.ReflectionUtils.getFromJARFile(ReflectionUtils.java:465)
	at org.mongodb.morphia.utils.ReflectionUtils.getClasses(ReflectionUtils.java:508)
	at org.mongodb.morphia.utils.ReflectionUtils.getClasses(ReflectionUtils.java:480)
	at org.mongodb.morphia.Morphia.mapPackage(Morphia.java:108)
	at org.mongodb.morphia.Morphia.mapPackage(Morphia.java:96)

**Comment by evanchooly** [comment]
Can you attach your classpath?  I think I see what the problem is I just need to confirm a few things.

**Comment by umbreak** [comment]
the models package is an external JAR and the rest I'm doing it through Play Framework, which is executed by Netty with a command `activator stage`. What else do you exactly need?

With the version 0.108 it was working.

**Comment by umbreak** [comment]
Here you have the returned from your code in `ReflectionUtils.getClasses(...)` (only until the part `resources.nextElement()
                                           .getFile();`

	/home/me/svn/trunk/web/central-**/target/universal/stage/lib/central-**.central-**-1.0-SNAPSHOT.jar!/models
	/home/me/svn/trunk/web/central-**/target/universal/stage/lib/com.typesafe.play.play_2.11-2.3.8.jar!/models
	/home/me/svn/trunk/web/central-**/target/universal/stage/lib/central.common.models.central-common-models_2.11-1.0-SNAPSHOT.jar!/models

**Comment by umbreak** [comment]
I can confirm also that is something related with that package which does not contain dots. For other packages in my project (for example, `model.type`) works. 

But this `model` package is really common in Play and is exactly were the models are located.

As a workaround I had to define them right now manually `morphia.map(Agent.class, User.class, ...);`
`

**Comment by evanchooly** [comment]
can you attach the output of the property `java.class.path`?  I think I can use that to build an effective test.

**Comment by umbreak** [comment]
Is quite huge. But if it helps you:

    /home/folder/target/universal/stage/lib/central-frontend.central-frontend-1.0-SNAPSHOT.jar:/home/folder/target/universal/stage/lib/com.springsource.javax.media.jai.core-1.1.3.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.twirl-api_2.11-1.0.2.jar:/home/folder/target/universal/stage/lib/org.scala-lang.modules.scala-xml_2.11-1.0.1.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.play_2.11-2.3.8.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.build-link-2.3.8.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.play-exceptions-2.3.8.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.play-iteratees_2.11-2.3.8.jar:/home/folder/target/universal/stage/lib/org.scala-stm.scala-stm_2.11-0.7.jar:/home/folder/target/universal/stage/lib/com.typesafe.config-1.2.1.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.play-json_2.11-2.3.8.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.play-functional_2.11-2.3.8.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.play-datacommons_2.11-2.3.8.jar:/home/folder/target/universal/stage/lib/org.joda.joda-convert-1.6.jar:/home/folder/target/universal/stage/lib/org.scala-lang.scala-reflect-2.11.1.jar:/home/folder/target/universal/stage/lib/org.scala-lang.modules.scala-parser-combinators_2.11-1.0.1.jar:/home/folder/target/universal/stage/lib/io.netty.netty-3.9.3.Final.jar:/home/folder/target/universal/stage/lib/com.typesafe.netty.netty-http-pipelining-1.1.2.jar:/home/folder/target/universal/stage/lib/org.slf4j.jul-to-slf4j-1.7.6.jar:/home/folder/target/universal/stage/lib/org.slf4j.jcl-over-slf4j-1.7.6.jar:/home/folder/target/universal/stage/lib/ch.qos.logback.logback-core-1.1.1.jar:/home/folder/target/universal/stage/lib/ch.qos.logback.logback-classic-1.1.1.jar:/home/folder/target/universal/stage/lib/com.typesafe.akka.akka-actor_2.11-2.3.4.jar:/home/folder/target/universal/stage/lib/com.typesafe.akka.akka-slf4j_2.11-2.3.4.jar:/home/folder/target/universal/stage/lib/commons-codec.commons-codec-1.9.jar:/home/folder/target/universal/stage/lib/xerces.xercesImpl-2.11.0.jar:/home/folder/target/universal/stage/lib/xml-apis.xml-apis-1.4.01.jar:/home/folder/target/universal/stage/lib/javax.transaction.jta-1.1.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.play-java_2.11-2.3.8.jar:/home/folder/target/universal/stage/lib/org.yaml.snakeyaml-1.13.jar:/home/folder/target/universal/stage/lib/org.hibernate.hibernate-validator-5.0.3.Final.jar:/home/folder/target/universal/stage/lib/javax.validation.validation-api-1.1.0.Final.jar:/home/folder/target/universal/stage/lib/com.fasterxml.classmate-1.0.0.jar:/home/folder/target/universal/stage/lib/org.jboss.logging.jboss-logging-3.2.0.Final.jar:/home/folder/target/universal/stage/lib/org.springframework.spring-context-4.0.3.RELEASE.jar:/home/folder/target/universal/stage/lib/org.springframework.spring-core-4.0.3.RELEASE.jar:/home/folder/target/universal/stage/lib/org.springframework.spring-beans-4.0.3.RELEASE.jar:/home/folder/target/universal/stage/lib/org.javassist.javassist-3.19.0-GA.jar:/home/folder/target/universal/stage/lib/org.reflections.reflections-0.9.9-RC1.jar:/home/folder/target/universal/stage/lib/com.google.guava.guava-17.0.jar:/home/folder/target/universal/stage/lib/dom4j.dom4j-1.6.1.jar:/home/folder/target/universal/stage/lib/com.google.code.findbugs.jsr305-2.0.3.jar:/home/folder/target/universal/stage/lib/org.apache.tomcat.tomcat-servlet-api-8.0.5.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.play-cache_2.11-2.3.8.jar:/home/folder/target/universal/stage/lib/net.sf.ehcache.ehcache-core-2.6.8.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.play-java-ws_2.11-2.3.8.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.play-ws_2.11-2.3.8.jar:/home/folder/target/universal/stage/lib/com.ning.async-http-client-1.8.15.jar:/home/folder/target/universal/stage/lib/oauth.signpost.signpost-core-1.2.1.2.jar:/home/folder/target/universal/stage/lib/oauth.signpost.signpost-commonshttp4-1.2.1.2.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.play-java-ebean_2.11-2.3.8.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.play-java-jdbc_2.11-2.3.8.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.play-jdbc_2.11-2.3.8.jar:/home/folder/target/universal/stage/lib/com.jolbox.bonecp-0.8.0.RELEASE.jar:/home/folder/target/universal/stage/lib/com.h2database.h2-1.3.175.jar:/home/folder/target/universal/stage/lib/tyrex.tyrex-1.0.1.jar:/home/folder/target/universal/stage/lib/org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:/home/folder/target/universal/stage/lib/org.avaje.ebeanorm.avaje-ebeanorm-agent-3.2.2.jar:/home/folder/target/universal/stage/lib/org.hibernate.javax.persistence.hibernate-jpa-2.0-api-1.0.1.Final.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.filters-helpers_2.11-2.3.8.jar:/home/folder/target/universal/stage/lib/com.typesafe.akka.akka-camel_2.11-2.3.4.jar:/home/folder/target/universal/stage/lib/org.apache.camel.camel-core-2.10.3.jar:/home/folder/target/universal/stage/lib/org.seleniumhq.selenium.selenium-java-2.42.2.jar:/home/folder/target/universal/stage/lib/org.seleniumhq.selenium.selenium-chrome-driver-2.42.2.jar:/home/folder/target/universal/stage/lib/org.seleniumhq.selenium.selenium-remote-driver-2.42.2.jar:/home/folder/target/universal/stage/lib/cglib.cglib-nodep-2.1_3.jar:/home/folder/target/universal/stage/lib/org.seleniumhq.selenium.selenium-api-2.42.2.jar:/home/folder/target/universal/stage/lib/commons-logging.commons-logging-1.1.3.jar:/home/folder/target/universal/stage/lib/org.apache.commons.commons-exec-1.1.jar:/home/folder/target/universal/stage/lib/net.java.dev.jna.jna-3.4.0.jar:/home/folder/target/universal/stage/lib/net.java.dev.jna.platform-3.4.0.jar:/home/folder/target/universal/stage/lib/org.seleniumhq.selenium.selenium-htmlunit-driver-2.42.2.jar:/home/folder/target/universal/stage/lib/net.sourceforge.htmlunit.htmlunit-2.14.jar:/home/folder/target/universal/stage/lib/xalan.xalan-2.7.1.jar:/home/folder/target/universal/stage/lib/xalan.serializer-2.7.1.jar:/home/folder/target/universal/stage/lib/commons-collections.commons-collections-3.2.1.jar:/home/folder/target/universal/stage/lib/org.apache.commons.commons-lang3-3.2.1.jar:/home/folder/target/universal/stage/lib/org.apache.httpcomponents.httpmime-4.3.2.jar:/home/folder/target/universal/stage/lib/net.sourceforge.htmlunit.htmlunit-core-js-2.14.jar:/home/folder/target/universal/stage/lib/net.sourceforge.nekohtml.nekohtml-1.9.20.jar:/home/folder/target/universal/stage/lib/net.sourceforge.cssparser.cssparser-0.9.13.jar:/home/folder/target/universal/stage/lib/org.w3c.css.sac-1.3.jar:/home/folder/target/universal/stage/lib/commons-io.commons-io-2.4.jar:/home/folder/target/universal/stage/lib/org.eclipse.jetty.jetty-websocket-8.1.14.v20131031.jar:/home/folder/target/universal/stage/lib/org.eclipse.jetty.jetty-util-8.1.14.v20131031.jar:/home/folder/target/universal/stage/lib/org.eclipse.jetty.jetty-io-8.1.14.v20131031.jar:/home/folder/target/universal/stage/lib/org.eclipse.jetty.jetty-http-8.1.14.v20131031.jar:/home/folder/target/universal/stage/lib/org.seleniumhq.selenium.selenium-firefox-driver-2.42.2.jar:/home/folder/target/universal/stage/lib/org.seleniumhq.selenium.selenium-ie-driver-2.42.2.jar:/home/folder/target/universal/stage/lib/org.seleniumhq.selenium.selenium-safari-driver-2.42.2.jar:/home/folder/target/universal/stage/lib/org.webbitserver.webbit-0.4.14.jar:/home/folder/target/universal/stage/lib/org.seleniumhq.selenium.selenium-support-2.42.2.jar:/home/folder/target/universal/stage/lib/com.feth.play-authenticate_2.11-0.6.8.jar:/home/folder/target/universal/stage/lib/org.scala-lang.scala-library-2.11.2.jar:/home/folder/target/universal/stage/lib/com.feth.play-easymail_2.11-0.6.7.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.plugins.play-plugins-mailer_2.11-2.3.1.jar:/home/folder/target/universal/stage/lib/org.apache.commons.commons-email-1.3.3.jar:/home/folder/target/universal/stage/lib/javax.mail.mail-1.4.5.jar:/home/folder/target/universal/stage/lib/javax.activation.activation-1.1.1.jar:/home/folder/target/universal/stage/lib/com.typesafe.play.plugins.play-plugins-util_2.11-2.3.0.jar:/home/folder/target/universal/stage/lib/org.mindrot.jbcrypt-0.3m.jar:/home/folder/target/universal/stage/lib/commons-lang.commons-lang-2.6.jar:/home/folder/target/universal/stage/lib/org.apache.xmlrpc.xmlrpc-client-3.1.3.jar:/home/folder/target/universal/stage/lib/org.apache.xmlrpc.xmlrpc-common-3.1.3.jar:/home/folder/target/universal/stage/lib/org.apache.ws.commons.util.ws-commons-util-1.0.2.jar:/home/folder/target/universal/stage/lib/junit.junit-3.8.1.jar:/home/folder/target/universal/stage/lib/com.sun.jersey.jersey-core-1.17.1.jar:/home/folder/target/universal/stage/lib/central.common.models.central-common-models_2.11-1.0-SNAPSHOT.jar:/home/folder/target/universal/stage/lib/commons-beanutils.commons-beanutils-1.9.2.jar:/home/folder/target/universal/stage/lib/be.objectify.deadbolt-java_2.11-2.3.1.jar:/home/folder/target/universal/stage/lib/be.objectify.deadbolt-core_2.11-2.3.1.jar:/home/folder/target/universal/stage/lib/com.google.api-client.google-api-client-1.19.0.jar:/home/folder/target/universal/stage/lib/com.google.oauth-client.google-oauth-client-1.19.0.jar:/home/folder/target/universal/stage/lib/com.google.http-client.google-http-client-1.19.0.jar:/home/folder/target/universal/stage/lib/com.google.http-client.google-http-client-jackson2-1.19.0.jar:/home/folder/target/universal/stage/lib/com.google.guava.guava-jdk5-13.0.jar:/home/folder/target/universal/stage/lib/com.google.oauth-client.google-oauth-client-jetty-1.19.0.jar:/home/folder/target/universal/stage/lib/com.google.oauth-client.google-oauth-client-java6-1.19.0.jar:/home/folder/target/universal/stage/lib/org.mortbay.jetty.jetty-6.1.26.jar:/home/folder/target/universal/stage/lib/org.mortbay.jetty.jetty-util-6.1.26.jar:/home/folder/target/universal/stage/lib/org.mortbay.jetty.servlet-api-2.5-20081211.jar:/home/folder/target/universal/stage/lib/com.google.apis.google-api-services-youtube-v3-rev112-1.19.0.jar:/home/folder/target/universal/stage/lib/javax.xml.bind.jaxb-api-2.2.11.jar:/home/folder/target/universal/stage/lib/org.apache.httpcomponents.httpclient-4.3.6.jar:/home/folder/target/universal/stage/lib/org.apache.httpcomponents.httpcore-4.3.3.jar:/home/folder/target/universal/stage/lib/com.google.inject.guice-3.0.jar:/home/folder/target/universal/stage/lib/javax.inject.javax.inject-1.jar:/home/folder/target/universal/stage/lib/aopalliance.aopalliance-1.0.jar:/home/folder/target/universal/stage/lib/org.sonatype.sisu.inject.cglib-2.2.1-v20090111.jar:/home/folder/target/universal/stage/lib/asm.asm-3.1.jar:/home/folder/target/universal/stage/lib/com.google.inject.extensions.guice-multibindings-3.0.jar:/home/folder/target/universal/stage/lib/com.google.inject.extensions.guice-assistedinject-3.0.jar:/home/folder/target/universal/stage/lib/com.google.inject.extensions.guice-throwingproviders-3.0.jar:/home/folder/target/universal/stage/lib/org.mongodb.morphia.morphia-0.110.jar:/home/folder/target/universal/stage/lib/org.mongodb.mongo-java-driver-2.13.0.jar:/home/folder/target/universal/stage/lib/org.mongodb.morphia.morphia-util-0.110.jar:/home/folder/target/universal/stage/lib/com.thoughtworks.proxytoys.proxytoys-1.0.jar:/home/folder/target/universal/stage/lib/org.mongodb.morphia.morphia-validation-0.110.jar:/home/folder/target/universal/stage/lib/org.mongodb.morphia.morphia-logging-slf4j-0.110.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-redshift-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-core-1.9.10.jar:/home/folder/target/universal/stage/lib/joda-time.joda-time-2.7.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-route53-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-cloudtrail-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-ses-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-storagegateway-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-glacier-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-sqs-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-sns-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-s3-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-kms-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-kinesis-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-sts-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-cloudsearch-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-opsworks-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-cloudformation-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-importexport-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-emr-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-elastictranscoder-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-lambda-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-directconnect-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-elasticbeanstalk-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-swf-libraries-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-simpleworkflow-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-rds-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-codedeploy-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-elasticache-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-cloudwatchmetrics-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-cloudwatch-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-dynamodb-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-elasticloadbalancing-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-cloudfront-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-simpledb-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-iam-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-cognitosync-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-logs-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-config-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-support-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-ec2-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-cognitoidentity-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-datapipeline-1.9.10.jar:/home/folder/target/universal/stage/lib/com.amazonaws.aws-java-sdk-autoscaling-1.9.10.jar:/home/folder/target/universal/stage/lib/commons-net.commons-net-3.3.jar:/home/folder/target/universal/stage/lib/log4j.log4j-1.2.17.jar:/home/folder/target/universal/stage/lib/com.neovisionaries.nv-i18n-1.12.jar:/home/folder/target/universal/stage/lib/com.fasterxml.jackson.core.jackson-annotations-2.4.1.jar:/home/folder/target/universal/stage/lib/com.fasterxml.jackson.core.jackson-core-2.4.1.jar:/home/folder/target/universal/stage/lib/com.fasterxml.jackson.core.jackson-databind-2.4.1.jar:/home/folder/target/universal/stage/lib/log4j.apache-log4j-extras-1.1.jar:/home/folder/target/universal/stage/lib/org.imgscalr.imgscalr-lib-4.2.jar:/home/folder/target/universal/stage/lib/org.apache.sanselan.sanselan-0.97-incubator.jar:/home/folder/target/universal/stage/lib/commons-cli.commons-cli-1.1.jar:/home/folder/target/universal/stage/lib/com.sun.jersey.jersey-client-1.17.1.jar:/home/folder/target/universal/stage/lib/com.sun.jersey.contribs.jersey-multipart-1.17.1.jar:/home/folder/target/universal/stage/lib/org.jvnet.mimepull-1.6.jar:/home/folder/target/universal/stage/lib/com.sun.jersey.contribs.jersey-oauth.oauth-client-1.17.1.jar:/home/folder/target/universal/stage/lib/com.sun.jersey.contribs.jersey-oauth.oauth-signature-1.17.1.jar:/home/folder/target/universal/stage/lib/com.github.rholder.guava-retrying-1.0.6.jar:/home/folder/target/universal/stage/lib/org.jsoup.jsoup-1.7.3.jar:/home/folder/target/universal/stage/lib/com.sun.jersey.contribs.jersey-apache-client-1.9-ea04.jar:/home/folder/target/universal/stage/lib/commons-httpclient.commons-httpclient-3.1.jar:/home/folder/target/universal/stage/lib/com.fasterxml.jackson.datatype.jackson-datatype-json-org-2.3.3.jar:/home/folder/target/universal/stage/lib/org.json.json-20090211.jar:/home/folder/target/universal/stage/lib/org.im4java.im4java-1.4.0.jar:/home/folder/target/universal/stage/lib/com.drewnoakes.metadata-extractor-2.6.2.jar:/home/folder/target/universal/stage/lib/com.adobe.xmp.xmpcore-5.1.2.jar:/home/folder/target/universal/stage/lib/com.jcraft.jsch-0.1.51.jar:/home/folder/target/universal/stage/lib/mysql.mysql-connector-java-5.1.18.jar:/home/folder/target/universal/stage/lib/org.julienrf.play-jsmessages_2.11-1.6.2.jar:/home/folder/target/universal/stage/lib/com.google.zxing.javase-3.1.0.jar:/home/folder/target/universal/stage/lib/com.google.zxing.core-3.1.0.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.fop-1.0.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.xmlgraphics-commons-1.4.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-svg-dom-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-anim-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-awt-util-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-util-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-dom-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-css-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-ext-1.7.jar:/home/folder/target/universal/stage/lib/xml-apis.xml-apis-ext-1.3.04.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-xml-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-parser-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-bridge-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-gvt-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-script-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-js-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-transcoder-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-svggen-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.xmlgraphics.batik-extension-1.7.jar:/home/folder/target/universal/stage/lib/org.apache.avalon.framework.avalon-framework-api-4.3.1.jar:/home/folder/target/universal/stage/lib/org.apache.avalon.framework.avalon-framework-impl-4.3.1.jar:/home/folder/target/universal/stage/lib/org.apache.velocity.velocity-1.7.jar:/home/folder/target/universal/stage/lib/net.sf.uadetector.uadetector-resources-2014.04.jar:/home/folder/target/universal/stage/lib/net.sf.uadetector.uadetector-core-0.9.16.jar:/home/folder/target/universal/stage/lib/net.sf.qualitycheck.quality-check-1.3.jar:/home/folder/target/universal/stage/lib/javax.annotation.jsr250-api-1.0.jar:/home/folder/target/universal/stage/lib/org.slf4j.slf4j-api-1.7.7.jar:/home/folder/target/universal/stage/lib/com.mohiva.play-html-compressor_2.11-0.3.1.jar:/home/folder/target/universal/stage/lib/com.googlecode.htmlcompressor.htmlcompressor-1.5.2.jar:/home/folder/target/universal/stage/lib/rhino.js-1.7R2.jar:/home/folder/target/universal/stage/lib/central-frontend.central-frontend-1.0-SNAPSHOT-assets.jar

**Comment by umbreak** [comment]
Can you, please, reopen this issue (since this is not solved).

Thanks and best regards!

**Comment by evanchooly** [comment]
@umbreak can you try the new snapshot [build](https://oss.sonatype.org/content/repositories/snapshots/org/mongodb/morphia/morphia/0.111-SNAPSHOT/morphia-0.111-20150330.143940-18.jar)?  I couldn't quite reproduce your bug though there's a definitely a bug there can be fixed regardless.  This jar *should* fix it but I'd love to get validation first.  If this does, then I'll cut the 0.111 release.

**Comment by umbreak** [comment]
I can't test that before next week.

**Comment by evanchooly** [comment]
OK.  I've fixed the obvious breakage so I'm going to mark this as fixed so I can push a release.  If you hit another issue around this, file another issue and we'll take it from there.
