### ISSUE TITLE
Allow for function calls to set field values

### ISSUE THREAD

**Issue by nosachamos** [mongodb/morphia#684]
The issue and use case is described here:
http://stackoverflow.com/questions/27662561/mongodb-how-to-make-morphia-set-the-value-of-a-field-as-the-value-returned-by

Basically it would be AWESOME to allow an entity to set a field to some special Morphia object that would indicate the field is to be sent as indicated to MongoDB, without any transformations. For example:

```java
@Entity
public class User {

    @Id
    private Long id;

    private Long seqId = new FunctionCallback("getNextSequence", "userid");;

    private String name;

    ...
}
```

In this case, upon invoking `save` on this entity, the `FunctionCall` object would be translated into a function call whose value is then set to the field by MongoDB. It would be the user responsibility to  make sure the function exists and admits the given parameters. In this case the insert would become:

```javascript
db.users.insert(
   {
     seqId: getNextSequence("userid"),
     name: "Sarah C."
   }
}
```

This allows for the extremely common case of implementing a dynamic value to a field without the need for a server round trip to get the value first.

Please let me know what you guys think.

**Comment by evanchooly** [comment]
You could actually implement this as an EntityInterceptor.  You'd have
fewer weird lifecycle issues that way.

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "10gen.com", *"*antwerkz.com*"* *]*,
  location : *"*New York, NY*"* *}*

**Comment by evanchooly** [comment]
`@PrePersist` and `@PreSave` allow for this, too.
