### ISSUE TITLE
[Feature Request] Static Meta Model Generator

### ISSUE THREAD

**Issue by ccaspanello** [mongodb/morphia#687]
One of the things I would like to see integrated with the Morphia package is an easy way to generate a type of "static meta model" similar to JPA.

**JPA Static Meta Model:**
    @Static Metamodel(Pet.class)
    public class Pet_ {
      
      public static volatile SingularAttribute<Pet, Long> id;
      public static volatile SingularAttribute<Pet, String> name;
      public static volatile SingularAttribute<Pet, String> color;
      public static volatile SetAttribute<Pet, Owner> owners;
    }
Note:  These classes are auto generaged by Maven via the auto generated by a Maven dependency, org.eclipse.persistence.jpa.modelgen.processor dependency.

Instead of hard coding strings you can use this in the criteria API as such:

**JPA Usage of Static Meta Model:**
    CriteriaQuery<Pet> cq = cb.createQuery(Pet.class);
    Root<Pet> pet = cq.from(Pet.class);
    cq.where(pet.get(Pet_.color).in("brown", "black"));

In the Morphia world we can do something very similar.  I propose we follow the same type of meta model class and we can use it similar to the following.

**Proposed Morphia Usage**
    ds.find(Pet.class).field(Pet_.name).equal(userInputVariable).get();

Implementing a static meta model like this makes the code easier to refactor.  Please feel re to reach out to me if you have any questions or would like help with this.

**Comment by ccaspanello** [comment]
I was going to put a label on this for "Enhancement"; but was unable to do so.  Feel free to add the label and change the subject as you see fit.

**Comment by evanchooly** [comment]
You might check out my pet project critter and see if that gets you closer
to what you need:  https://github.com/evanchooly/critter

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "10gen.com", *"*antwerkz.com*"* *]*,
  location : *"*New York, NY*"* *}*

**Comment by ccaspanello** [comment]
@evanchooly - Thank you very much for your reply.  At first glimpse it looks very promising (nice documentation).  I'll check it out in more detail right now and give you some feedback.

**Comment by evanchooly** [comment]
@ccaspanello does critter meet your needs?  I'm going to close this here.
