### ISSUE TITLE
Mapping uninitialized entities

### ISSUE THREAD

**Issue by eemelipa** [mongodb/morphia#688]
If custom annotations ("interesting annotations") are introduced in a static code block in the corresponding entity, it is possible that mapper doesn't recognize these. 

At the beginning of a program Morphia can be explicitly made to map some packages, e.g., morphia.mapPackage(name), and the problem is that if some interesting annotations have been stated in static blocks inside the respective entities (MappedField.addInterestingAnnotation(MyAnnotation.class)) those static blocks don't get executed, thus, morphia doesn't recognize these annotations. Since mapping is done only once these annotations will remain unnoticed by morphia the rest of the execution. As a resolution the entity classes should be initialized before mapping them. Morphia should do this automatically in order to avoid unnecessary code bloat in the actual program, and frustration of making sure every entity is initialized before using it with morphia.

**Comment by evanchooly** [comment]
The mapper is currently being replaced in 2.x.  There will be a new mechanism for this kind of thing so this shouldn't be a problem.
