### ISSUE TITLE
Erroneous warning "DatastoreImpl: DBCollection already exists is capped already"

### ISSUE THREAD

**Issue by jbyler** [mongodb/morphia#694]
When Morphia manages an entity stored in a capped collection, the first time the application starts, Morphia creates the capped collection.  On the second and all subsequent starts of the application, Morphia logs a warning like this:

```
WARN  [2015-01-12 20:57:35,024] org.mongodb.morphia.DatastoreImpl: DBCollection already exists is capped already; doing nothing. { "serverUsed" : "localhost:27017" , ...}
```

Looking at the logic in [DataStoreImpl](https://github.com/mongodb/morphia/blob/f765a7095cbcd1bf46a94f7047db88b17d2f60ce/morphia/src/main/java/org/mongodb/morphia/DatastoreImpl.java#L438), it's clear that this log message is printed every time `ensureCaps()` is called.  This log message should probably be DEBUG level or removed entirely.

**Comment by jbyler** [comment]
Great, thanks @evanchooly!  Much appreciated.

**Comment by evanchooly** [comment]
np.  thanks for the patch.

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "10gen.com", *"*antwerkz.com*"* *]*,
  location : *"*New York, NY*"* *}*
