### ISSUE TITLE
mapPackageFromClass fails for external jar (Maven dependency)

### ISSUE THREAD

**Issue by zmirc** [mongodb/morphia#697]
Morphia 0.109
JDK 1.8_25 x64 on Win 8.1 x64
TokuMX 2.0.0 - which uses Mongo 2.4.10
Stacktrace:
`java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1954)
	at org.mongodb.morphia.utils.ReflectionUtils.getPackageName(ReflectionUtils.java:443)
	at org.mongodb.morphia.utils.ReflectionUtils.getFromJARFile(ReflectionUtils.java:469)
	at org.mongodb.morphia.utils.ReflectionUtils.getClasses(ReflectionUtils.java:512)
	at org.mongodb.morphia.utils.ReflectionUtils.getClasses(ReflectionUtils.java:484)
	at org.mongodb.morphia.Morphia.mapPackage(Morphia.java:108)
	at org.mongodb.morphia.Morphia.mapPackageFromClass(Morphia.java:86)
	at zmirc.morphia109.bug.war.Servlet1.doGet(Servlet1.java:18)`

Links to repositories used to reproduce this error:
https://github.com/zmirc/morphia109-bug-war
https://github.com/zmirc/morphia109-bug-shared

This error appeared since 0.109. With 0.108 there is no issue.
Explanation:
- the error appears when a project includes another project as a jar dependency (through Maven).
- the 2 links I gave above represent the main demo app ("war") and a project that contains shared classes ("shared"). We use this technique because we share some logic and Mongo entities between more projects.
- the problem appears when the main project wants to mapPackageFromClass(), giving as parameter a class from the shared project. This worked ok with version 108, but I saw that version 109 had significant changes in `ReflectionUtils`, so I guess the error lies there.
- if I copy the entity classes from the shared project into the war (main project), then they can be mapped ok. The issue appears only when I want to map classes which belong to a different project/jar.

How to reproduce in Netbeans:
- clone both repositories
- right click on "shared", then select "clean and build" (this is necessary because it builds the project and adds it into the local Maven repository of Netbeans, so then it can be used by the "war" project as a dependency (see the pom.xml files of both projects)).
- install a servlet container, where the "war" project can be run
- run the "war" project and open the URL of zmirc.morphia109.bug.war.Servlet1, which should normally be (depending on which root path you set for the project) http://localhost:8082/morphia109-bug-war/servlet1

In case more info is necessary, I am willing to help.
Thank you in advance. I really look forward to having this bug fixed, because I have to stick to 0.108 until then. Thanks. :)

**Comment by evanchooly** [comment]
can you attach the error/stacktrace for me?  Thanks.

**Comment by zmirc** [comment]
@evanchooly Unless you try to say something else, all the stacktrace is contained in my post. See lines 5-13 from my post. There's nothing else. You can also try it yourself by using the sample I provided.

**Comment by evanchooly** [comment]
duh.  i'm stupid.  nevermind.  I'll see what I can do on this one.  Thanks.

**Comment by evanchooly** [comment]
I think this is related to https://github.com/mongodb/morphia/issues/683.  Can you try a SNAPSHOT build and see if it works now.  There's a jar attached to that issue you can try.

**Comment by zmirc** [comment]
@evanchooly No worries. Thank you as well. I can try, but what should write in the pom.xml to get the snapshot version? I looked for the snapshot details in the wiki, but I didn't see it. Can you please tell me?
That's what I'm currently using:
`<dependency> 
  <groupId>org.mongodb.morphia</groupId> 
  <artifactId>morphia</artifactId>
  <version>0.109</version>
</dependency>`

**Comment by evanchooly** [comment]
change the version to 0.110-SNAPSHOT and put the jar in
~/.m2/repository/org/mongodb/morphia/morphia/0.110-SNAPSHOT

That should do it for you.  If you've set up your pom to pull from the
snapshots repository simply changing the version number should suffice.

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "10gen.com", *"*antwerkz.com*"* *]*,
  location : *"*New York, NY*"* *}*

**Comment by zmirc** [comment]
Where do I download the jar from them? I just tried to build it from source (without tests), but it fails. Can you just send me the jar directly, because I guess you can make it faster, if not you already have it?

**Comment by evanchooly** [comment]
the jar is linked in the comments on that issue...

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "10gen.com", *"*antwerkz.com*"* *]*,
  location : *"*New York, NY*"* *}*

**Comment by zmirc** [comment]
Thanks. I found it.
I've just tried with my sample and the real project and it seems to work. 
Great! Thank you.

**Comment by evanchooly** [comment]
Fantastic.  Thanks for the update.
