### ISSUE TITLE
Nesting embedded is creating nested indices I don't want

### ISSUE THREAD

**Issue by petropolis** [mongodb/morphia#706]
I have a two classes (I'll skip the id field since it isn't relevant):

@Entity
class Room {
   @Indexed
   String roomName;
   @Embedded
   Story latestStory;
}

@Entity
class Story {
   @Indexed
    String message;
}

When I do an ensureIndexes() it is creating the index "latestStory.message" in my Rooms collection. I don't want this. This is useless in my Rooms collection (I only want the roomName index). How do I stop it from doing this?

**Comment by cteyton** [comment]
Hi, 
If it can help you, I think that you misuse the @Embedded annotation, since here you want to embed an entity (Story). 
I'm not sure this is consistent, perharps you should :
* replace the @Entity on Story with @Embedded ?
* replace the @Embedded on lastestStory with @Reference ?

I may be incorrect, so I let someone more expert than me give his opinion :)

**Comment by evanchooly** [comment]
My first thought was definitely along those lines.  I can see why someone
might want to do it this way, though.  I'm just not sure morphia was
intended to work with this use case.

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "10gen.com", *"*antwerkz.com*"* *]*,
  location : *"*New York, NY*"* *}*

**Comment by petropolis** [comment]
That is NOT what I want. Using @Reference uses a separate object. I'm not using a separate object. I'm using one object embedded in the other and stored in Mongo as a single object. Since it is stored as a single object, I don't need the spurious indices (and it will actually slow Mongo down since it will attempt to populate these indices on each insertion).

**Comment by petropolis** [comment]
I'll illustrate how this is broken in case the Morphia devs want to fix it. Suppose I have two collections X and Y like

@Indexes({@Index("a,b")})
class X {
  String a;
  @Indexed
  String b;
}

@Indexes({@Index("c,d")})
class Y {
  String c;
  @Indexed
  String d;
}

So collection X is indexed on the compound index (a,b) and the field "b" and the collection Y is similar. If I embed Y in X like this:

@Indexes({@Index("a,b")})
class X {
  String a;
  @Indexed
  String b;
  Y y;
}

then Morphia creates the indices (c,d) and "y.d" on collection X! But X will *never* have a (c,d) field and I don't need the index on "y.d" since I never search on it. Because Mongo doesn't know I'll never stick a "c" or a "d" field in X, it has to check on each insertion if these fields are there. This is broken and I can't ever see a scenario when you'd want the compound field (c,d) put on X or the "y.d" field either (if I wanted this field indexed, I'd declare it).

**Comment by evanchooly** [comment]
This is expected and long-standing behavior.  Morphia has always looked at embedded types to create any indexes defined there.  If you don't want the embedded index created, you'll have to create them manually rather than relying on Morphia to create them for you.  I'll leave this open for now in case a workable solution presents itself but essentially this is how Morphia is supposed to work.

**Comment by drdamour** [comment]
I too ran into this.  I have a class that i use both as the main entity in one collection, and as an embedded entity in another entity that is the main entity of another collection.  I'd like not to have the embedded indexes forced on me.  A param to ensureIndexes would get me there.

**Comment by petropolis** [comment]
@drdamour It sounds like they aren't going to fix it even though it is broken. There is no way to prevent these indices from being created and taking the performance hit. I gave up.

**Comment by drdamour** [comment]
yeah i ended up not reusing classes...even though they are nearly the same.  that actually freed me up to optimize my model a bit...which is probably what they are saying to do when they say "not the way morphia was intended"  It's more DDD / NoSQL approach for sure to not DRY your model so much.
