### ISSUE TITLE
Constructing a Key<?> object

### ISSUE THREAD

**Issue by mustafaakin** [mongodb/morphia#708]
How do we construct the Key<?> object by just using an ObjectID? Cannot find anywhere. Neither Key has any public static method , or a Key<?> object. I want to store some fields as key<User> but instead I store them as ObjectId, which kinda defeats the purpose.

**Comment by evanchooly** [comment]
Please post this question and a code sample to the [mailing list](https://groups.google.com/forum/#!forum/morphia) and we can talk it through.  The issue tracker isn't the best place for discussions like this.
