### ISSUE TITLE
elementMatch with queries different to equal

### ISSUE THREAD

**Issue by umbreak** [mongodb/morphia#709]
I know morphia offer the option `hasThisElement`, which is like to use elementMatch in mongo shell. That would work when the comparisson logic is `equal`. But how I can do when I want to do something like??

    db.schools.find( { zipcode: "63109" },
                 { students: { $elemMatch: { school: 102, age: { $gt: 10} } } } )
There is one `equal` logic and one `greaterThan` inside the elementMatch

**Comment by evanchooly** [comment]
You could build a DBObject reflecting that structure.  It's not very morphia-ish, though.  Perhaps an area for API improvement at some point.  `hasThisElement` takes `Object` so you could pass that in.  Please post to the [mailing list](https://groups.google.com/forum/#!forum/morphia) if you have questions about that part.
