### ISSUE TITLE
Lazy Loading is not actually Lazy Loading?

### ISSUE THREAD

**Issue by AddoSolutions** [mongodb/morphia#712]
Hello, I am trying to figure out what I am doign wrong here.  I am debugging my application for performance issues, and am noticing that even when I add a `@Reference(lazy = true)`, the application still does a query for the reference, but instead of loading the whole reference, it just loads `_id` and `className`.  I am getting this conclusion on what I am seeing here: `org.mongodb.morphia.mapping.ReferenceMapper` on line 220.

List/Single Reference Split Point: https://github.com/mongodb/morphia/blob/bb3ed1e2c3506bff3dc2a927699b48d9d912f953/morphia/src/main/java/org/mongodb/morphia/mapping/ReferenceMapper.java#L220

Single Reference: https://github.com/mongodb/morphia/blob/bb3ed1e2c3506bff3dc2a927699b48d9d912f953/morphia/src/main/java/org/mongodb/morphia/mapping/ReferenceMapper.java#L295

List: https://github.com/mongodb/morphia/blob/bb3ed1e2c3506bff3dc2a927699b48d9d912f953/morphia/src/main/java/org/mongodb/morphia/DatastoreImpl.java#L599

If this in fact true, then this library does not truly support lazy loading, because a query is being made regardless of whether or not lazy loading is configured.  This is a massive issue especially when using in a clustered environment.

Thanks

**Comment by AddoSolutions** [comment]
From my digging through the code, it looks like the reason that this occurs is so that we can check if the reference exists, but shouldn't that be caught upon lazy loading?

**Comment by evanchooly** [comment]
This kind of question belongs on the [mailing list](https://groups.google.com/forum/#!forum/morphia).  Please post your question there and any output that leads you to believe there's a problem and we can discuss it.

**Comment by plaa** [comment]
For the benefit of later readers, this issue resulted in #714, which fixes the loading.

Discussion thread is here:  https://groups.google.com/forum/#!topic/morphia/OEQtZLII8tI
