### ISSUE TITLE
The BasicDAO does not consider the information added in the MappedClass Mapper earlier

### ISSUE THREAD

**Issue by fredericogg** [mongodb/morphia#713]
I'm following this code to use Morphia without annotations, so my code is as follows

Mongo Mongo; // I create the Mongo
Morphia morphia = new Morphia ();

/ * 
In this place I call a method that maps the class by adding the annotation @Entity and @Id and in my Mapper Morphia
* /

Datastore ds = new DatastoreImpl (morphia, mongo, "db");

/ *
When creating the DAO get an exception "Noid complained about com.hipersistence.resources.People:. In the field is annotated with ..."
* /
BasicDAO <People, String> dao = new BasicDAO <People, String> (People.class, ds);

// The exeption is because when creating the BasicDAO it executes the following code:

protected void initType (Class end <T> type) {
       entityClazz = type;
       ds.getMapper () addMappedClass (type).;
}

/ * 
And the method of addMappedClass Mapper class that was called, creates a new MappedClass internally and does not consider the mappings previously made
* /
public MappedClass addMappedClass (final Class c) {
       return addMappedClass (new MappedClass (c, this), true);
}

**Comment by evanchooly** [comment]
(note to self) the fix:  add a check in addMappedClass():
      if(ds.getMapper().getMappedClass(type) == null)
