### ISSUE TITLE
Exception when trying to query using enum with methods

### ISSUE THREAD

**Issue by eyalgo** [mongodb/morphia#715]
Hi,
We have an enum, which has an abstract method and each specific type overrides it.

    public enum MyEnum {
      A {
       @Override
       public void foo() {
       }
      },B {
       @Override
       public void foo() {
       }
     };
     public abstract void foo();
    }

And class tha holds it:

     public class EnumHolder {
	     private MyEnum myEnum;
	     public EnumHolder() {
	     }
	     public MyEnum getMyEnum() {
		        return myEnum;
	     }
	      public void setMyEnum(MyEnum myEnum) {
		       this.myEnum = myEnum;
	     }
      }

We have requests, which we get a String, do a valueOf for the enum and the pass it to a Query:

     public class MyDao extends AbstractDaoImpl<EnumHolder> {
       ...
        public void foo(String theEnum) {
            Query<EnumHolder> query = createQuery();
            MyEnum myEnum = MyEnum.valueOf(theEnum); // we do not fail here...
            query.criteria("myEnum").equal(myEnum); // this is where we fail
            // more additions to the query
        }
      }

We get an exception saying the mapper does not recognize MyEnum$1 (or $2).
The enums have the $ sign because they implement method.

Sample error message from our real code (eliminated package prefix):

**org.mongodb.morphia.mapping.Mapper : The type(s) for the query/update may be inconsistent; using an instance of type '....OperatingSystem$2' for the field '....EnrichedData.os' which is declared as '....OperatingSystem'**
(EnrichedData holds OperatingSystem enum with *os* name)

Is there a way to handle that?
Currently we removed the method.

We use Morphia 0.107

**Comment by evanchooly** [comment]
We have [tests](https://github.com/mongodb/morphia/blob/master/morphia/src/test/java/org/mongodb/morphia/mapping/EnumMappingTest.java#L20-20) that use enums successfully.  Can you post a full test case to the [mailing list](https://groups.google.com/forum/#!forum/morphia) and we can discuss it there?

**Comment by eyalgo** [comment]
Thanks.
You are correct.
I created a small app https://github.com/eyalgo/MorphiaEnumExample

In our project, we use version 0.107, which in the example will give a warning message:
_WARNING: The type(s) for the query/update may be inconsistent; using an instance of type 'org.eyalgo.morphia.MyEnum$1' for the field 'org.eyalgo.morphia.EnumHolder.myEnum' which is declared as 'org.eyalgo.morphia.MyEnum'_

Using latest version (0.110) eliminates this message.
