### ISSUE TITLE
0.111 release plan

### ISSUE THREAD

**Issue by pulse00** [mongodb/morphia#716]
Any release date planned for `0.111` ? Currently `0.109` seems to have [package naming issues](https://github.com/mongodb/morphia/issues/683) on windows and `0.110` seems to have a severe regression that appears to be fixed in `0.111-SNAPSHOT` https://twitter.com/evanchooly/status/564908044577173504

**Comment by evanchooly** [comment]
I don't think there was a regression.  0.110 requires 2.13.0 which has a
changed API from 2.12.x.  0.111 will hopefully be out soon.  I'm just
whittling away at the open issues.  You should definitely give 0.110 a try,
though.  You should be fine.

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "10gen.com", *"*antwerkz.com*"* *]*,
  location : *"*New York, NY*"* *}*

**Comment by evanchooly** [comment]
Further discussion should happen on the [mailing list](https://groups.google.com/forum/#!forum/morphia).
