### ISSUE TITLE
query for not empty arrays

### ISSUE THREAD

**Issue by umbreak** [mongodb/morphia#720]
There is a way to query for non empty arrays? The query in MongoDB would be simple (in this case an array of pictures):

    db.ME.find({pictures: {$gt: []}})

**Comment by umbreak** [comment]
Well, it looks like this works:

    .field("pictures").greaterThan(new ArrayList<>())

**Comment by darbie** [comment]
information for other people that look at this: for this to work, you must have set morphia to store empty  arrays (rather than using null).  I used a line like this:
morphia.getMapper().getOptions().setStoreEmpties(true);
