### ISSUE TITLE
Is morphia support mongo3.0?

### ISSUE THREAD

**Issue by zhaozhiming** [mongodb/morphia#723]
HI ALL,
    I want to use morphia to parse java object to Document(new class in mongo java driver 3.0), or parse Document to java object, how to do it? 

I know morphia can to/from use DBObject，but how could do with Document? thanks.

```java
DBObject toDBObject(Object entity) 
T fromDBObject(Class<T> entityClass, DBObject dbObject)
```

**Comment by evanchooly** [comment]
Morphia works with the 3.0 driver but not the new APIs (Document, MongoCollection, etc.).  If you'd like to discuss this further, please use the [mailing list](https://groups.google.com/forum/#!forum/morphia).
