### ISSUE TITLE
Data type disparity between Query.countAll(), Query.offset(int)

### ISSUE THREAD

**Issue by ineedteepee** [mongodb/morphia#726]
There is a data type disparity in com.google.code.morphia.query.Query class.

long countAll()
offset(int)
limit(int)

Since the countAll() supports counting more than Integer.MAX_VALUE results, the offset(...) and limit(...) methods should respectively allow skipping and limiting to more than Integer.MAX_VALUE results.

**Comment by evanchooly** [comment]
While aesthetically, I also dislike the asymmetry, these types match what the java driver uses and what the server expects.  Changing the types wouldn't fix anything and would, in fact, introduce (edge case) bugs.
