### ISSUE TITLE
Query.order(String) overwrites values set in earlier calls

### ISSUE THREAD

**Issue by ineedteepee** [mongodb/morphia#730]
The implementation of Query.order(String) overwrites the values set in previous calls to order(String) (an undocumented feature). The following statement should have expected results:

query.order("name").order("-time");

**Comment by ineedteepee** [comment]
BTW, the fix is super trivial and I can do it myself but the project doesn't even compile.

> Could not find method jcenter() for arguments [] on root project 'buildSrc'.

If there are some magic hoops I need to jump through, please document them in CONTRIBUTING.md.

**Comment by evanchooly** [comment]
This method is working as designed and documented.  To get that sort order you'd call `query.order("name, -time");`

As for building, if you use the included `gradlew` script it should build fine.  It's building on both jenkins and travis, e.g., with no problems.

**Comment by ineedteepee** [comment]
Ok, thanks. I had an old gradle installed from Ubuntu repo which caused the problem.
