### ISSUE TITLE
Generic TypeVariable not supported when saving a List<Generic>

### ISSUE THREAD

**Issue by Faliorn** [mongodb/morphia#737]
Hi again. I filed an issue before but it was fixed using Morphia 0.110. However, I still have a problem.

I'm using an abstract class defined this way:

```java
public abstract class FatherEntity<MyInfo extends InfoEntity<?>, MyEmbedded extends FatherEmbedded>
```

The father class has a list of "MyEmbedded":

```java
@Embedded
private List<MyEmbedded> embeddedItems;
```

Then, I have an entity which inherits FatherEntity:

```java
@Entity(value = ChildEntity.TABLE_NAME)
@ClassName(ChildEntity.class)
public class ChildEntity extends
        FatherEntity<ChildInfoEntity, ChildEmbedded> {
```

Last, I have a DAO class to access the child entity:

```java
protected ChildEntityDAO(Datastore ds) throws Exception {
    super(ds);
}
```

Now, when I try to save an entity of ChildEntity, I get this error:

```
Caused by: java.lang.RuntimeException: Generic TypeVariable not supported!
	at org.mongodb.morphia.mapping.MappedField.toClass(MappedField.java:420)
```

I've tried changing the list to:

```java
private List<? extends FatherEmbedded> actividades;
```

I get this "funny" error: 

```
Caused by: org.mongodb.morphia.mapping.MappingException: 
Unknown type... pretty bad... call for help, wave your hands... yeah!
at org.mongodb.morphia.utils.ReflectionUtils.getParameterizedType(ReflectionUtils.java:273)
```

Am I doing something wrong? Can I achieve this in some other way? If so, please let me know.

Info:

Morphia 0.110
MongoDB 2.6.0
Java JDK 1.8.0_25
Best regards and thank you very much!!

**Comment by evanchooly** [comment]
Can you attach your entity/embedded classes?  I'm not sure I can recreate your issue with just these details.

**Comment by Faliorn** [comment]
I'll try to make a small example asap. Thanks!

**Comment by Faliorn** [comment]
Here you have a link:

https://dl.dropboxusercontent.com/u/11873732/morphiaexample.rar

I've tried to keep the example as simple as possible. In FatherEntity you have both examples.

Thanks!

**Comment by evanchooly** [comment]
good news.  i've tracked it down and have it patched.  snapshot builds will be available as soon as jenkins is done churning through everything if you want to give it a try locally and confirm the fix.

**Comment by Faliorn** [comment]
Thanks man! You people at morphia rock! :+1:

**Comment by evanchooly** [comment]
happy to help.  :)

**Comment by Faliorn** [comment]
Hi

I've upgraded to morphia 0.111 but the bug seems to still be there when using this in FatherEntity:

private List<MyEmbedded> embeddedList;

This sample code:

```java
ChildEntity child = new ChildEntity();
List<ChildEmbedded> embeddedList = new ArrayList<ChildEmbedded>();
ChildEmbedded embeddedItem = new ChildEmbedded();
embeddedList.add(embeddedItem);
child.setEmbeddedList(embeddedList);

Datastore ds = Conexion.getInstance().obtenerDatastore();
ChildDAO dao = new ChildDAO(ds);
dao.save(child);
```

Would end up with:

```
org.mongodb.morphia.mapping.MappingException: Error mapping field:com.morphiaexample.FatherEntity.embeddedList
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:553)

Caused by: java.lang.RuntimeException: Generic TypeVariable not supported!
	at org.mongodb.morphia.mapping.MappedField.toClass(MappedField.java:419)
```

Hope you can fix it. If you need any further informations, don't hesitate to get in touch.

Best regards!
