### ISSUE TITLE
invalid hexadecimal representation of an ObjectId: [550d9c995f1b860ed9e6134fa]

### ISSUE THREAD

**Issue by Nomane** [mongodb/morphia#741]
Hello,

I use latest version of Morpha (0.110) with MongoDB Java driver release 3.0.0 and MongoDB 3.0 (WiredTiger storage engine).

When I call function:

 public T get(final K id) {
        return ds.get(entityClazz, id);
    }

from BaseDAO I have this error message:

invalid hexadecimal representation of an ObjectId: [550d9c995f1b860ed9e6134fa]

This code was OK with previous version of Morphia and MongoDB (version 2.4).

Can someone help me ?

Thanks,

Neo

**Comment by evanchooly** [comment]
If you post your test case to the [mailing list](https://groups.google.com/forum/#!forum/morphia) we can discuss it there.  Thanks.

**Comment by umbreak** [comment]
Is due to an empty string in the construction of an ObjectId: `new ObjectId("")`

**Comment by Elrhino** [comment]
I'm having the same problem using:
```
    public UserDto getUser(String userId) {
        ObjectId id = new ObjectId(userId); <-- THROW EXCEPTION
...
```
 where `userId` is a hex String coming from the database.

Here's the error: `invalid hexadecimal representation of an ObjectId: ["<validHexID>"]`

**Comment by Nomane** [comment]
Hi Elrhino,

This error is probably due of your userId format, it's not well formatted (null value or alterated regarding your user document id).

Also test your value, check if it is not null and be sure that input userId is equals to to your field "_id" in your user collection.
