### ISSUE TITLE
Version field not updated when using "Datastore.update(...)" & "BulkWriteOperation"

### ISSUE THREAD

**Issue by fgouguenheim** [mongodb/morphia#743]
When I update a mongo document using "Datastore.update(...)",
or when I insert or update one or many mongo documents using "BulkWriteOperation",
version field is not updated (incremented).

It looks like a bug as "Datastore.insert(...)" & "Datastore.merge(...)" does increment this version field.

Furthermore (maybe a consequence of the first issue), when I make an upsert on an embeded object (having @Embeded annotation instead of @Entity) and the parent object (i.e. the document) does not exists, the parent object is created but does not have the version field.

**Comment by evanchooly** [comment]
Can you attach a test case reproducing the issue?

**Comment by fgouguenheim** [comment]
https://drive.google.com/open?id=0B7oKzbjdsbMDfkVhTXd6VVMycWlCSDZlcWp2ZU5tOWNQdXRvTGpxV3drQ1BuSDFyOFlwREk&authuser=0

Just set Mongo connection params (see TODO at beginning of test class), and init a collection named "test" .
Failed assertion are commented with TODOs ;-)

**Comment by evanchooly** [comment]
Thanks.  I'll have a look.

**Comment by fgouguenheim** [comment]
Have you invastigated this issue ?

**Comment by evanchooly** [comment]
I haven't yet but I'll try today.  I've been off on other stuff but I'm working hard to clear the queue here and get the release out.

**Comment by fgouguenheim** [comment]
Well, thanks for your reactivity :-)

**Comment by evanchooly** [comment]
Good news and bad news.  I've recreated your issue and fixed half of it.  The Datastore.update() operation now correctly updates the versions in the database.  However you're on you're own with the BulkUpdateOperation.  That's a driver level method and morphia has no visibility in to that update.  Consequently, morphia can't issue the appropriate version update operations.  If you update the documents in the database without morphia, you'll have to make sure you update that version field yourself.

**Comment by fgouguenheim** [comment]
Thank you very much for your clear response.

What about the upsert on an embeded object when the parent object does not exists, causing the parent object being created without having the version field set.
Could you fix that issue ?

Can you tell us when version 1.0.0 is supposed to be released, as we need it for our project ?

Thanks a lot

**Comment by evanchooly** [comment]
Upserts on a nonexistent entity should work as well.  Check out this test
and see if it matches your scenario:
https://github.com/mongodb/morphia/blob/master/morphia/src/test/java/org/mongodb/morphia/TestVersionAnnotation.java#L37-37

1.0.0 should hopefully be released in the next week or two.  There are 4
remaining tickets:  2 are closely related geo related issues, the other is
also a geo issue and the last is a docs task.  I don't get as much time as
I'd like on morphia these days but I'm aggressively carving out time to get
it done.

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "10gen.com", *"*antwerkz.com*"* *]*,
  location : *"*New York, NY*"* *}*

**Comment by fgouguenheim** [comment]
Yes that's quite the same test :-)
