### ISSUE TITLE
Make database operations throw more informative exceptions, and document them

### ISSUE THREAD

**Issue by yeefan** [mongodb/morphia#747]
It would be nice if the Morphia API can be enhanced so that database operations (e.g., insert, update, query) can be made to throw more informative exceptions when errors occur. This is so that an application can distinguish the different kinds of errors (e.g., mapping error, connection error, duplicate id error) and take more informed actions (e.g., should the query be retried?). Of course, this enhancement needs to be documented, preferably in the Javadocs. Thanks!

**Comment by evanchooly** [comment]
some examples of the ambiguities would be helpful

**Comment by evanchooly** [comment]
If you have specific examples, I'd be happy to discuss them.  Closing this for now.
