### ISSUE TITLE
ClassCastException when using maps of enums

### ISSUE THREAD

**Issue by sdeitmer** [mongodb/morphia#753]
When accessing enum values stored in a map, a ClassCastException is thrown. 
This problem was introduced in v 0.111 (it worked until v 0.110). Current snapshot (1.0.0-rc0-20150413.154616-3) is affected as well.
Tested with Java driver v 3.0.0 and MongoDB 3.0.1.

Sample code:

```java
package com.test;

import java.util.HashMap;
import java.util.Map;

import org.bson.types.ObjectId;
import org.mongodb.morphia.Datastore;
import org.mongodb.morphia.Morphia;
import org.mongodb.morphia.annotations.Entity;
import org.mongodb.morphia.annotations.Id;

import com.mongodb.MongoClient;

public class Mongo3Test {

    public enum SomeEnum {
        ONE, TWO, THREE
    }

    @Entity( "morphs" )
    public static class MorphEnumTest {
        @Id
        public ObjectId                id;
        public SomeEnum                field;
        public Map< String, SomeEnum > map = new HashMap< String, SomeEnum >();
    }

    public static void main( String[] args ) {

        // connect to db "test" on localhost
        Morphia morphia = new Morphia();
        morphia.mapPackageFromClass( MorphEnumTest.class );
        MongoClient mongo = new MongoClient();
        Datastore ds = morphia.createDatastore( mongo, "test" );

        // delete data from previous runs
        ds.delete( ds.createQuery( MorphEnumTest.class ) );

        // create and save test object
        MorphEnumTest e1 = new MorphEnumTest();
        e1.field = SomeEnum.ONE;
        e1.map.put( "key", SomeEnum.TWO );
        ds.save( e1 );

        // retrieve test object
        MorphEnumTest e2 = ds.find( MorphEnumTest.class ).get();

        // getting enum value from simple field works
        SomeEnum a = e2.field;

        // getting enum value from map doesn't work (throws ClassCastException)
        SomeEnum b = e2.map.get( "key" );

        mongo.close();
    }

}
```

**Comment by cteyton** [comment]
What if you add "@Embedded" on field and map ?

**Comment by sdeitmer** [comment]
Doesn't change anything, same exception.

**Comment by cteyton** [comment]
Does it change anything if you set "SomeEnum" on a seperate file (high-level class) and writing @Embedded on top of it ?

(ps : i'm not expert, just trying to help :))

**Comment by sdeitmer** [comment]
No, still doesn't work. 
BTW, I used nested classes / enums only to get the shortest example possible. The original code uses top level classes and enums.

**Comment by evanchooly** [comment]
This test works on the latest master.  Double check that this test accurately recreates the error (or that `master` fixes it).  If you're still seeing the issue please post a test case to the [mailing list](https://groups.google.com/forum/#!forum/morphia).

**Comment by sdeitmer** [comment]
I don't think it does. 
Mailing list post is here: https://groups.google.com/forum/#!topic/morphia/8oUWQUgYEYA

**Comment by evanchooly** [comment]
My test was just checking not null assuming the exception would come from the mapper but it comes back as a String out of the mapper so my test was missing that.

**Comment by yterradas** [comment]
any idea when will this be release?

**Comment by evanchooly** [comment]
I'm finishing up 1 actual bug and some docs updates.  Hopefully this week,
other work permitting, or next.

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "10gen.com", *"*antwerkz.com*"* *]*,
  location : *"*New York, NY*"* *}*

**Comment by yterradas** [comment]
thank you @evanchooly

**Comment by umbreak** [comment]
Same here. Happening for Map where the value is an enum. Waiting for a release.

Thanks
