### ISSUE TITLE
Generic TypeVariable not supported when saving a List<Generic>

### ISSUE THREAD

**Issue by Faliorn** [mongodb/morphia#755]
Hi

This issue is related to #737. I put this comment on that issue, but since it is closed, maybe it's better to create a new one.

I've upgraded to morphia 0.111 but the bug seems to still be there when using this in FatherEntity:

```private List<MyEmbedded> embeddedList;```

This sample code:

```java
ChildEntity child = new ChildEntity();
List<ChildEmbedded> embeddedList = new ArrayList<ChildEmbedded>();
ChildEmbedded embeddedItem = new ChildEmbedded();
embeddedList.add(embeddedItem);
child.setEmbeddedList(embeddedList);

Datastore ds = Conexion.getInstance().obtenerDatastore();
ChildDAO dao = new ChildDAO(ds);
dao.save(child);
```

Would end up with:

```
org.mongodb.morphia.mapping.MappingException: Error mapping field:com.morphiaexample.FatherEntity.embeddedList
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:553)

Caused by: java.lang.RuntimeException: Generic TypeVariable not supported!
	at org.mongodb.morphia.mapping.MappedField.toClass(MappedField.java:419)
```

Hope you can fix it. If you need any further informations, don't hesitate to get in touch.

Source code is still available at:

https://dl.dropboxusercontent.com/u/11873732/morphiaexample.rar
Best regards!

**Comment by evanchooly** [comment]
There's been a fair bit of work in this area lately.  can you try 1.0.0-rc0-SNAPSHOT and see if the issue remains.
