### ISSUE TITLE
AdvancedDatastore#insert(T...) and UseBulkWriteOperations & postPersit are not working

### ISSUE THREAD

**Issue by dinosavings** [mongodb/morphia#759]
Simple unit test for bulk write failure:

    public void testBulkTest() {

        {
            morphia.setUseBulkWriteOperations(false);

            final TestObject to1 = new TestObject();
            final TestObject to2 = new TestObject();
            datastore.insert(to1, to2);

            assertNotNull("normal insert1:", to1._id);//works
            assertNotNull("normal insert2:", to2._id);//works
        }

        {
            morphia.setUseBulkWriteOperations(true);

            final TestObject to1 = new TestObject();
            final TestObject to2 = new TestObject();
            datastore.insert(to1, to2); /// <<<< fails here

            assertNotNull("bulk insert1:", to1._id);
            assertNotNull("bulk insert2:", to2._id);
        }
    }

    @Entity
    public static class TestObject {

        @Id
        private ObjectId _id;

        @PostPersist
        public void doIt() {

            one = "one";
        }
    }

Throws following exception:

org.mongodb.morphia.mapping.MappingException: Missing _id after save!
	at org.mongodb.morphia.DatastoreImpl.postSaveGetKey(DatastoreImpl.java:993)
	at org.mongodb.morphia.DatastoreImpl.insert(DatastoreImpl.java:901)
	at org.mongodb.morphia.DatastoreImpl.insert(DatastoreImpl.java:876)
	at org.mongodb.morphia.DatastoreImpl.insert(DatastoreImpl.java:942)
	at BulkInsertTest.testBulkTest(BulkInsertTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

Also, code reviewing org.mongodb.morphia.DatastoreImpl#insert(com.mongodb.DBCollection, java.lang.Iterable<T>, com.mongodb.WriteConcern)

Line: 910

list.add(toDbObject(entity, new LinkedHashMap<Object, DBObject>()));

Why pass in " new LinkedHashMap<Object, DBObject>()". Seems unnecessary since code can handle null involvedObjects in org.mongodb.morphia.mapping.Mapper#toDBObject(java.lang.Object, java.util.Map<java.lang.Object,com.mongodb.DBObject>, boolean)

Also, in the !morphia.getUseBulkWriteOperations() branch, it appears that postSaveOperatorsion is not being called. To reproduce:

public void testPostPersis() {

        {
            morphia.setUseBulkWriteOperations(false);

            final TestObject to1 = new TestObject();
            final TestObject to2 = new TestObject();
            final TestObject to3 = new TestObject();
            datastore.save(to1);
            datastore.insert(to2, to3);

            assertNotNull("normal insert1:", to1._id);
            assertNotNull("normal insert2:", to2._id);
            assertEquals("one", to1.one);
            assertEquals("one", to2.one);  /// < fails
            assertEquals("one", to3.one);
        }

    }

**Comment by dinosavings** [comment]
I reviewed the fix but I don't understand something:

        postSaveOperations(involvedObjects);
        for (Entry<Object, DBObject> entry : involvedObjects.entrySet()) {
            final Key<T> key = postSaveGetKey(entry.getKey(), entry.getValue(), dbColl, involvedObjects);
            savedKeys.add(key);
        }

The code now calls  postSaveOperations(involvedObjects) explicitly and iterates and calls postSaveGetKey.

If you look at method postSaveGetKey:

    protected <T> Key<T> postSaveGetKey(final Object entity, final DBObject dbObj, final DBCollection dbColl,
                                        final Map<Object, DBObject> involvedObjects) {
        if (dbObj.get(Mapper.ID_KEY) == null) {
            throw new MappingException("Missing _id after save!");
        }
        mapper.updateKeyInfo(entity, dbObj, createCache());

        postSaveOperations(involvedObjects);
        final Key<T> key = new Key<T>((Class<? extends T>) entity.getClass(), dbColl.getName(), mapper.getId(entity));
        key.setType((Class<? extends T>) entity.getClass());

        return key;
    }

It is calling postSaveOperations(involvedObjects); again but for each key. I would imagine a big performance hit.

It seems that postSaveGetKey should not call postSaveOperations(involvedObjects). Better yet, this method should only work on entity, not for involvedEntities.

**Comment by evanchooly** [comment]
Yep.  You're probably right.  That API is a bit awkward and I actually broke it a bit on the way to what you see there trying to optimize it a bit.  I'll take a closer look at it but it seems you're probably right...

**Comment by dinosavings** [comment]
Modify the TestPostPersist:

        @PostPersist
        public void doIt() {
            if (one != null) {
                throw new RuntimeException("bad state");
            }
            one = "one";
        }

Unit test will fail.

**Comment by evanchooly** [comment]
ah.  nice.  will do. thanks.  I seem to recall another (really old) issue about multiple lifecycle calls.  perhaps this will catch that as well.

**Comment by evanchooly** [comment]
Going to reopen this briefly so I don't lose track of the issue @dinosavings found.

**Comment by evanchooly** [comment]
There was a bit more cleanup than I expected but I have it cleaned up to the "good enough" point now.
