### ISSUE TITLE
entity name problem

### ISSUE THREAD

**Issue by Rugal** [mongodb/morphia#773]
Today I encounter a very strange problem regarding entity naming.  
If my collection name is `class_room` then my class name is `ClassRoom`, so I have to map `@Entity(value="class_room")`, but that doesn't work.  
Only if I change the collection name in MongoDB to something like `classRoom` (without underscore) can morphia process it normally.  
Also at this moment I didn't change the `class_room` in `@Entity` annotation but it still mapping correctly. I think there must have some problem related with name mapping and underscore process.

**Comment by evanchooly** [comment]
There's nothing about underscores specifically.  Running a quick test locally shows this works just fine.  If you're on the latest version and still having issues, please post to the [mailing list](https://groups.google.com/forum/#!forum/morphia) with the details and we'll try to work things through.

**Comment by Rugal** [comment]
Actually I encountered another problem I think is related with the one above.  
I am trying to integrate Morphia with spring-data-mongo. Morphia provided some simple but powerful annotations and spring provided a lot of so called `repository` to generate query dynamically.   

     package rugal.sample.core.entity;
     @Entity(value = "student", noClassnameStored = true)
     public class Student
     {
         @Id
         private ObjectId id;
         private String name;
        private int age;
         @Reference
         private ClassRoom classRoom;
         ...

As you know I need to set map for morphia:  

        Morphia morphia = new Morphia();
        morphia.map(Student.class).map(ClassRoom.class);
        return morphia.createDatastore(mongo(), getDatabaseName());

When I tried to use Morphia only, every functions seems alright, including the issue I opened above.  
When I tried to integrate these two frameworks and set entity mapping in configuration:
   
    @Override
    protected String getMappingBasePackage()
    {
        return "rugal.sample.core.entity";
    }

Instead of providing mapping information for `Morphia`, this method actually only allows `spring-data` to scan the entity package.   

Thus at this time, when I trying to use `repository` methods to `save` a bean, such annotations like `@Reference` and @Entity(value = "classRoom", noClassnameStored = true)` on Entity class make no effect.   

    { "_id" : ObjectId("5554e407a0665724ac7b622a"), "_class" : "rugal.sample.core.entity.Student", "name" : "Bernstein", "age" : 26, "classRoom" : { "_id" : ObjectId("555418d50032f55ffbf8ca78"), "name" : "SE0907" } }
Just as I said, repository just saved all data in bean without looking at those annotations.  

So to verify this, I instantiate a `datastore` object in spring context and use it to `save` a bean. This time all annotations make effect on saving action.  

    { "_id" : ObjectId("5554e600a0665722e0335b5c"), "name" : "Bernstein", "age" : 26, "classRoom" : DBRef("classRoom", ObjectId("555418d50032f55ffbf8ca78")) }


So I think the issue is nothing to do with `Morphia`, the problem is actually in the way to integrate morphia and spring-data-mongo, spring overridden morphia's behavior.  
 I hope this issue could help someone in the future.  Also, if anyone could do the integration in a better way, please let me know.
