### ISSUE TITLE
Morphia as application server resource

### ISSUE THREAD

**Issue by heruan** [mongodb/morphia#783]
I'd like to abstract the MongoDB/Morphia initializer from the single application and make a Morphia datasource instance available to all applications on the application server (i.e. Glassfish 4.1). This would enforce many concurrency aspects such us single instance, connection and clustering. Does anyone have experience of this configuration?

**Comment by evanchooly** [comment]
You could wire something up using CDI and injecting the Datastore.  If you have further questions please post to the [mailing list](https://groups.google.com/forum/#!forum/morphia).  You'll probably want a Java EE mailing list if CDI is new to you.
