### ISSUE TITLE
PostPersist issue

### ISSUE THREAD

**Issue by ibugariu** [mongodb/morphia#786]
Dear Morphia Team,

recently I encountered an issue with latest 1.0.0rc0 release.
My team uses for a project MongoDB with Morphia. These days I migrated to latest MongoDB 3.0.1 java driver and Morphia 1.0.0.rc0. 
The logic within POJO classes relies on "_id" member( annotated with @Id ) to be populated after insert. 
I've investigated in debug and I found that DatastoreImpl.postSaveOperations() method calls methods annotated with @PostPersist before to update @Id field:

```java
  @SuppressWarnings("unchecked")
    private <T> List<Key<T>> postSaveOperations(final Iterable<T> entities, final Map<Object, DBObject> involvedObjects,
                                                final DBCollection collection, final boolean fetchKeys) {
        List<Key<T>> keys = new ArrayList<Key<T>>();
        for (final T entity : entities) {
            final DBObject dbObj = involvedObjects.remove(entity);
                
            mapper.getMappedClass(entity).callLifecycleMethods(PostPersist.class, entity, dbObj);
            
            if (fetchKeys) {
                if (dbObj.get(Mapper.ID_KEY) == null) {
                    throw new MappingException(format("Missing _id after save on %s", entity.getClass().getName()));
                }
                mapper.updateKeyInfo(entity, dbObj, createCache());
                keys.add(new Key<T>((Class<? extends T>) entity.getClass(), collection.getName(), mapper.getId(entity)));
            }
        }
        
        for (Entry<Object, DBObject> entry : involvedObjects.entrySet()) {
            final Object key = entry.getKey();
            mapper.getMappedClass(key)
                  .callLifecycleMethods(PostPersist.class, key, entry.getValue());
            
        }
        return keys;
    }
```

This seems to be a bug. I tested with an older version and it worked.
Could you please investigate the issue?
Thanks.

**Comment by evanchooly** [comment]
org.mongodb.morphia.mapping.Mapper#updateKeyInfo is what sets the @Id field on the entity.  `@PostPersist` is not used for that.

Are you saying that you expect the @Id field to be set when the `@PostPersist` methods are called?

**Comment by ibugariu** [comment]
Yes, exactly it worked with an older version of Morphia. The logic is based on the id being available after the insert. We don't want to make a new query to get the _id value.
Is it possible to have a fix for this issue?

**Comment by evanchooly** [comment]
OK.  I've tracked down that series of changes and you're right.  I'll clean that up.

**Comment by ibugariu** [comment]
Thank you very much!

**Comment by evanchooly** [comment]
np.  there should be a snapshot build available within the hour once jenkins churns through all the jobs.  You can either wait for that and test or build it locally with `./gradlew jar`
