### ISSUE TITLE
Add an option for caching the results of Class.forName in DefaultCreator

### ISSUE THREAD

**Issue by rlodge** [mongodb/morphia#789]
During performance testing we discovered that calls to Class.forName were taking a large amount of time relative to our expectations.  We'd like to have an option for caching the results of the class name lookup so that the forName method is only called on new classes.

**Comment by evanchooly** [comment]
That happens in a number of places in Morphia.  Any particular hotspot giving you problems?

**Comment by rlodge** [comment]
DefaultCreator.  We've made a change and seen a 10-12% performance improvement, at least in our case.  I'm preparing a pull request.

**Comment by evanchooly** [comment]
excellent.  I look forward to seeing it.  it won't make the 1.0 cut but we can do a 1.0.1 release soon enough.

**Comment by rlodge** [comment]
Works for me, as long as it's on the roadmap.
