### ISSUE TITLE
@Reference(idOnly=true) generates warning or incorrect results when querying

### ISSUE THREAD

**Issue by kushal** [mongodb/morphia#794]
Here's a simple test case:

**Comment by kushal** [comment]
public class Test {

    @Entity private static class TestEntityA {
        @Id public ObjectId id;

    }

    @Entity private static class TestEntityB {
        @Id public ObjectId id;
        @Reference(idOnly=true) public TestEntityA entityA;
    }

    public static void main(String[] args) {
        MongoClient mongoClient = new MongoClient(new MongoClientURI("mongodb://localhost/"));
        Morphia m = new Morphia();
        m.map(TestEntityA.class, TestEntityB.class);
        Datastore datastore = m.createDatastore(mongoClient, "testcase");

        TestEntityA a = new TestEntityA();
        a.id = new ObjectId();
        datastore.save(a);

        TestEntityB b = new TestEntityB();
        b.id = new ObjectId();
        b.entityA = a;
        datastore.save(b);

        System.out.println(datastore.find(TestEntityB.class, "entityA", a).get()); // null
        System.out.println(datastore.find(TestEntityB.class, "entityA", a.id).get()); // works with warning
        //System.out.println(datastore.find(TestEntityB.class, "entityA.id", a).get()); // fails
    }
}

**Comment by evanchooly** [comment]
What behavior are you seeing exactly?

**Comment by kushal** [comment]
The code sample includes comments for what output I get.
I would maybe expect both
System.out.println(datastore.find(TestEntityB.class, "entityA", a).get()); 
and
System.out.println(datastore.find(TestEntityB.class, "entityA", a.id).get()); 
to return the correct result, rather than no results and the correct results with a warning, respectively?

**Comment by evanchooly** [comment]
The last test *will* fail as there is no `.id` on entityA in TestEntityB.  I believe the second case may no longer give a warning based on some changes in that area in the last few days.  I'll dig in to that first case, though.

**Comment by evanchooly** [comment]
And the first case I just fixed.

**Comment by kushal** [comment]
Awesome, thank you!

**Comment by evanchooly** [comment]
my pleasure.  snapshots will be online soon.  i'll probably push 1.0.1 next week.
