### ISSUE TITLE
Nullpointerexception on mongo().find(MyClass.class).asList(), version: 1.0.0-rc1

### ISSUE THREAD

**Issue by Siamaster** [mongodb/morphia#795]
Hi,
One of my tests start to fail after trying the 1.0.0-rc1 version. It throws a null pointer exeption on a line like mongo().find(MyClass.class).asList(). When I switch back to 0.111, the code works again.
Now that line of code doesn't always crash, mostly it works. But on a special occasion where I update the MyClass collection by adding an array of inner documents just before calling that line of code, it crashes.
This is the stacktrace before my code: Caused by: java.lang.NullPointerException at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) at org.mongodb.morphia.converters.Converters.getEncoder(Converters.java:74) at org.mongodb.morphia.converters.CustomConverters.getEncoder(CustomConverters.java:29) at org.mongodb.morphia.converters.Converters.hasSimpleValueConverter(Converters.java:172) at org.mongodb.morphia.mapping.EmbeddedMapper.readCollection(EmbeddedMapper.java:206) at org.mongodb.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:144)

**Comment by evanchooly** [comment]
can you attach a test case?

**Comment by Siamaster** [comment]
Sorry for not attaching a test case. I don't want to expose too much application code and creating a new one just takes time. However, the issue was gone in 1.0.1, Good job guys!

**Comment by wdtaylor** [comment]
I am having this issue with version 1.0.1.  If I save a record and then immediately query a class then it works.  If I add a record then later run the same query with .asList() it returns a Nullpointerexception.  If I get an Iterator and try to get the class from interator.next() I also get a Nullpointerexception.

**Comment by evanchooly** [comment]
@wdtaylor please post a test case to the [mailing list](https://groups.google.com/forum/#!forum/morphia)

**Comment by Siamaster** [comment]
Sorry,
The problem still exists! IntelliJ was just not recompiling my tests.
I'll post a test case.

**Comment by Siamaster** [comment]
@evanchooly 
I'm wondering if you have seen the test case since the issue was marked as closed when I posted it?
Had to check, better safe than sorry.

**Comment by wdtaylor** [comment]
I need to do an isolated case. I had to roll back to version 0.11 to get to
work.

**Comment by Siamaster** [comment]
@wdtaylor  
you could check mine to see if it's the same problem, it sounds so.

https://groups.google.com/forum/#!topic/morphia/FNVikFUn0JU

**Comment by wdtaylor** [comment]
I should be able to test this out Monday and let you know.

Thanks!

**Comment by Siamaster** [comment]
@evanchooly
 
Please reply or reopen this issue so I know you have seen the recent messages and the test case. I'm still using version 0.111 because of this.
