### ISSUE TITLE
Returning score from text search

### ISSUE THREAD

**Issue by ctmay4** [mongodb/morphia#798]
Is it possible to return the full text score from a Query?

This is what my raw query looks like:

```js
db.disease.find( { $text: { $search: "brain" } }, 
                          { score: { $meta: "textScore" } } )
          .sort( { score: { $meta: "textScore" } } )
```

This works correctly and includes score in the results as well as sorting the results by score.

This is the same query using the MongoDB Java driver directly.

```java
// search with the Java driver
BasicDBObject textSearch = new BasicDBObject("$search", "brain");
BasicDBObject search = new BasicDBObject("$text", textSearch);

BasicDBObject meta = new BasicDBObject("$meta", "textScore");
BasicDBObject score = new BasicDBObject("score", meta);

List<DBObject> diseases = collection.find(search, score).sort(score).toArray();
Assert.assertEquals(2, diseases.size());
Assert.assertEquals("brain", diseases.get(0).get("name"));
Assert.assertEquals("benign-brain", diseases.get(1).get("name"));
```

I've been reading through the documentation and I can't figure out how to accomplish the same thing in Morphia. From the search example in the Morphia documentation (http://mongodb.github.io/morphia/1.0/guides/querying/#text-searching), this is how my query looks:

```java
List<DiseaseBean> diseases = datastore.createQuery(DiseaseBean.class)
                                      .search("brain")
                                      .order("_id")
                                      .asList();
Assert.assertEquals(2, diseases.size());
```

This returns the correct documents, however does not include the score and is ordering by "_id". I don't see any way to handle the $meta operator in Morphia to get at the "textScore". Is this possible?

**Comment by evanchooly** [comment]
I see this was also posted to stackoverflow.  I'll answer there since the issue tracker isn't the best forum for this kind of question.

Answered:  https://stackoverflow.com/questions/30709505/include-score-in-morphia-full-text-search/30738588#30738588
