### ISSUE TITLE
UpdateOpsImpl method expired inc and dec

### ISSUE THREAD

**Issue by fredwuye** [mongodb/morphia#802]
I found the method inc() and dec() expired on Class UpdateOpsImpl of Morphia version 1.0.0-rc1. The last fine version is 0.111. 
Who can solve this issue?

**Comment by evanchooly** [comment]
I'm not sure what you're asking.  If you post the details of your problem and any code/error messages to the [mailing list](https://groups.google.com/forum/#!forum/morphia), maybe we can find a solution.

**Comment by fredwuye** [comment]
When I use the morphia to update one document on mongo, I use the method inc() of UpdateOpsimpl. I find it doesn't work. The value of number doesn't change. But the method does work under version 0.111. So I check the morphia version among 0.105 to 1.0.0-rc1. The method can't work since 1.0.0. It is the same to the method dec().
I'm out of office today so I can't provide the codes at this moment. If you want it, I can provide it sometimes later.

**Comment by evanchooly** [comment]
Please do but post it to the mailing as the issue tracker isn't intended for such discussions.

**Comment by fredwuye** [comment]
Sorry but late. See my comments in this method. The inc() doesn't work on Morphia 1.0.0


    public Boolean addCouponCount(Datastore couponDao, ObjectId couponId, Integer addCount, String userId) {
        try {
            // Query for certain document
            Query<Coupon> query = couponDao.createQuery(Coupon.class).filter("id", couponId);
            List<Coupon> list = query.asList();

            // Show the current value
            for (Coupon coupon : list) {
                System.out.println(coupon.getId() + "\t" + coupon.getTotalCount() + "\t" + coupon.getUpdateDate() + "\t" + coupon.getUpdateUser());
            }

            // Update the fields
            UpdateOperations<Coupon> ops = couponDao.createUpdateOperations(Coupon.class)
                    // !! Nothing happened for inc() or dec() on Morphia 1.0.0 but it works on 0.111
                    .inc("totalCount", 20) //.dec("totalCount") .inc("totalCount")
                    .set("updateUser", userId)
                    .set("updateDate", new Date());
            UpdateResults result = couponDao.update(query, ops);

            query = couponDao.createQuery(Coupon.class).filter("id", couponId);
            list = query.asList();

            // Show the current value again
            for (Coupon coupon : list) {
                System.out.println(coupon.getId() + "\t" + coupon.getTotalCount() + "\t" + coupon.getUpdateDate() + "\t" + coupon.getUpdateUser());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }
Sorry but late. See my comments in this method. The inc() doesn't work on Morphia 1.0.0
    public Boolean addCouponCount(Datastore couponDao, ObjectId couponId, Integer addCount, String userId) {
        try {
            // Query for certain document
            Query<Coupon> query = couponDao.createQuery(Coupon.class).filter("id", couponId);
            List<Coupon> list = query.asList();

            // Show the current value
            for (Coupon coupon : list) {
                System.out.println(coupon.getId() + "\t" + coupon.getTotalCount() + "\t" + coupon.getUpdateDate() + "\t" + coupon.getUpdateUser());
            }

            // Update the fields
            UpdateOperations<Coupon> ops = couponDao.createUpdateOperations(Coupon.class)
                    // !! Nothing happened for inc() or dec() on Morphia 1.0.0 but it works on 0.111
                    .inc("totalCount", 20) //.dec("totalCount") .inc("totalCount")
                    .set("updateUser", userId)
                    .set("updateDate", new Date());
            UpdateResults result = couponDao.update(query, ops);

            query = couponDao.createQuery(Coupon.class).filter("id", couponId);
            list = query.asList();

            // Show the current value again
            for (Coupon coupon : list) {
                System.out.println(coupon.getId() + "\t" + coupon.getTotalCount() + "\t" + coupon.getUpdateDate() + "\t" + coupon.getUpdateUser());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

**Comment by evanchooly** [comment]
Take a look at this [test](https://github.com/mongodb/morphia/blob/master/morphia/src/test/java/org/mongodb/morphia/TestUpdateOps.java#L146-146).  It's doing a `$inc` and a `$set` and the test passes.  What results are you seeing that make you think that `inc()` isn't working?
