### ISSUE TITLE
Cannot map entities with generic arrays

### ISSUE THREAD

**Issue by mark1ewis** [mongodb/morphia#803]
When I try to map a class with a parameterized array member variable in 1.0.1, I get this exception:

`java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class`

I ran into this while porting some code originally written for Morphia 0.99 over to 1.0.1, so I'm reasonably sure that this is a regression from 0.99.

It's worth noting that this is the same exception as in issue #772, although that was closed for lack of information and it didn't have enough information for me to know if it was the same case or not.

I'm afraid I didn't get a chance to create a test case that integrates with the Maven build, but I do have a self-contained class with a main method that demonstrates the issue, see here:

```java
import org.mongodb.morphia.Morphia;
import org.mongodb.morphia.annotations.Id;

public class Test {
        public static void main(String [] args) throws Exception {
                Morphia morphia = new Morphia();
                morphia.map(MyEntity.class);
                // Never gets here, exception is thrown!
        }

        static class MyEntity {
                @Id
                private String id;
                private SomethingGeneric<String> [] member;
        }

        static class SomethingGeneric<T> {}
}
```

**Comment by mark1ewis** [comment]
Sorry, I accidentally left out the full stack trace, here it is:

```
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
	at org.mongodb.morphia.mapping.MappedField.discoverType(MappedField.java:199)
	at org.mongodb.morphia.mapping.MappedField.discover(MappedField.java:117)
	at org.mongodb.morphia.mapping.MappedField.<init>(MappedField.java:95)
	at org.mongodb.morphia.mapping.MappedClass.discover(MappedClass.java:214)
	at org.mongodb.morphia.mapping.MappedClass.<init>(MappedClass.java:145)
	at org.mongodb.morphia.mapping.Mapper.addMappedClass(Mapper.java:163)
	at org.mongodb.morphia.Morphia.map(Morphia.java:67)
	at Test.main(Test.java:7)```

**Comment by evanchooly** [comment]
What version of the JDK are you on?

**Comment by mark1ewis** [comment]
I ran the tests on Java 8.
