### ISSUE TITLE
Aggregation - extended id grouping

### ISSUE THREAD

**Issue by heyarny** [mongodb/morphia#810]
There is an example in SQL to mongodb documentation.

```
db.orders.aggregate( [
   {
     $group: {
        _id: {
           cust_id: "$cust_id",
           ord_date: {
               month: { $month: "$ord_date" },
               day: { $dayOfMonth: "$ord_date" },
               year: { $year: "$ord_date"}
           }
        },
        total: { $sum: "$price" }
     }
   }
] )
```

I can't find a way to generate the same example in Java.
Anyone able to help me out here?

Thanks

**Comment by evanchooly** [comment]
Please post this question to the [mailing list](https://groups.google.com/forum/#!forum/morphia).  More people monitor the list and so are more likely to have an answer for you.

**Comment by heyarny** [comment]
@evanchooly 
Mailing list was no help.
I'm not sure if this is possible at all.
There is no way to sub-group.

I'm not able to reproduce the following part from the example above:
´´´
ord_date: {
               month: { $month: "$ord_date" },
               day: { $dayOfMonth: "$ord_date" },
               year: { $year: "$ord_date"}
           }
```

my solution right now is which is different, because I can't sub-group:
```
AggregationPipeline pipeline = ds
				.createAggregation(ListenLog.class)
				.group(
						id(
							grouping("year", new Accumulator("$year", "startTime")),
							grouping("month", new Accumulator("$month", "startTime")),
							grouping("day", new Accumulator("$dayOfMonth", "startTime"))
						)
				);
```

this results into following json which seems to generate "null" instead of the field:
```
[{ "$group" : { "_id" : { "year" :  null  , "month" :  null  , "day" :  null }}}]
```

So my conclusion is:
1. sub-grouping is not supported
2. there's a bug generating the json source (field is ignored)

Hope this helps

**Comment by heyarny** [comment]
I modified the source of
https://github.com/mongodb/morphia/blob/master/morphia/src/main/java/org/mongodb/morphia/aggregation/AggregationPipelineImpl.java

```

    @Override
    public AggregationPipeline group(final List<Group> id, final Group... groupings) {
        DBObject idGroup = new BasicDBObject();
        for (Group group : id) {
        	if (group.getAccumulator() != null) {
                Accumulator accumulator = group.getAccumulator();
                idGroup.put(group.getName(), new BasicDBObject(accumulator.getOperation(), accumulator.getField()));
        	} else {
        		idGroup.put(group.getName(), group.getSourceField());
        	}
        }
        DBObject group = new BasicDBObject("_id", idGroup);
        for (Group grouping : groupings) {
            Accumulator accumulator = grouping.getAccumulator();
            group.put(grouping.getName(), new BasicDBObject(accumulator.getOperation(), accumulator.getField()));
        }
```

This supports at least operations within id now, but still no sub-grouping.
Hope this helps to improve the library.
