### ISSUE TITLE
Disable Entity Cache request

### ISSUE THREAD

**Issue by ktonder** [mongodb/morphia#812]
Would it be possible to add a feature where I can easily disable entitycachingen, it causes problems the data to load incorrectly from database and does not match what the DBObject is compared to the converted objects.

**Comment by larslorenzen** [comment]
It would be nice to have a cache factory in the MapperOptions.

**Comment by ktonder** [comment]
Yes, that will do. Then everyone can make a caching that they self need, in my case I just made a cache that implement EntityCache and is basically empty. :) solved the loading issue I had and will just hardcode it for now.

Your implementation looks promising, any idea if it will get pulled into master branch ?

**Comment by larslorenzen** [comment]
No clue, we have a very large project depending on an old version of morphia (google code version) where we introduced some factories. 
At the moment i am trying to use this morphia version and integrate our factories.
Will create a pull request for the first version.
