### ISSUE TITLE
save for updating an entity delete fields out of the mapping area

### ISSUE THREAD

**Issue by chandon** [mongodb/morphia#815]
If i use a mapping configuration on an entity, i load it and save it again, i lose every "out of the mapping" fields of the document.
Example, document :
 
     { "_id" : "12345678901234567890123456", "test" : "text", "test2", "moreText"}

And entity defined by : 

    class MyTest {
    @Id
    ObjectId id;
    String test;
    }

No definition in MyTest for test2... then doing : 

    MyTest mytest = ds.get(MyTest.class, new ObjectId("12345678901234567890123456"));
    ds.save(mytest);

In the Datastore, the value of "test2" is lost...

It seems it's because of com.mongodb.DBCollection.replaceOrInsert.It should be "update" and not "replace"

For example, this is very annoying when using concurrent ODM (like Morphia for Java and Doctrine for Symfony 2). Morhpia add "className", and Symfony add "type" for the same purpose. But Morphia delete the "type" field if not in the mapping information.
This is also a problem for embedded polymorphic entities : if not defined in the mapping area of Morphia (because it seems it's not possible), they are deleted at the "save" time.

**Comment by evanchooly** [comment]
What happens when you use `ds.merge()` ?

**Comment by evanchooly** [comment]
If this is still a problem in your app, let's follow this up on on the [mailing list](https://groups.google.com/forum/#!forum/morphia) where it'd be a bit more appropriate to have a discussion.
