### ISSUE TITLE
GWT docs incomplete

### ISSUE THREAD

**Issue by Fuzzo** [mongodb/morphia#818]
The page https://github.com/mongodb/morphia/wiki/GoogleWebToolkit says to download the gwt module jar and add the inherits node to gwt.xml module

Where is the GWT module JAR? Without it i get the error: [ERROR] Unable to find 'org/mongodb/morphia/Morphia.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?

**Comment by ismetozalp** [comment]
https://github.com/ismetozalp/morphia-gwt

**Comment by evanchooly** [comment]
With the new docs site, i should disable the wiki or at least link to the
new site <http://mongodb.github.io/morphia/>.  I'll do that now.

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "10gen.com", *"*antwerkz.com*"* *]*,
  location : *"*New York, NY*"* *}*
