### ISSUE TITLE
Make MorphiaIterator and Query implement Closeable to utilize "try-with-resources" in Java 7

### ISSUE THREAD

**Issue by rzanner** [mongodb/morphia#820]
To be able to automatically close a MorphiaIterator or a Query using a "try-with-resources" statement in Java 7, the classes need to implement java.lang.AutoCloseable. To not break backwards compatibility with Java 5, they should rather implement java.io.Closeable.

**Comment by evanchooly** [comment]
At the moment, we're restricting the JVM level support to Java 6 but once we get the go ahead to target newer JVMs this will definitely happen.

**Comment by evanchooly** [comment]
My mistake.  I misunderstood a few bits.  We can definitely do this soonish.

**Comment by shils** [comment]
@evanchooly is there still a plan to do this?
