### ISSUE TITLE
Mapper.toMongoObject() : For references, MappedField can be null if validation is disabled.

### ISSUE THREAD

**Issue by kazetsukaimiko** [mongodb/morphia#824]
First, my use case. I have a hierarchic data structure that uses polymorphism to track several different concepts using the same entity structure. Simple example:

public abstract class Container {
  public Container parent;
}
Glass extends Container //...
Bucket extends Container //...
Ball extends Container //...

Ball ball = // Fetch Ball from database
Container one = ball.parent; // Could be any container, this case = reference to Glass
Container two = one.parent; // Could be any container, this case = reference to Bucket

And on and on. In my case the top level is "Partition", with Questionnaire, Question, Section, and Option underneath.
To trace this heirarchy, I have to ask four different collections who has [Questionnaire] as its parent. I don't know what is going to come back, and for everything that does come back I have to ask the same question again, ending up with
Questionnaire favorite foods -> Section 1 -> (sub) Section A -> Question 1 -> Option 3.

Because of this, I get lots of warnings from Morphia when building trees of these Partitions:

The type(s) for the query/update may be inconsistent; using an instance of type 'edu.harvard.channing.entity.morphia.stash.Question' for the field 'edu.harvard.channing.entity.morphia.stash.Partition.parent' which is declared as 'edu.harvard.channing.entity.morphia.stash.Questionnaire'
The type(s) for the query/update may be inconsistent; using an instance of type 'edu.harvard.channing.entity.morphia.stash.Question' for the field 'edu.harvard.channing.entity.morphia.stash.Partition.parent' which is declared as 'edu.harvard.channing.entity.morphia.stash.Questionnaire'
Validation warnings:
[Validation failed: 'Type edu.harvard.channing.entity.morphia.stash.Questionnaire may not be queryable with value 'edu.harvard.channing.entity.morphia.stash.Question@17cacc7' with class edu.harvard.channing.entity.morphia.stash.Question']
Validation warnings:
[Validation failed: 'Type edu.harvard.channing.entity.morphia.stash.Questionnaire may not be queryable with value 'edu.harvard.channing.entity.morphia.stash.Question@17cacd9' with class edu.harvard.channing.entity.morphia.stash.Question']

This floods the logs with junk, and I know what I'm doing, so I call .disableValidation() on my queries. 

This all worked fine on Morphia 0.109 and Mongo Java Driver 2.12. However, post upgrade to Morphia 1.0.1 and Mongo Java Driver 3.0.2, I get an NPE on line 419 of Mapper.java if validation is disabled:
https://github.com/mongodb/morphia/blob/1.0.x/morphia/src/main/java/org/mongodb/morphia/mapping/Mapper.java#L419

This is because the MappedField 'mf' is null at that point, and tracing back I can see it was constructed from a method named "validateQuery":
https://github.com/mongodb/morphia/blob/1.0.x/morphia/src/main/java/org/mongodb/morphia/query/FieldCriteria.java#L38-L44

I'm assuming that disabling validation is inadvertently creating a set of conditions that skips or forgoes generating this MappedField object or its dependencies.

For the time being, I have the workaround of NOT calling disableValidation, so this isn't critical.

Please let me know if you would like me to build a test case project for you to reproduce this issue, I should be able to whip something up fairly easily.

**Comment by evanchooly** [comment]
If you had a test case handy, I could git bisect against 0.109 and see what changed.  I can probably recreate this either way but it'd definitely be simpler with one in hand.

**Comment by kazetsukaimiko** [comment]
Let me see if I can quickly whip this up...

**Comment by kazetsukaimiko** [comment]
I've reproduced the issue and have a tarball with a sample maven project in it.

How would I provide this to you?

**Comment by evanchooly** [comment]
a dropbox link would work...

**Comment by kazetsukaimiko** [comment]
Here is a link to the Project Tarball.
http://fallingsnow.jp/morphia824.tar.gz

**Comment by kazetsukaimiko** [comment]
Lines 114-117 of ReferenceCriteriaNPE.java will show you how to toggle between the NPE condition and warnings. You can set your mongo host connection on line 31.

**Comment by evanchooly** [comment]
Awesome.  Thanks.  I'll try to take a look at it as soon as I can.  It'll be a few days because of other commitments, though.

**Comment by kazetsukaimiko** [comment]
Thank you sir!
