### ISSUE TITLE
Problem when inserting object with hashmap which keys contain a dot

### ISSUE THREAD

**Issue by cteyton** [mongodb/morphia#827]
Re-opens #268

I encountered this issue as well and reproduced it : 

```
static class MyObjectWithMap {
        Map<String, String> map = Maps.newHashMap();
}
```

```
MyObjectWithMap obj = new MyObjectWithMap();
obj.map.put("keyOk", "OK");
getDs().save(obj); // No problem
obj.map.put("key.notOK", "notOK");
getDs().save(obj); // Problem
```

Generates this :
```
java.lang.IllegalArgumentException: Invalid BSON field name key.notOK
	 at org.bson.AbstractBsonWriter.writeName(AbstractBsonWriter.java:494)
	 at com.mongodb.DBObjectCodec.encodeMap(DBObjectCodec.java:219)
	 at com.mongodb.DBObjectCodec.writeValue(DBObjectCodec.java:198)
	 at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:128)
	 at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:61)
	 at com.mongodb.CompoundDBObjectCodec.encode(CompoundDBObjectCodec.java:48)
	 at com.mongodb.CompoundDBObjectCodec.encode(CompoundDBObjectCodec.java:27)
	 at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	 at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
```

**Comment by washu** [comment]
key names with . in them in mongo not allowed http://docs.mongodb.org/manual/reference/limits/#naming-restrictions

**Comment by evanchooly** [comment]
Thanks for posting this @washu.  I'd meant to and then got side tracked.  @cteyton you'll need to change your key values before you can store them.

**Comment by plaa** [comment]
Is there any generic workaround?  We're storing a document with generic JSON content (i.e. we do not control the key names).  I'm thinking of having some pre/postprocessor that replaces invalid keys with an encoded version and replaces them upon reading.  Maybe defining a special JsonMap class which would know to do the proper processing.

**Comment by evanchooly** [comment]
You could try using an `@PrePersist` and an `@PreLoad` method to massage key values in the `DBObject`.  That'd make it transparent/automatic at least.  If it's a global change and not just on one entity, an `EntityListener` might be the ticket.

**Comment by washu** [comment]
encode you json document as a String and just parse it on load or you could save it as org.bson.types.Binary object i would recomend just store it as a string and handle marshalling yourself.

**Comment by plaa** [comment]
Can any of the lifecycle methods (either annotations of `EntityListeners`) be used on embedded objects?  I'd like to create `JsonMap` class, which functions as a map within an entity, but performs the transformation on the map automatically.  Can I override that an embedded `JsonMap` object is serialized using a specific listener?

**Comment by evanchooly** [comment]
Not directly because embedded objects don't have a lifecycle separate from
the enclosing type.  If you'd like help with the listeners, please post
your questions to the mailing list
<https://groups.google.com/forum/#!forum/morphia>.

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "mongodb.com <http://www.mongodb.com>", *"*antwerkz.com*"*
*]*,
  location : *"*New York, NY*"* *}*
