### ISSUE TITLE
Upgrading Morphia fails with MappingException.

### ISSUE THREAD

**Issue by energyhub-dev** [mongodb/morphia#833]
I'm trying to upgrade Morphia from .108 to 1.01 in some code I've inherited. There's a class that looks like:

    @Entity(value="audit", noClassnameStored=true)
    public class AuditEntry<T>  {
        @Id
        private ObjectId id;
    
        @Embedded
        private Delta<T> delta;
    
        public ObjectId getId() {
            return id;
        }

        public void setId(ObjectId id) {
            this.id = id;
        }
    
    
        public Delta<T> getDelta() {
            return this.delta;
        }
    
        public void setDelta(Delta<T> delta) {
            this.delta = delta;
        }
    }

Then the embedded delta class:

    @Embedded
    public class Delta<T> {
        private Map<String, Object> before;
        private Map<String, Object> after;
        
        private Delta() { }
    
        public Delta(Map<String, Object> before, Map<String, Object> after) {
            this.before = before;
            this.after = after;
        }
    
        public void setBefore(Map<String, Object> before) {
            this.before = before;
        }
        public Map<String, Object> getBefore() {
            return (this.before == null ? Collections.<String, Object>emptyMap() : this.before);
        }
        public void setAfter(Map<String, Object> after) {
            this.after = after;
        }
        public Map<String, Object> getAfter() {
            return (this.after == null ? Collections.<String, Object>emptyMap() : this.after);
        }
    }

After upgrading the Morphia version, this now breaks during mapping as follows:

    Caused by: org.mongodb.morphia.mapping.MappingException: A type could not be found for the field null.null
    	at org.mongodb.morphia.mapping.MappedField.discoverType(MappedField.java:211)
    	at org.mongodb.morphia.mapping.MappedField.<init>(MappedField.java:101)
    	at org.mongodb.morphia.mapping.EphemeralMappedField.<init>(EphemeralMappedField.java:36)
    	at org.mongodb.morphia.mapping.MappedField.discoverType(MappedField.java:189)
    	at org.mongodb.morphia.mapping.MappedField.discover(MappedField.java:117)
    	at org.mongodb.morphia.mapping.MappedField.<init>(MappedField.java:95)
    	at org.mongodb.morphia.mapping.MappedClass.discover(MappedClass.java:214)
    	at org.mongodb.morphia.mapping.MappedClass.<init>(MappedClass.java:145)
    	at org.mongodb.morphia.mapping.Mapper.addMappedClass(Mapper.java:163)
    	at org.mongodb.morphia.Morphia.map(Morphia.java:67)
    	at org.mongodb.morphia.Morphia.mapPackage(Morphia.java:114)
    	at org.mongodb.morphia.Morphia.mapPackage(Morphia.java:96)

The `Delta` class seems unnecessarily generified, but I'm disinclined to change it, especially when it was working before and I was under the impression this is  something Morphia supports. Why has this started breaking?

**Comment by evanchooly** [comment]
The mapping code has been under some relatively heavy updates and it looks like we broke something.

**Comment by evanchooly** [comment]
I have a jar that might fix your problem.  The test I have right now it is a bit primitive and I'll round it out a bit but if you could try this jar and let me know if it resolves your problem that'd be great.  In the meantime, I'll build out some more robust testing around this area.

https://www.dropbox.com/s/iv9gtzhmqqz6956/morphia-1.1.0-SNAPSHOT.jar?dl=0

**Comment by evanchooly** [comment]
didn't intend for github to close this yesterday.

**Comment by evanchooly** [comment]
@energyhub-dev ping

This seems to fix your problem but I haven't heard back.  If I don't hear back soon, I'll have to assume this fixes things for you and close this issue.

**Comment by energyhub-dev** [comment]
Sorry -- I was just exploring possibly upgrading, and decided no on the basis of this bug. I'll give it a whirl when I get another chance -- thanks for the effort!

**Comment by dkilmer** [comment]
I'm not the original reporter, but I had this issue on my `ensureIndexes()` call. I tested out the snapshot you posted, and it fixed the issue for me.

**Comment by evanchooly** [comment]
Closing this as fixed then.
