### ISSUE TITLE
Aggregation unwind function does not behave as expected?

### ISSUE THREAD

**Issue by littlejedi** [mongodb/morphia#854]
I'm trying to do a simple MongoDB aggregation here. Basically i have documents like this:

      {
         timestampInMs: 1444094140442,
         records: [{
             value: "testvalue",
             experiment: {
                 id: "56105b0af2763b25806d1365",
                 name: "integrationtest-kkkk",
                 created: "2015-10-03T22:47:38.479+0000",
                 updated: null
             },
             sensorId: "testsensor",
             dataType: 1
         }, {
             value: "testvalue2",
             experiment: {
                 id: "56105b0af2763b25806d1365",
                 name: "integrationtest-kkkk",
                 created: "2015-10-03T22:47:38.479+0000",
                 updated: null
             },
             sensorId: "testsensor2",
             dataType: 1
         }, {
             value: "testvalue3",
             experiment: {
                 id: "56105b0af2763b25806d1365",
                 name: "integrationtest-kkkk",
                 created: "2015-10-03T22:47:38.479+0000",
                 updated: null
             },
             sensorId: "testsensor3",
             dataType: 1
         }, {
             value: "testvalue4",
             experiment: {
                 id: "56105b0af2763b25806d1365",
                 name: "integrationtest-kkkk",
                 created: "2015-10-03T22:47:38.479+0000",
                 updated: null
             },
             sensorId: "testsensor4",
             dataType: 1
         }],
         created: "2015-10-06T01:15:40.501+0000",
         updated: "2015-10-06T01:15:40.528+0000"
     }

The java model looks like this

    @Entity("sensordatadocs")
    @Indexes ({
        @Index(fields = @Field("timestampInMs"), options = @IndexOptions(name = "timestamp_ms_index"))
    })
    public class DbSensorDataDocument {
        
        @Id
        // Should be milliseconds since Epoch
        private Long timestampInMs;
        
        @Embedded
        private List<DbSensorDataRecord> records;
        
        private Date created;
        
        private Date updated;
    }

    public class DbSensorDataRecord {
            
        private String value;
        
        @Reference
        private Experiment experiment;
        
        private String sensorId;
        
        private int dataType;
    }

When I used the DB query 

    db.sensordatadocs.aggregate([{$unwind: "$records"}])

It gave me 4 documents, each document's "records" contains a single item which corresponds to item in the original array. However, when I used Morphia's API, like this:
 

    Iterator<DbSensorDataDocument> iter = datastore.createAggregation(DbSensorDataDocument.class)
            .unwind("records").aggregate(DbSensorDataDocument.class);
It would return result like this:

    {
         timestampInMs: 1444094140442,
         sensorId: "testsensor",
         value: "testvalue",
         experimentId: "56105b0af2763b25806d1365",
         dataType: 1
    }, {
         timestampInMs: 1444094140442,
         sensorId: "testsensor",
         value: "testvalue",
         experimentId: "56105b0af2763b25806d1365",
         dataType: 1
    }, {
         timestampInMs: 1444094140442,
         sensorId: "testsensor",
         value: "testvalue",
         experimentId: "56105b0af2763b25806d1365",
         dataType: 1
    }, {
         timestampInMs: 1444094140442,
         sensorId: "testsensor",
         value: "testvalue",
         experimentId: "56105b0af2763b25806d1365",
         dataType: 1
    }

This is how my iteration code looks like:

    while (iter.hasNext()) {
                DbSensorDataDocument doc = iter.next();
                final SensorDataRecord record = SensorDataUtils.flattenSensorDataDocument(doc);  
                result.add(record);
            }

Note that the number of items is correct, however, the values inside the "records" are incorrect, **in fact they are values of only the **first** item in the original array**. Why is this the case? Please help. Thanks!

Morphia version 1.0.1

**Comment by evanchooly** [comment]
First, my apologies for taking forever to respond but here's what's going on.  The `$unwind` creates a new document for each element of the array.  Those new documents consist of the original document with the array field replaced by an array element.  What this means is that each document has the same _id value which Morphia sees and assumes that each of those documents are, in fact, the same document and returns the cached deserialized instance for that ID value.

To get around that, you simply need to remove the `_id` from the unwound documents like this:
```java
Iterator<DbSensorDataDocument> iter = getDs().createAggregation(DbSensorDataDocument.class)
                                             .unwind("records")
                                             .project(projection("_id").suppress(),
                                                      projection("timestampInMs"),
                                                      projection("records"),
                                                      projection("created"),
                                                      projection("updated"))
                                             .aggregate(DbSensorDataDocument.class);
```

Now each document has no ID value and is correctly deserialized in to a new instance.  Given how old this issue is I'm going to close it but if you continue to have problems please post to the [mailing list](https://groups.google.com/forum/#!forum/morphia) and we'll get you squared away.
