### ISSUE TITLE
MongoClient creation and connection pool size

### ISSUE THREAD

**Issue by nmayakuntla** [mongodb/morphia#855]
We use morphia in our framework and have some basic questions.

Does morphia create MongoClient.java to talk to mongo cluster?
If so, what is the life cycle of MongoClient instance created?.
How are connection pool settings handled?

**Comment by evanchooly** [comment]
Morphia takes a MongoClient and uses whatever it's given so you're free to configure the client however you'd like.  If you have any further questions, please post them to the [mailing list](https://groups.google.com/forum/#!forum/morphia)
