### ISSUE TITLE
Bug in MapNotSerializable?

### ISSUE THREAD

**Issue by trishagee** [mongodb/morphia#857]
I think I just found a typo that could be a bug. In MapNotSerializable, lines 27 and 33 are the same:

    if (!Serializable.class.isAssignableFrom(keyClass)) {

when in fact they have two different null checks just before them. IntelliJ tells me the second one could throw a null pointer. I think it should in fact, be:

    if (!Serializable.class.isAssignableFrom(valueClass)) {

**Comment by trishagee** [comment]
Sorry for not simply submitting a pull request at this time, but I'm in the middle of a large experimental refactor.

**Comment by evanchooly** [comment]
Now that you have time on your hands...  :D

**Comment by evanchooly** [comment]
Did you ever run this one to ground?
