### ISSUE TITLE
MongoDB client v3 and Morphia queries

### ISSUE THREAD

**Issue by umbreak** [mongodb/morphia#862]
Hello,

I know that it is possible to combine Morphia queries with DBObject. The fluent interface allows things like `T t = morphia.fromDBObject(type, dbObject)` and it is useful in cases where morphia does not implement the query you want to perform (like [this](https://github.com/mongodb/morphia/issues/709) or [this](https://github.com/mongodb/morphia/issues/835)).

However, checking the MongoDB java client [documentation](https://docs.mongodb.org/getting-started/java/query/#logical-or) I've found that there is nothing anymore about `DBObject` or `BasicDBObject`. They use now the `org.bson.conversions.Bson` and `FindIterable`. It would be great if Morphia can be compatible with those Objects and if those Bson could be passd to a morphia query as well.

The new MongoDB interface, with the help of helpers is much more compact. For example, a elemMatch query with an or (which cannot be done in Morphia) it looks like that:

    Bson bson=elemMatch("list", and(or(eq("ID1", new ObjectId("55c1ff903b764c08aa108464")), eq("ID1", new ObjectId("55c1ff903b764c08aa108466"))), eq("list2.ID1", new ObjectId("562f4e43bf828176c5e773d6"))));

**Comment by evanchooly** [comment]
You'll have to use the legacy API in the java driver for this.  Once #749 is in, you can do it this way.
