### ISSUE TITLE
Expect to provide a specific entity instance by factory method when mapping a doc to one of polymorphic entities

### ISSUE THREAD

**Issue by ikonglong** [mongodb/morphia#863]
For example, there are **Employee**, **Developer** and **Manager** classes. And we save all these entities into a collection named **employees**。when we read from mongo, we expect to map each doc to its corresponding entity, maybe a **Developer** or **Manager**。

Morphia support this, but it's not good. It saves the full class name as a field into the **employees** collection. This make our application code be tightly couple with mongo db. If we move the entity classes from current package to another package to refactor our code, the tragedy happened and the read operation didn't work.

I expect that Morphia provides a annotation which denotes the factory method that creates a specific entity instance according to a field in the mapped doc when mapping a doc to a polymorphic entity. For example:

```java
@StaticFactoryMethod("newInstanceByType")
@Entity(value = "content_sections", noClassnameStored = true)
public abstract class ContentSection extends AbstractEntity {

    protected ContentType type;

    public ContentType type() {
        return this.type;
    }

    public static ContentSection newInstanceByType(DBObject dbObject) {
        String typeValue = (String) dbObject.get("type");

        try {
            ContentType actualType = ContentType.valueOf(typeValue);
            if (actualType == ContentType.text) {
                return new TextBlock();
            } else if (actualType == ContentType.image) {
                return new Picture();
            } else if (actualType == ContentType.video) {
                return new Video();
            } else {
                throw new MappingException("Can't mapping dbObject to specific entity by type filed:" + typeValue);
            }
        } catch (MappingException ex) {
            throw ex;
        } catch (Exception ex) {
            throw new MappingException("Can't mapping dbObject to specific entity by type filed:" + typeValue, ex);
        }
    }

}
```
I modify Morphia source code to using the custom annotation **StaticFactoryMethod** to tell Morphia when mapping a doc to ContentSection it uses the **ContentSection.newInstanceByType** to create a corresponding entity.

**Comment by evanchooly** [comment]
I can't tell if this is a question or bug report.  But if you want to customize object create you can use `org.mongodb.morphia.ObjectFactory` and set it using org.mongodb.morphia.mapping.MapperOptions#setObjectFactory`.  Otherwise, issues #721 and #22 mostly cover the idea of a custom discriminator fields. 

If you have any further questions, please don't hesitate to post to the [mailing list](https://groups.google.com/forum/#!forum/morphia).
