### ISSUE TITLE
How to use with mongo-java-driver-reactivestreams

### ISSUE THREAD

**Issue by frapontillo** [mongodb/morphia#871]
Hello, I am trying to use Morphia (latest 1.0.1) as the converter level for [`mongo-driver-reactivestreams`](https://github.com/mongodb/mongo-java-driver-reactivestreams) (latest 1.2.0-rc0), but I am stuck as Morphia expects `com.mongodb.DBObject`, which is basically a wrapped `Map`, while `mongo-driver-reactivestreams` needs `org.bson.Document`, which is again another wrapped `Map`.

My current half-solution is to convert the `Document` in a `DBObject` and pass it to Morphia:
```
Set<Map.Entry<String, Object>> entrySet = document.entrySet();
LinkedHashMap map = new LinkedHashMap<String, Object>(entrySet.size());
entrySet.forEach(e -> map.put(e.getKey(), e.getValue()));
DBObject dbObject = new BasicDBObject(map);
morphia.fromDBObject(MyClass.class, dbObject);
```

Sadly, this only works for documents without embedded objects, as the embedded objects will be `Document`s and not `DBObject`s. I could set up a recursive conversion from `Document` to `DBObject`, but I'm not sure if that's the only/best way possible or if there is another solution I haven't thought of.

Thanks.

**Comment by evanchooly** [comment]
Unfortunately, Morphia hasn't been migrated to the new API yet.  The [plan](#749) is to fix that soon but that work is still pending.

If you have any further questions, please post them to the [mailing list](https://groups.google.com/forum/#!forum/morphia).

**Comment by jyemin** [comment]
You can continue to use DBObject with the reactive streams driver, but it takes a bit of work.  I put up this gist to show how: https://gist.github.com/anonymous/425c3d496ddb80bf6729

**Comment by frapontillo** [comment]
@jyemin but is it possible to map those objects back to POJOs?

**Comment by jyemin** [comment]
:)
