### ISSUE TITLE
mapPackage OR map with multiple (3) databases places collections in wrong database

### ISSUE THREAD

**Issue by jgl-jll** [mongodb/morphia#874]
I'm using Spring 4.2.2.RELEASE and Morphia 1.0.1, I'm creating 3 databases each with multiple collections, the databases have the right collections but they also have collections that are not found in the the packages that are mapped:

My GenericDao looks like:

```
public GenericDaoMongo(Morphia morphia, MongoClient mongoClient, WriteConcern writeConcern, String databaseName, List<String> mappedPackages) {
        this.morphia = morphia;
        this.mongoClient = mongoClient;
        this.writeConcern = writeConcern;
        this.databaseName = databaseName;
        this.mappedPackages = mappedPackages;

        for (String mappedPackage : this.mappedPackages) {
            this.morphia.mapPackage(mappedPackage, true);
        }

        this.datastore = this.morphia.createDatastore(this.mongoClient, this.databaseName);
        this.datastore.ensureIndexes();

        log.info("GenericDaoMongo of TYPE: " + this.getClass().getName()
                + ", databaseName: " + this.databaseName
                + ", mappedPackages: " + this.mappedPackages);
    }
```

I tried using  this.morphia.map(Class.forName(mappedPackage));  and switched the "mappedPackage" config in the beans to fully qualified java class names, same problem.

SPRING BEANS:

    <bean id="mappedpackagesLogging" class="java.util.ArrayList">
        <constructor-arg>
            <list>
                <value>my.app.model.logging</value>
            </list>
        </constructor-arg>
    </bean>    

    <bean id="mappedpackagesMyAppDeviceQueue" class="java.util.ArrayList">
        <constructor-arg>
            <list>
                <value>my.app.model.queue.remotewebsrv</value>
            </list>
        </constructor-arg>
    </bean>
    
    <bean id="mappedpackagesMyApp" class="java.util.ArrayList">
        <constructor-arg>
            <list>
                <value>my.app.model.user</value>
                <value>my.app.model.catalog</value>
            </list>
        </constructor-arg>
    </bean>

    <bean id="UserDeviceLogDao" class="my.app.dao.mongodb.logging.UserDeviceLogDaoMongo">
        <constructor-arg name="morphia"         ref="morphia" />
        <constructor-arg name="mongoClient"     ref="mongoClient-myApp-logging" />
        <constructor-arg name="writeConcern"    ref="writeConcern-myApp-logging" />
        <constructor-arg name="databaseName"    value="${my.app.mongo.db.name.myApp-logging}" />
        <constructor-arg name="mappedPackages"  ref="mappedpackagesLogging"/>
    </bean>

    <bean id="DeviceMsgQueueMongoDao" class="my.app.dao.mongodb.queue.remotewebsrv.DeviceMsgQueueMongo">
        <constructor-arg name="morphia"         ref="morphia" />
        <constructor-arg name="mongoClient"     ref="mongoClient-myApp-device-msg-queue" />
        <constructor-arg name="writeConcern"    ref="writeConcern-myApp-device-msg-queue" />
        <constructor-arg name="databaseName"    value="${my.app.mongo.db.name.myApp-device-msg-queue}" />
        <constructor-arg name="mappedPackages"  ref="mappedpackagesMyAppDeviceQueue"/>
    </bean>
    
    <bean id="UserDao" class="my.app.dao.mongodb.user.UserDaoMongo">
        <constructor-arg name="morphia"         ref="morphia" />
        <constructor-arg name="mongoClient"     ref="mongoClient-myApp-base" />
        <constructor-arg name="writeConcern"    ref="writeConcern-myApp-base" />
        <constructor-arg name="databaseName"    value="${my.app.mongo.db.name.myApp}" />
        <constructor-arg name="mappedPackages"  ref="mappedpackagesMyApp"/>
    </bean>

    <bean id="mongoClient-myApp-logging" class="com.mongodb.MongoClient">
        <constructor-arg name="host" value="${my.app.mongo.db.host.jacward-logging}" />
        <constructor-arg name="port" value="${my.app.mongo.db.port.jacward-logging}" />
    </bean>

    <bean id="mongoClient-myApp-device-msg-queue" class="com.mongodb.MongoClient">
        <constructor-arg name="host" value="${my.app.mongo.db.host.jacward-queue}" />
        <constructor-arg name="port" value="${my.app.mongo.db.port.jacward-queue}" />
    </bean>

    <bean id="mongoClient-myApp-base" class="com.mongodb.MongoClient">
        <constructor-arg name="host" value="${my.app.mongo.db.host.jacward}" />
        <constructor-arg name="port" value="${my.app.mongo.db.port.jacward}" />
    </bean>
    

The database my.app.mongo.db.name.myApp and my.app.mongo.db.name.myApp-device-msg-queue are created but they have the same collections, based on the classes in their mappedPackages refs one should have 2 collections and the other 6, both have 6.

If minimize the spring beans to two databases all is well, it's the third database the causes the collections in the wrong db issue.

Any idea?

Thanks,
Jacob

**Comment by evanchooly** [comment]
This looks related to #757.  Can you try your app with 1.1.0-alpha2 verify that fix addresses your issue?

**Comment by jgl-jll** [comment]
Will do and will let you know, thanks...

**Comment by jgl-jll** [comment]
Short Answer: Using 1.1.0-alpha2 did not fix it, it made it worse and better...

Now all the database are created but only one of them doesn't have all the collections. They other collections that are not mapped are empty, so the class to collection to database mapping is correct but it creates the other collections unnecessarily. 

On Note: 1.1.0-alpha2 has a different array indexing behavior. In using 1.1.0-alpha2 I had to change about 6 test cases that were failing because of "com.mongodb.DuplicateKeyException: Write failed with error code 11000 and error message 'null'".

Apparently 1.0.1 allowed for creating empty object arrays that didn't consider more than one array element value null, null as unique.

The index that was failing is:

devices.deviceId_1_devices.userUUID_1

The full index definition is:

> db.User.getIndexes();
[
	{
		"v" : 1,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "myApp.User"
	},
	{
		"v" : 1,
		"unique" : true,
		"key" : {
			"userUUID" : 1
		},
		"name" : "userUUID_1",
		"ns" : "myApp.User"
	},
	{
		"v" : 1,
		"key" : {
			"lastName" : 1,
			"firstName" : 1
		},
		"name" : "lastName_1_firstName_1",
		"ns" : "myApp.User"
	},
	{
		"v" : 1,
		"key" : {
			"email" : 1
		},
		"name" : "email_1",
		"ns" : "myApp.User"
	},
	{
		"v" : 1,
		"key" : {
			"createdDate" : 1
		},
		"name" : "createdDate_1",
		"ns" : "myApp.User"
	},
	{
		"v" : 1,
		"unique" : true,
		"key" : {
			"devices.deviceId" : 1,
			"devices.userUUID" : 1
		},
		"name" : "devices.deviceId_1_devices.userUUID_1",
		"ns" : "myApp.User"
	},
	{
		"v" : 1,
		"key" : {
			"devices.manufacturer" : 1,
			"devices.make" : 1,
			"devices.model" : 1,
			"devices.softwareVersion" : 1
		},
		"name" : "devices.manufacturer_1_devices.make_1_devices.model_1_devices.softwareVersion_1",
		"ns" : "myApp.User"
	},
	{
		"v" : 1,
		"key" : {
			"devices.msgRegistrationToken" : 1
		},
		"name" : "devices.msgRegistrationToken_1",
		"ns" : "myApp.User"
	},
	{
		"v" : 1,
		"key" : {
			"devices.thirdPartyMsgUUID" : 1
			},
		"name" : "devices.thirdPartyMsgUUID_1",
		"ns" : "myApp.User"
	}
]

**Comment by evanchooly** [comment]
If you have indexes defined on your entities, collections *will* be created in each database because the indexes need to live on something.  Do you see data going to the correct databases or do you see cross-contamination across databases.

I'm not sure what you mean about empty object arrays.  Can you post an example?

**Comment by jgl-jll** [comment]
Thanks for your time on this!

It makes sense about the indexes needing to live somewhere however based on my spring configuration certain collections should only live in certain database, not all of them, this is the bug.

I, for example have a employee DB that should Only have employee and dept collections.

I also, for example, have a logging DB that should only have the employeeLog collection.

And finally a third DB called configs that should only have the empConfig collection.

If I configure 2 of the databases, in my spring config, employee and logging, no problem, I get:

employee:
   - employee
   - dept

logging:
   - employeeLog

However if I add the configuration for the 3rd DB I get (or a 4th DB):

employee:
   - employee
   - dept 
    - empConfig (never has data)

logging:
   - employeeLogRec

configs:
   - employee (never has data)
   - dept (never has data)
    - empConfig 


Empty object array: 

Sorry for not being clearer, also because the this is a different issues, out of going from 1.0.1 to alpha2, I should probably create a new issue but here goes:

My collection defines an object array called devices, sometimes I have the data for the array and sometime I don't.

The @embedded device array has a unique index on userUUID and deviceUUID, as in:

{
email:"EMAIL",
name:"NAME"
}

{
email:"EMAIL 1",
name:"NAME 2",
devices: [ {
                 userUUID:"UUID",
                 deviceUUID: "deviceUUID"
               }  ]
}

Duplicate key error on insert on device_userUUID_device_deviceUUID when I insert this 3rd record.

{
email:"EMAIL 2",
name:"NAME 2"
}

When I try to insert the 3rd record with alpha2 I get a duplicate key error on unique index device_userUUID_device_deviceUUID BUT I do not with 1.0.1.

Thanks!

**Comment by evanchooly** [comment]
If you use the same `Mapper` for multiple `Datastore`s you're going to index information and thus collections for everything.  If you need only certain collections and entities in a given database, you'll need to use a different `Mapper` for each subset of collections/entities you want in each `Datastore`.

As for the object array error, the duplicate key error comes from mongodb.  I'm not sure that's a morphia issue as such.  If you could post a test case to the [mailing list](https://groups.google.com/forum/#!forum/morphia) we can dig in to it.

**Comment by jgl-jll** [comment]
Thanks so much, using a different Mapper (Spring scope=prototype), worked!

I'll work on a mini test case, for the Mongo DB index issue, thx

**Comment by evanchooly** [comment]
Can I close this issue then?

**Comment by jgl-jll** [comment]
closed
