### ISSUE TITLE
Filter with empty list as $in parameter don't work

### ISSUE THREAD

**Issue by granchi** [mongodb/morphia#875]
Filter with empty list as $in parameter generate "$in null" condition and query fails:

    query.filter("company in", new ArrayList());

The query works after conversion in array:

    query.filter("company in", new ArrayList().toArray());

**Comment by evanchooly** [comment]
I just tried on master and couldn't recreate this:

>         q.criteria("refs").in(new ArrayList<ObjectId>());
>         System.out.println("************ q = " + q);

gives me:

>  ************ q = { "refs" : { "$in" : [ ]}}

Make sure you're on the latest version (1.0.1).  If that doesn't work, try again with 1.1.0-alpha2 and see if that doesn't resolve it for you.  If it's still failing, please post a test case to the [mailing list](https://groups.google.com/forum/#!forum/morphia) and we can take it from there.
