### ISSUE TITLE
QueryValidator canQueryPast NPE

### ISSUE THREAD

**Issue by agiannone** [mongodb/morphia#881]
The QueryValidator validateQuery() method calls the canQueryPast() method, but at this stage the mf variable can be equal to null. This causes the canQueryPast() method to throw an exception. A null check should be added to the canQueryPast() method.

To recreate this you need a nested interface:

public interface Nested {}

public class NestedImplA implements Nested {
private String field;
}

public class WithNested {
private Nested nested;
}

When we query WithNested using: nested.field and disable validation, we end up getting an NPE because the MappedField will be null.

This is stopping any query which uses a field nested in an interface implementation.

**Comment by evanchooly** [comment]
this sounds like a refinement of the problem we've been discussing in #777, yes?  or is this a new one?

**Comment by agiannone** [comment]
This is a new one, although the root cause of both bugs seems to be querying or indexing on a field nested in an interface (or better, nested in a class which implements the interface).

In both cases the code trys to get the MappedField for the actual interface implementation which isn't available and that causes the problems.

How long do you recon before this could be fixed? 

I ask because our product stopped working after the update done a few days ago. The only alternative I see is reverting back to 1.0.1 but I remember migrating off that because of a problem.

**Comment by evanchooly** [comment]
I'll take a look now at the test case.  I have a feeling I know where/what the issue is and then take it from there.

**Comment by agiannone** [comment]
I think I found what changed and started causing this bug... in r1.1.0-alpha1 on line 49 we have:

if (validateNames) {

In r1.1.0 this is missing and that's causing the exception to be raised.

**Comment by evanchooly** [comment]
I can't recreate your error on `master` using this test:

```java
    @Test
    public void testNestedInterfaces() {
        getMorphia().map(WithNested.class);
        WithNested nested = new WithNested();
        nested.nested = new NestedImpl("nested value");
        getDs().save(nested);

        final WithNested found;
        try {
            getDs().createQuery(WithNested.class)
                                            .field("nested.field").equal("nested value")
                                            .get();
            Assert.fail("Querying against an interface should fail validation");
        } catch (Exception ignore) {
            // all good
        }
        found = getDs().createQuery(WithNested.class)
                                        .disableValidation()
                                        .field("nested.field").equal("nested value")
                                        .get();
        Assert.assertNotNull(found);
        Assert.assertEquals(nested, found);
    }
```

What am I missing?

**Comment by agiannone** [comment]
Ok, I'm investigating this a little further to see if I can recreate an independent test.

I am looking at the MappedClass which is causing problems and specifically on the field we have nested in the class which contains an interface. Below is the output of the MappedField toString method:

attrs ( type:RewardAttributesDTO, single:true); {interface org.mongodb.morphia.annotations.Embedded=@org.mongodb.morphia.annotations.Embedded(value=., concreteClass=class java.lang.Object)}, 

As you can see, for some reason the value of Embedded is "."

Any ideas why this might be happening?

**Comment by agiannone** [comment]
Ignore the previous question... that's the IGNORED_FIELDNAME

**Comment by agiannone** [comment]
Ok, I've found the issue. If you modify the following line in the test case:
```
found = getDs().createQuery(WithNested.class)
                                        .disableValidation()
                                        .field("nested.field.fails").equal("nested value")
                                        .get();
```
You'll notice that the there is a NPE. This is because the following statement is no longer valid:
```
                if (i >= parts.length) {
                    break;
                }
```
To solve this, I made a local build which changes the following line in validateQuery():
```
if (!origProp.substring(0, 1).equals("$")) {
```
to:
```
if (validateNames && !origProp.substring(0, 1).equals("$")) {
```

**Comment by agiannone** [comment]
If you add the following line to the WithNested class:

```
@Indexes({
	@Index( fields={ @Field("nested.field.fail") },
			options = @IndexOptions( disableValidation = true, sparse = true ) )
})
```
Then call ensureIndexes() on the class, you will get the error from issue: #777

**Comment by mthomas87** [comment]
So happy that I finally found this issue. Same NPE on our project.

    Caused by: java.lang.NullPointerException: null
    at org.mongodb.morphia.query.QueryValidator.canQueryPast(QueryValidator.java:135) ~    [morphia-1.1.0-SNAPSHOT.jar:na]
    at org.mongodb.morphia.query.QueryValidator.validateQuery(QueryValidator.java:91) ~[morphia-1.1.0-SNAPSHOT.jar:na]
    at org.mongodb.morphia.query.FieldCriteria.<init>(FieldCriteria.java:40) ~[morphia-1.1.0-SNAPSHOT.jar:na]
    at org.mongodb.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:288) ~[morphia-1.1.0-SNAPSHOT.jar:na]
    at org.mongodb.morphia.query.FieldEndImpl.hasThisOne(FieldEndImpl.java:145) ~[morphia-1.1.0-SNAPSHOT.jar:na]
    at org.mongodb.morphia.query.FieldEndImpl.hasThisOne(FieldEndImpl.java:25) ~[morphia-1.1.0-SNAPSHOT.jar:na]</code>

Code looks like this, crashes on last line here:

    Query<Editorial> query = this.dao.newQuery();
    query.disableValidation();
    query.criteria("data.type").equal("gallery");
    query.criteria("data.data.id").hasThisOne(galleryId);

Really looking forward to have this fixed. :+1:  :

**Comment by evanchooly** [comment]
I think i have it.  Your suggested fix breaks another case but I think I have it tweaked properly enough to work in both cases.  Hopefully a snapshot build later this afternoon to try.

**Comment by evanchooly** [comment]
The new -SNAPSHOT build is [up](https://oss.sonatype.org/content/repositories/snapshots/org/mongodb/morphia/morphia/1.2.0-SNAPSHOT/) if you'd like to give it a try.  The test case above and the one listed in #777 both pass now.

**Comment by agiannone** [comment]
Two birds, one stone. That resolved both issues =)
