### ISSUE TITLE
$in with empty collection as argument results in MongoQueryException (version 1.0.1)

### ISSUE THREAD

**Issue by robbypelssers** [mongodb/morphia#882]
When running following query

                final Query<GridEventActive> query = getDataStoreWithMorphia()
                        .find(GridEventActive.class)
                        .field("eventId")
                        .in(event.getRelatedEvents());
where event.getRelatedEvents() is an empty HashSet 
the Mapper tries to find a suitable converter and encode this argument.  I noticed this resulted in using the IterableConverter, which ends up returning null in its final statement.

return !values.isEmpty() || getMapper().getOptions().isStoreEmpties() ? values : null; 

com.mongodb.MongoQueryException: Query failed with error code 17287 and error message 'Can't canonicalize query: BadValue $in needs an array' on server

**Comment by chaseberry** [comment]
Seconded. Using $in with an [] is a valid Mongo Query. Not sure why [] is turned into $null.
I've had to add a bunch of if(collection.isEmpty()){ return default }

**Comment by evanchooly** [comment]
I'm having trouble recreating this one:  

```java
        getMorphia().getMapper().getOptions().setStoreEmpties(false);
        final Query<Photo> query = getDs()
                           .find(Photo.class)
                           .field("keywords")
                           .in(new ArrayList<String>());
        System.out.println("************ query = " + query);
```

`************ query = { "keywords" : { "$in" : [ ]}}`

What am I missing?  i tried passing in an empty `HashSet`, too.

**Comment by evanchooly** [comment]
I can't seem recreate this so I'm closing for now.  If we get a test case recreating the issue, we can reopen this.
