### ISSUE TITLE
UpdateOperations should increment the version on @Versioned entities

### ISSUE THREAD

**Issue by evanchooly** [mongodb/morphia#886]
`update(T ent, UpdateOperations<T> ops)` apparently creates an update like this `update somedb.SomeCollection query: { _id: "56ab365453faef0207a300c9", version: 2 } update: { $set: { someField: "1234" } }`.  The version should have a `$inc` as well.

**Comment by dklotz** [comment]
The version update is there (I just posted an edited log the google group), just as part of the $set, not an $inc, so I think this is not an issue. Here's the complete line from the db log file:
`Fri Jan 29 09:55:43.564 [conn12] update user_data.SomeAccount query: { _id: "55fb364452faff0007a210e7", version: 2 } update: { $unset: { statusMessage: 1 }, $set: { problem: "NO_PROBLEM", lastSynchronized: new Date(1454061343504), nextSync: new Date(1454061652558), modified: new Date(1454061343561), version: 3 } } idhack:1 nupdated:0 keyUpdates:0 locks(micros) r:215 0ms`

**Comment by evanchooly** [comment]
Ah, ok.  Great.  I was pretty sure we had tests to make sure that was happening.  Thanks for the update.

**Comment by dklotz** [comment]
I would close this issue, If I could, but since I didn't create it, I can't... :)
