### ISSUE TITLE
New constructor for DatastoreImpl to take DB object directly

### ISSUE THREAD

**Issue by rednuht** [mongodb/morphia#890]
I'm in a situation where I don't have access to the MongoClient object, all that I get is the DB object. Looking at the DatastoreImpl class it seems the only time the client is used is in the copy method.

Would be great if there was another constructor where I could supply the DB object directly. Don't know the impact of breaking the copy method though... otherwise I would do a pull request for this myself.

**Comment by evanchooly** [comment]
That seems reasonably simple to add.
