### ISSUE TITLE
No usable constructor for java.time.Period (or LocalDateTime)

### ISSUE THREAD

**Issue by jvence** [mongodb/morphia#894]
I'm trying to load an instance of a class that contains a Period and keep getting "org.mongodb.morphia.mapping.MappingException: No usable constructor for java.time.Period"

I know that this is probably caused by the fact that Period doesn't have an empty constructor but given that it's a standard datatype in Java 8, I'm assuming that is should work. Same issue for LocalDateTime.
Tried using @Embedded on the instance declaration to no avail.

I am using 1.2.0-SNAPSHOT.

Any workaround for this?

**Comment by jvence** [comment]
Also seems that there's no support for java.math.BigDecimal.  Do we really need to write all these converters for standard Java 8 data types?

**Comment by evanchooly** [comment]
The converter for BigDecimal is not as simple as it would sound.  See #411 for a discussion.  Given that morphia is bound to 1.6 (not my decision) we can't ship converters for java 8 types as part of the core.  I'm exploring creating a new `java8` module that would help fill that gap, though.

**Comment by andrea-bologna** [comment]
Hi all,
do you have any built-in parser for LocalDateTime? It can be serialized by Morphia but not loaded from MongoDB. Thanks

**Comment by cleciusjm** [comment]
Hi all,
Do you want to create a support project for Java8 Date Time converters, as
optional library in the official repository.
If this project is created I can contribute to implement some converters.
The only problem is about the automation of converter registration to it
can be more transparentin the datastore creation, something like the CDI
bean or FacesConverter

Em sáb, 12 de mar de 2016 às 08:09, andrea-bologna <notifications@github.com>
escreveu:

**Comment by evanchooly** [comment]
depends on #940

**Comment by evanchooly** [comment]
closing this since this is tracked by #940
