### ISSUE TITLE
Group by Month, Day, and Year - AggregationPipelineImpl

### ISSUE THREAD

**Issue by ruedigerpape** [mongodb/morphia#896]
Hey guys,

I tried to use the Morphia Aggregation for Group by Month, Day, and Year. With the current Implementation it is not possible.

See: [https://docs.mongodb.org/manual/reference/operator/aggregation/group/ ](url) --> Group by Month, Day, and Year

Please enhance the function:

`    public AggregationPipeline group(final List<Group> id, final Group... groupings) {
`

like this:

...
`for (Group group : id) {` 
   &#160;&#160;&#160;&#160; `if(group.getAccumulator() != null) {`
       &#160;&#160;&#160;&#160; &#160;&#160;&#160;&#160;`idGroup.put(group.getName(), new BasicDBObject(group.getAccumulator().getOperation(), group.getAccumulator().getField()));`
       &#160;&#160;&#160;&#160;     ` } else {`
 &#160;&#160;&#160;&#160; &#160;&#160;&#160;&#160;`idGroup.put(group.getName(), group.getSourceField());`
    &#160;&#160;&#160;&#160;         `}`
            
`}`
...

Example:

`Iterator<AggregateMonthBasedResult> iterator = pipeline.match(query).group`
 &#160;&#160;&#160;&#160;`(` 
                  &#160;&#160;&#160;&#160; &#160;&#160;&#160;&#160;  `id(` 
                  &#160;&#160;&#160;&#160; &#160;&#160;&#160;&#160;       `grouping("month", new Accumulator("$month", "date")) , `
                &#160;&#160;&#160;&#160; &#160;&#160;&#160;&#160;         `grouping("year", new Accumulator("$year", "date"))`
              &#160;&#160;&#160;&#160; &#160;&#160;&#160;&#160;       `),`
              &#160;&#160;&#160;&#160; &#160;&#160;&#160;&#160;       `grouping("count", new Accumulator("$sum", 1)) `
                    
 &#160;&#160;&#160;&#160;` ).aggregate(AggregateMonthBasedResult.class);`
`
Creates correct native query:

`{`
               &#160;&#160;`"$group" : { `
		        	&#160;&#160;&#160;&#160;`"_id" : { "month" : { "$month" : "$date"} , "year" : { "$year" : "$date"}} , `
		        	&#160;&#160;&#160;&#160;`"count" : { "$sum" : 1}`
		        &#160;&#160;`}`
             
`}`     

Best,
Rüdiger

**Comment by 0xNacho** [comment]
same bug for me. The above expression always return `null` month:
`grouping("month", new Accumulator("$month", "date")) 
`

**Comment by devylon** [comment]
The bug also exists for me

**Comment by 0xNacho** [comment]
Does someone know where is the bugged code? @devylon @ruedigerpape

**Comment by ruedigerpape** [comment]
Yes I know. The code must be enhanced. See my post.
