### ISSUE TITLE
mapPackage() does not work with subpackages

### ISSUE THREAD

**Issue by UlrichCech** [mongodb/morphia#898]
Hi all,

I don't want to map every single Entity-class only to have the indexes created correctly (at the moment, if you don't map a class explicitly, the application works, but no index is created other then the index on "_id").
What I want to have is the folloing:
```
morphia.getMapper().getOptions().setMapSubPackages(true);
morphia.mapPackage("<basicPackageName>", true);
```

I think, that the method "ReflectionUtils.isSubPackage()" has a problem, because the comparison would work, but currently, there is added a period to the parentPackgeName, so the equals()-method will fail (without the period, everything would work fine)...

Or do I oversee something here?

Thanks in advance,
Ulrich

**Comment by evanchooly** [comment]
Are you saying the subpackages aren't getting mapped properly?  The tests are all green at the moment.

**Comment by UlrichCech** [comment]
< The tests are all green at the moment>
:-) Yes, because the test does not check for a class in a subpackage. The resulting set only contains classes from the parent "org.junit".
For example: org/junit/rules  results in "false" in the method "isSubPackage()" with "org/junit" as parent, but you see, that it should result in "true".
```
private static boolean isSubPackage(final String fullPackageName, final String parentPackageName) {
        return fullPackageName.startsWith(parentPackageName + ".");
}
```
The period at the end breaks the "startWith()".

**Comment by evanchooly** [comment]
Got it.  I'll take another look at the test then.  Thanks.

**Comment by UlrichCech** [comment]
I provided a pull-request for this issue. Perhaps, you can take a look at that.

**Comment by evanchooly** [comment]
Looks good.  Thanks for the patch.

fixed  https://github.com/mongodb/morphia/commit/04c9a0ca8227eb101e955755ba744d89c2f3206c
