### ISSUE TITLE
Useless null check or missing clone() in QueryImpl#getSortObject

### ISSUE THREAD

**Issue by vcque** [mongodb/morphia#900]
Hi,

QueryImpl#getSortObject does a strange null check :
```java
    @Override
    public DBObject getSortObject() {
        return (sort == null) ? null : sort;
    }
```
Looking at the code around, it seems that it was meant as `(sort == null) ? null : sort.clone()` but changing it might now break userspace code ?

Thanks for your work

**Comment by evanchooly** [comment]
That looks like it intended to be a defensive copy but only went halfway.  Should be safe to clean up.
