### ISSUE TITLE
upsert improvment

### ISSUE THREAD

**Issue by mlkmhd** [mongodb/morphia#912]
I want to upsert a document that has changed its properties.
probably have to add a method like this: `findAndModify(Query<T> paramQuery, T dirtyObject)` to get all properties of dirtyObject and create a `UpdateOperations` inside it and set all properties.

now I have to call `UpdateOperations.set('p', T.getP())` for each property of generic T

thank you

**Comment by evanchooly** [comment]
I feel like the question's missing here.  Can you post to the [mailing list](https://groups.google.com/forum/#!forum/morphia) with your question and any details?
