### ISSUE TITLE
QueryValidator bypass the validateName(disableValidation) check

### ISSUE THREAD

**Issue by bgkian** [mongodb/morphia#914]
Morphia 1.1.1 throwing ValidationException(The field '%s' could not be found in '%s') at QueryValidator line 99 if query filter consist of array element index such as user.0.itemid.

**Comment by evanchooly** [comment]
can you check the test I just added and linked above?  This test seems to indicate everything is working as expected.  If my test doesn't accurately recreate your issue, I'd really appreciate a test case from you that does so i can get this fixed for you.  Thanks.

**Comment by evanchooly** [comment]
There's been no response so I'm considering this bug fixed.  Please file a new issue if something else comes up.
