### ISSUE TITLE
morphia MappingException: Error setting value from converter (IdentityConverter)

### ISSUE THREAD

**Issue by nagapavan** [mongodb/morphia#915]
Due to issues observed with bulk-write, I am trying to upgrade Morphia jar of my project.

From Morphia 0.99 to 1.1.1. After update I am having problem while reading Embedded class objects, which implemented Iterable.

Following is the error I am seeing while reading, persisted record:

> java.lang.RuntimeException: org.mongodb.morphia.mapping.MappingException: Error setting value from converter (IdentityConverter)

I am using Mongo 2.7.3, I can not do an upgrade at the moment.

**Comment by evanchooly** [comment]
Can you post a test case and we can take a look?

And by Mongo 2.7.3 you mean of the server?  or the driver?

**Comment by nagapavan** [comment]
Sorry for the late reply. It's Mongo 2.7.3 server.
I have solved my issue by keeping Morphia 0.99. Closing this issue.
