### ISSUE TITLE
Could morphia support allowDiskUse?

### ISSUE THREAD

**Issue by IVANOPT** [mongodb/morphia#917]
In our development with morphia, we met the following errors:

> MongoDB : Sort exceeded memory limit of 104857600 bytes

According the guide: [http://www.mkyong.com/mongodb/mongodb-sort-exceeded-memory-limit-of-104857600-bytes/](http://www.mkyong.com/mongodb/mongodb-sort-exceeded-memory-limit-of-104857600-bytes/), the operation 'allow disk use' was the solution.

My questions :

> 1. If morphia supports allowDiskUse operation, if it is possible to show some sample codes?
> 2. If morphia not  #supports this operation, If it is possible to add 'allowDiskUse' from command line as configurations and all aggregations could use 'allowDiskUse' condition.

Thanks

**Comment by evanchooly** [comment]
There isn't a way to configure morphia or the driver externally like that but i'll add this to the queue for the next release.

**Comment by evanchooly** [comment]
Actually, this is [already supported](https://github.com/mongodb/morphia/blob/521bd9c90fa53e8815393a783a6c09f4e5edfc82/morphia/src/main/java/org/mongodb/morphia/aggregation/AggregationPipeline.java#L35-L35).  I *thought* seemed like an obvious thing to have missed.

**Comment by IVANOPT** [comment]
I got it, thanks.
