### ISSUE TITLE
Why not provide map package recursively?

### ISSUE THREAD

**Issue by lantaozi** [mongodb/morphia#924]
I set the  map-sub-package option as true as follows:
```        
        MapperOptions mapperOptions = new MapperOptions();
        mapperOptions.setMapSubPackages(true);
        final Morphia morphia = new Morphia(new Mapper(mapperOptions));
        morphia.mapPackage("com.package.name");
```
But it could only find classes in one package layer.
And i find the reason is the getFielNames in ReflectionUtils:
```
private static Set<String> getFileNames(final File directory, final String packageName, final boolean mapSubPackages) {
        Set<String> fileNames = new HashSet<String>();
        for (File file: directory.listFiles()) {
            if (file.isFile()) {
                fileNames.add(packageName + '.' + file.getName());
            } else if (mapSubPackages){
                fileNames.addAll(getFileNames(file, packageName + '.' + file.getName(), false));
            }
        }
        return fileNames;
    }
```
it seems a bug appeared. or for some other considerations?

**Comment by UlrichCech** [comment]
Hi Tony,

I think, you hit the following issue:
https://github.com/mongodb/morphia/issues/898

Could you test with the 1.2.0-SNAPSHOT-Version of morphia, if your 
problem still exists?



Am 20.04.16 um 12:07 schrieb Tony Yang:

**Comment by lantaozi** [comment]
Not exactly.
`
fileNames.addAll(getFileNames(file, packageName + '.' + file.getName(), false));
`
I think the 'false' should be 'mapSubPackages' instead. the recursive invocation is not exact.

**Comment by UlrichCech** [comment]
Yes, you are absolutely right, this must be 'true' instead of 'false'...at this point, mapSubPackage is always true, so you can provide 'true' here.
