### ISSUE TITLE
Why lombok is not used?

### ISSUE THREAD

**Issue by tomerghelber** [mongodb/morphia#927]
Not really an issue, but its really upsetting to write all the getters, setters and other boilers that lombok knows how to handle.
Why there is no use of it?

**Comment by evanchooly** [comment]
Are you asking why morphia isn't using lombok?  I'm not entirely sure what you're looking for.  If you can post something to the mail [mailing list](https://groups.google.com/forum/#!forum/morphia), we can try to answer you questions.
