### ISSUE TITLE
When you will update java mongo driver?

### ISSUE THREAD

**Issue by AaronLiang** [mongodb/morphia#928]
Currently, I found the newest mongo java driver version is 3.2, the driver version in morphia is 2.11, do you have any schedule to update it? And why not updating it?

**Comment by bpappin** [comment]
The version I am using says the latest is 3.0.2, but we should update to 3.2.0.

The notes say that 3.1.0 is binary compatible with 3.0.X except:
http://mongodb.github.io/mongo-java-driver/3.1/whats-new/upgrading/
Also, version 3.2.0 a major release and is binary compatible with 3.1.0. 

This looks like it may be an easy update, and be worth the effort.

**Comment by evanchooly** [comment]
You can use the newer driver just fine.  You'll just need an explicit dependency in your build file.  The build is currently using [3.0.2](https://github.com/mongodb/morphia/blob/d2e07a57df99892be5a1d400cd6a98e1c7f9a5eb/morphia/build.gradle#L14-L14).
