### ISSUE TITLE
map & mapPackage dont work

### ISSUE THREAD

**Issue by Flawd** [mongodb/morphia#929]
morphia.mapPackage("my.package.with.only.mongo.entities");
morphia.map(BlogEntry.class)
    .map(Author.class);

something like this doesn't work. map and mapPackage can both not be resolved in INtelliJ

I use import  org.mongodb.morphia.Morphia;

What can I do?

**Comment by evanchooly** [comment]
It sounds like a misconfiguration of your project.  If you're still having this problem, please post the to the [mailing list](https://groups.google.com/forum/#!forum/morphia) with more details and we'll try to get you sorted.
