### ISSUE TITLE
Morphia Aggregation Pipeline always returns the same data

### ISSUE THREAD

**Issue by Faliorn** [mongodb/morphia#932]
Hi! I've put a question at StackOverflow, but I think it might be an issue. To avoid copy/pasting it, here is the link:

[http://stackoverflow.com/questions/37123794/morphia-aggregation-pipeline-always-returns-the-same-data](http://stackoverflow.com/questions/37123794/morphia-aggregation-pipeline-always-returns-the-same-data)

Debugging, I found out that my problem was the cache used internally in MorphiaIterator. Although every iteration should return different items, since the ID of the main item is the same, it returns always the same item from the internal cache.

The point is in fromDb method in Mapper class. It uses the cache from the iterator. Debugging in the processItem method shows that in:

`final V item = convertItem(dbObj);`

The final item is different from the dbObj, (dbObj content is right).

I think that it should be possible to either clear the cache in between iterations of the loop (worst solution in my oppinion), or to be able to tell the Pipeline not to use the cache to build the items.

Best regards

**Comment by evanchooly** [comment]
You're running in to this issue: #854.   You'll need to suppress the _id fields.

**Comment by Faliorn** [comment]
But I also need the "_id" field in my case...

**Comment by evanchooly** [comment]
I'm afraid the two requirements are contradictory.   You might try projecting the `_id` field to `id` so that subsequent documents aren't conflated unnecessarily.  But by unwinding you're creating multiple docs with duplicate IDs which doesn't work for a number of reasons.
