### ISSUE TITLE
Documentation of query building is incomplete: Criteria needed for *and* and similar operators

### ISSUE THREAD

**Issue by BairDev** [mongodb/morphia#933]
* Morphia Version. 1.1.1
* JDK: 1.8
* Mongo: 3.0.x

The current [documentation of complex queries](http://mongodb.github.io/morphia/1.1/guides/querying/#complex-queries:50d269286defa89dcc6793dab2a5c4d0) is not correct.

This code

```
q.and(
    q.criteria("width").equal(10),
    q.criteria("height").equal(1)
);
```
Won't be accepted by the compiler, because `equal()` returns an Object, not a **Criteria**.
A very stupid solution was this.

```
Datastore ds = this.getValidDatastore(); //pseudocode
Query myQuery = ds.createQuery(MyEntity.class);
myQuery.and(
    (Criteria) myQuery.criteria(MyEntity.GREAT_FIELD).exists(),
    (Criteria) myQuery.criteria(MyEntity.GREAT_FIELD).hasAnyOf(myList)); // myList is present
List<MyEntity> myEntities = myQuery.asList();
```

Now the query looks good and the result is OK. But either the documentation is not complete, or `and()` does not work as expected.

**Comment by evanchooly** [comment]
Are you sure about that?  I just tried it and it worked just fine.  `equal()` actually returns a `T` so this example compiles just fine.

**Comment by BairDev** [comment]
Mhm, quite sure.
This is what Eclipse is saying: `The method and(Criteria...) in the type Query is not applicable for the arguments (Object)`

Probably I'm doing smth wrong. Code:

```
myQuery.and(
    myQuery.criteria("myField").equal("myValue"));
```

I let this run:

```
! java.lang.Error: Unresolved compilation problem: 
! The method and(Criteria...) in the type Query is not applicable for the arguments (Object)
! [...]
 ```

But you're right

```
@Override
public T equal(final Object val) {
    return addCriteria(FilterOperator.EQUAL, val);
}
```

Our service is Dropwizard based. From our pom.xml:

```
<dropwizard.version>0.9.2</dropwizard.version> 
<morphia.version>1.1.1</morphia.version>
<mongo.java.driver.version>3.2.2</mongo.java.driver.version>
```

**Comment by evanchooly** [comment]
Can you post that entire method?  It looks like maybe `myQuery` is declared oddly and you're losing type information.  If you take a look at `org.mongodb.morphia.TestQuery#testCombinationQuery` you can see a working instance of using `and()`.

**Comment by BairDev** [comment]
Uuh, you are right again. This was the solution:

```
Query<MyEntity> tagsQuery = ds.createQuery(MyEntity.class);
```

--> no warnings, no exceptions

**Comment by evanchooly** [comment]
Excellent!  Glad you're moving again.
