### ISSUE TITLE
Datastore.save does not return

### ISSUE THREAD

**Issue by roberterdin** [mongodb/morphia#934]
Morphia version: 1.1.1
JDK version: Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Mongo version: 3.0.12

I have an issue where Datastore.save does not return for a certain object. Other, similar objects work perfectly fine.

There is no exception and nothing in the mongo logs. These are the last few corresponding lines from `/var/log/mongodb/mongod.log`
```
2016-05-12T16:09:57.280+0200 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:42429 #1 (1 connection now open)
2016-05-12T16:09:58.081+0200 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:42431 #2 (2 connections now open)
2016-05-12T16:09:58.104+0200 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:42432 #3 (3 connections now open)
2016-05-12T16:13:32.885+0200 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:42457 #4 (4 connections now open)
```

And this is the only corresponding log message of the application using morphia

```
[pool-1-thread-1] DEBUG org.mongodb.driver.protocol.insert - Inserting 1 documents into namespace dbname.statistics on connection [connectionId{localValue:2, serverValue:4}] to server localhost:27017
```

The class looks as follows
```java
@Entity("statistics")
public class Statistics {

    @Id
    private ObjectId id;

    private int intA = 0;
    private int intB = 0;
    private int intC = 0;

    private Map<String, Integer> mapA = new HashMap<>(); //4751 entries in one case that fails
    private Map<String, Integer> mapB = new HashMap<>();

}
```

As I said, the bug only happens with certain objects of this class. Most work just fine. I figured out the following as well. It has to do with the map.
```java
Statistics stats = new Statistics();
// ... stats is filled with data

ds.save(stats) // hangs

stats.mapA.clear()
ds.save(stats) // works  fine
```

This led me to the conclusion that there might be something in a string of the map that is not properly escaped or something. However, saving all content of the `stats.mapA` in seperate documents, e.g. with a test class works flawless.
```java
@Entity("dbtest")
public class DbTest {
    @Id
    private ObjectId id;

    private String word;
}

stats.mapA.entrySet().forEach((entry) -> {
    ds.save(new DbTest(entry.getKey()));
});
// no problem
```

I'm a bit lost here with neither an exception nor something in a log file. I'm happy to do the debugging but some ideas where to start would be greatly appreciated.

**Comment by roberterdin** [comment]
I found the error. There was a leading `$` sign in the key of the map. And since maps are treated like objects where the key is the field name this broke something. It is, however, very bad behavior to just fail, without anything that might give you a hint on what's wrong. This should throw an exception.

**Comment by evanchooly** [comment]
Can you post a test case to recreate it?  It *might* be a morphia or it might be a driver.  It could also be a "well, don't do that" but I'd like to see how you're getting there so I know if/where there's work to be done.

**Comment by roberterdin** [comment]
If I try to reproduce it standalone I get `java.lang.IllegalArgumentException: Invalid BSON field name` as you would expect. It has to be a logging issue. Ironically I do get the annoying cluster messages but not the exception. Will close this one and open another if I can't sort it out.

**Comment by evanchooly** [comment]
Sounds good.  Thanks.
