### ISSUE TITLE
Map key with dots gets converted to an object

### ISSUE THREAD

**Issue by agiannone** [mongodb/morphia#939]
When I have a Map field like so:

Map<String, Integer> counter;

And I use a value such as a URL for the key, it actually converts the value to an object in MongoDB.
So let's say I use http://subdomain.mysite.com as a key and 1 as a value I would expect it to store this in the following way in MongoDB:

{ "http://subdomain.mysite.com": 1 }

Instead what I get is:

{ "http://subdomain": { "mysite" : { "com" : 1 } } }

This obviously then breaks our code when we try to read the value back from the DB. 

I know MongoDB doesn't allow dots or dollar symbol as a key value but having an error or warning return would be better than simply converting it into an object.

**Comment by evanchooly** [comment]
At the moment, Morphia doesn't support dotted names in keys.  The C# driver has a [feature](http://mongodb.github.io/mongo-csharp-driver/2.2/reference/bson/mapping/#dictionary-serialization-options) to customize dictionary serialization for cases like.  Morphia doesn't currently support this though it's on the road map.  (This feature was pointed out to me only last week.)  In the meantime, you can write a @PreSave/@PreLoad to serialize your Maps in to a form like [ { key : "http://subdomain.mysite.com", value: 1 } ] and back.  It's not ideal but should get you going until this option can be baked in.

**Comment by UlrichCech** [comment]
Which version of Morphia do you use?
With 1.2.0-SNAPSHOT, when I have the following "map" in my Entity...
```
Map<String, String> map = new HashMap<String, String>();
map.put("a.b", "a");
map.put("b.c.d", "b");
```
... and try to save it through datastore, I get:
`java.lang.IllegalArgumentException: Invalid BSON field name a.b`

**Comment by evanchooly** [comment]
I'm on `master` since I'm developing Morphia itself.  But as I said, dotted names are not allowed.

**Comment by UlrichCech** [comment]
Sorry, Evan, my post was for "agiannone", who already mentioned, that dotted names are not allowed from MongoDB as key name, but he wanted an Exception rather than converting to an object.
And like I mentioned in the post, in 1.2.0-SNAPSHOT, there is already that exception.

**Comment by evanchooly** [comment]
ha.  my bad.  carry on.

**Comment by agiannone** [comment]
@UlrichCech - Thanks! You pointed me in the right direction, it was an issue with our mapper which generates the update queries for maps!
@evanchooly - My bad
