### ISSUE TITLE
Query with disable validation fails with embedded keys

### ISSUE THREAD

**Issue by nitinkcv** [mongodb/morphia#941]
I have a class annotated with @Entity and while querying i disable validation using `getDs().createQuery(collectionName, ResourceEntity.class).disableValidation()`. When i construct my query (with either filter or field method) for simple keys the query works fine. 

However when i construct the query for embedded keys (for e.g. `query.field('foo.bar').equal('value')` morphia throws an exception @ [https://github.com/mongodb/morphia/blob/master/morphia/src/main/java/org/mongodb/morphia/query/QueryValidator.java#L99](url).

I haven't gone through the logic in details but i guess if the disableValidation is enabled, then we should break out from validateQuery early on. This looks to be a bug as the [documentation](https://github.com/mongodb/morphia/wiki/Query#disabling-validation) seems to suggest implicitly it should work for both simple and embedded keys.

**Comment by evanchooly** [comment]
This seems to work for me.  Can you check the linked test case and see what I'm missing?

**Comment by evanchooly** [comment]
between the test working and #961 this should be resolved.  If you're still running in to this, please reopen this one or a new one with the details.
