### ISSUE TITLE
Scala support

### ISSUE THREAD

**Issue by gabfssilva** [mongodb/morphia#949]
I'm wondering if you guys planned on creating a Scala version of Morphia. Also, I want to ask if it would be easy to create a wrapper (just like casbah). I'm planning on doing it myself, but, depending on how Morphia is implemented it could not be that easy to just wrap on a scala interface, so, I just want to know before starting to do it.

Thanks!

**Comment by evanchooly** [comment]
We don't have any such plans, no.  With changes i'm working on in the driver itself, you could probably get by with just the Scala driver and the 3.4+ Java driver.  (Depending on when these updates I'm working on hit the Java driver.)  If that's not sufficient, I'd be happy to discuss details on the [mailing list](https://groups.google.com/forum/#!forum/morphia)
