### ISSUE TITLE
Add group by id null

### ISSUE THREAD

**Issue by MiguelAngelLV** [mongodb/morphia#951]
Sometimes I need group by "all elements", so I use null as ID, but Morphia don't have this options, it allways add "$" to ID, so if I do group(null, Groups...), it transform null to "$null"

**Comment by cleciusjm** [comment]
I've the same problem, to solve I do something like this:  
this.createAggregation().group(Collections.emptyList(),
Group.grouping("maxNumber",
Group.max("key.number"))).aggregate(MaxKeyResult.class);

  

But with null key really not work

  
Clécius J. Martinkoski

Arquiteto de Softwares Java/JEE/Android

(42) 9999-5400

  

![](https://link.nylas.com/open/cgc39v5sy7kixa1hq44h9y6rb/local-4dc72aec-
51a3?r=cmVwbHkrMDAzNWVmNjI2MTZjOGY4NzY0NDAzN2M0NmU3NTcyYzA0YjhiYjg2NDFmYjkwNjJmOTJjZjAwMDAwMDAxMTM3YjlmM2Y5MmExNjljZTA5OTZhMjI4QHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 17 2016, at 8:21 am, Miguel Ángel López Vicente
&lt;notifications@github.com&gt; wrote:  

> Sometimes I need group by "all elements", so I use null as ID, but Morphia
don't have this options, it allways add "$" to ID, so if I do group(null,
Groups...), it transform null to "$null"

>

> —  
> You are receiving this because you are subscribed to this thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/mongodb/morphia/issues/951&r=cmVwbHkrMDAzNWVmNjI2MTZjOGY4NzY0NDAzN2M0NmU3NTcyYzA0YjhiYjg2NDFmYjkwNjJmOTJjZjAwMDAwMDAxMTM3YjlmM2Y5MmExNjljZTA5OTZhMjI4QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/ADXvYmCpo7EX_7ijVfqnULenk9RHLXxRks5qMoM_gaJpZM4I4RAp&r=cmVwbHkrMDAzNWVmNjI2MTZjOGY4NzY0NDAzN2M0NmU3NTcyYzA0YjhiYjg2NDFmYjkwNjJmOTJjZjAwMDAwMDAxMTM3YjlmM2Y5MmExNjljZTA5OTZhMjI4QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/ADXvYikcSsyJfRpRFQ2BdbyZqrUje8osks5qMoM_gaJpZM4I4RAp.gif)

**Comment by evanchooly** [comment]
See [here](https://github.com/mongodb/morphia/blob/02762d9c6bc33427668e201ccca3a6c918652394/morphia/src/test/java/org/mongodb/morphia/aggregation/AggregationTest.java#L70-L70) for how to do this.

**Comment by MiguelAngelLV** [comment]
Perfect :D
