### ISSUE TITLE
lazy+ignoreMissing not working

### ISSUE THREAD

**Issue by claudio-destro** [mongodb/morphia#953]
Hi guys,

I was tinkering with v1.2 (latest on mvn) but I've found a bug:

when a lazy reference has no entity associated, that's `@Reference(..., lazy = true, ignoreMissing = true)`, Morphia throws a `LazyReferenceFetchingException` instead of setting the value to null. See `org.mongodb.morphia.mapping.lazy.proxy.EntityObjectReference#fetch` method.

I think this is a bug, because when `lazy = false`, missing entities are ignored as expected.

Even if this is intentional, is there a way to get rid of it?

Thanks in advance.

Claudio

**Comment by evanchooly** [comment]
Sounds like a bug, for sure.  I'll look in to it.
