### ISSUE TITLE
Can we use Jackson for serializing/deserializing?

### ISSUE THREAD

**Issue by pavankumarjs** [mongodb/morphia#955]
I have objects of type LocalTime & LocalDate in Morphia entities. I would like to have them serialized using Jackson JavaTimeModule for better readability.

For example, I would like to serialize and store LocalTime as "09:30:00" using Jackson instead of the following way. Jackson can also parse and deserialize the formats of type "09:30:00" instead into LocalTime.

Default Morphia serialization:
`{
	"_id" : ObjectId("576d6b07505b5811f55d3ba2"),
	"className" : "models.config.Config",
	"configs" : [
		{
			"periods" : [
				[
					{
						"className" : "java.time.LocalTime",
						"hour" : 8,
						"minute" : 0,
						"second" : 0,
						"nano" : 0
					},
					{
						"className" : "java.time.LocalTime",
						"hour" : 9,
						"minute" : 0,
						"second" : 0,
						"nano" : 0
					}
				]
			],
               }
       ]
}`

**Comment by evanchooly** [comment]
Morphia and Jackson probably aren't the best combination for a number of reasons.  We are filling this gap, though.  See #940 especially the discussion linked in the comments.  As a stop gap, take a look at the converters defined in the `java8` branch.  Perhaps you can use those to tailor something more to your liking until that support hits `master`.
