### ISSUE TITLE
Annotation to add document validation to a collection

### ISSUE THREAD

**Issue by UlrichCech** [mongodb/morphia#956]
Are there already plans to introduce an annotation to define a document validator on an entity (collection)? Like adding and index?

```
@Entity
@Validator(validator="{$and: [{lastname: {$exists: true}}, {ssn: {$exists: true}}]}" , validationLevel="strict", validationAction="error")
public class User {
   ....
}
```

I could try to start a prototype on this and if it works, implement it completely.

**Comment by evanchooly** [comment]
I know you'd talked about prototyping this but i'm in a hotel tonight and slightly bored so I banged out a prototype.  Take a look at the commit above and see what you think.

**Comment by evanchooly** [comment]
probably easier to just look at the docvalidation branch in general.

**Comment by UlrichCech** [comment]
I was waiting for a response, if this feature is planned or somewhere on the roadmap, but ok, you branch looks nice... I was thinking about the same way of implementing it.

**Comment by evanchooly** [comment]
I apologize.  I should've left this one for you.  Hotel boredom got the best of me.  Anything else catch your eye you'd like to tackle?  Current issue or missing feature?
