### ISSUE TITLE
Deserializing map creates empty maps instead of null

### ISSUE THREAD

**Issue by umbreak** [mongodb/morphia#958]
I have a class as follows:

    public class Price {
        protected Map<AdditionalCostsType, AdditionalPrice> otherCosts;
        ....
    }

As I can see, **in the DB the field otherCosts is not stored** (which is just fine). When I am fetching that object through morphia I see that **the returned object has the field otherCosts. Empty, but it has it**. And that's wrong.

I know there is an option, on serializing, to tell Morphia to save the object in the DB as it is in memory (if element is empty, save empty: `morphia.getMapper().getOptions().setStoreEmpties(true)`. However, this is the opposite case: If in DB is null, return me a null object and if it is empty return me empty.

If this does not work the equals does not work correctly, which is pretty important...

That was working in 1.0.1.

**Comment by evanchooly** [comment]
Could you try 1.2.1 and see if you're still seeing this behavior?  If so, can you check the linked test?  I can't recreate this on master.

**Comment by umbreak** [comment]
In a very basic test I could not reproduce it. But having a bit more complex model I could. Here is a model which will cause this issue:

    @Entity
    public static class TestEmptyModel{
        public String text;
        public Wrapped wrapped;
        public static class Wrapped {
            public Map<String, Wrapped> others;
            public String text;
        }
    }

And the test:

                TestEmptyModel model= new TestEmptyModel();
                model.text="text";
                model.wrapped = new TestEmptyModel.Wrapped();
                model.wrapped.text="textWrapper";
                model.save();
                TestEmptyModel model2 = TestEmptyModel.find.byId(model.id);
                Assert.assertNull(model.wrapped.others);
                Assert.assertNull(model2.wrapped.others);

**The error is related with the Map having a Entry which is an object**. When is a Map<String,String> for example, it works.

**Comment by evanchooly** [comment]
found the culprit.  thanks.
