### ISSUE TITLE
Querying embedded Fields giving ValidationException on disableValidation

### ISSUE THREAD

**Issue by mdoh** [mongodb/morphia#961]
Hi,

I get a ValidationException after updating to Morphia 1.2.0

The field 'data.data.id' could not be found in 'java.lang.Object' in Embedded Objects. at org.mongodb.morphia.query.QueryValidator.validateQuery(QueryValidator.java:99

Morphia Version 1.2.0
JDK 1.8
MongoDB 3.0.7

In MongoDB the corresponding Query 
`db.collection.find({"data.data.id" : "123"})`
is working

Here is a Test:

```
import java.util.List;
import java.util.Map;
import java.util.Objects;

import org.bson.types.ObjectId;
import org.junit.Before;
import org.junit.Test;
import org.mongodb.morphia.annotations.Entity;
import org.mongodb.morphia.annotations.Id;
import org.mongodb.morphia.dao.BasicDAO;
import org.mongodb.morphia.query.Query;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mongodb.BasicDBList;


public class ValidateEntityWithDBListIT extends AbstractMorphiaIT {

	private BasicDAO<TestEntity, ObjectId> dao;

	private ObjectMapper jsonMapper = new ObjectMapper();

	public static final String DATA = "[{ \"type\" : \"text\", \"data\" : { \"text\" : \"sometext\" } },  { \"data\" : { \"id\" : \"123\" }, \"type\" : \"image\"  }]";

	/**
	 * 
	 */
	@Before
	public void setUp() {
		this.dao = new BasicDAO<>(TestEntity.class, datastore);
	}

	/**
	 * 
	 */
	@Test
	@SuppressWarnings("unchecked")
	public void testCreateEntityWithBasicDBList() throws Exception {

		TestEntity entity = new TestEntity();

		List<Map<String, Object>> data = this.jsonMapper.readValue(DATA, List.class);

		entity.setData(data);
		this.dao.save(entity);

		this.dao.get(entity.getId());

		Query<TestEntity> query = this.dao.createQuery();
		query.disableValidation();
		query.criteria("data.data.id").equal("123");

		TestEntity foundEntity = query.get();
		assertNotNull(foundEntity);
	}

	/**
	 *
	 */
	@Entity("CreateEntityWithDBListIT-TestEntity")
	public static class TestEntity {

		@Id
		private ObjectId id;

		public ObjectId getId() {
			return id;
		}

		private BasicDBList data;

		public BasicDBList getData() {
			return data;
		}

		public void setData(List<?> data) {
			Objects.requireNonNull(data, "data");
			this.data = new BasicDBList();
			this.data.addAll(data);
		}
	}

}
```

**Comment by evanchooly** [comment]
Probably related #941

**Comment by mdoh** [comment]
Yes, it seems so. 

Is there a reason why the QueryValidator only breaks at Interface?

```
if (mf == null && mc.isInterface()) {
    break;
} else if (mf == null) {
    throw new ValidationException(format("The field '%s' could not be found in '%s'", prop, mc.getClazz().getName()));
}
```

**Comment by evanchooly** [comment]
That logic predates me so I can't say one way or the other why it breaks there though I have some guesses.  

Can you share an example line or two of your json just so I can recreate this test locally.  I have an idea of what it looks like but would like to minimize the assumptions I'm making.

**Comment by evanchooly** [comment]
nevermind.  just found that constant.

**Comment by mdoh** [comment]
still broken in current 1.3.0-SNAPSHOT

**Comment by evanchooly** [comment]
That jenkins build is still running.

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "mongodb.com <http://www.mongodb.com>", *"*antwerkz.com*"*
*]*,
  location : *"*New York, NY*"* *}*

**Comment by mdoh** [comment]
ok.

**Comment by evanchooly** [comment]
It should be online now.  At least, jenkins has pushed the bits.

*--------------------------------*

*{ *name     : *"**Justin Lee**", *
  title    : *"*Software Engineer*"*,
  twitter  : *"*@evanchooly <http://twitter.com/evanchooly>*"*,
  web      : *[* "mongodb.com <http://www.mongodb.com>", *"*antwerkz.com*"*
*]*,
  location : *"*New York, NY*"* *}*

**Comment by mdoh** [comment]
i tried morphia-1.3.0-20160711.144219-30 and it is still broken on my site:

The field 'data.data.id' could not be found in 'java.lang.Object'
	at org.mongodb.morphia.query.QueryValidator.validateQuery(QueryValidator.java:97) ~[morphia-1.3.0-SNAPSHOT.jar:na]

**Comment by evanchooly** [comment]
can you look at the test [here](org.mongodb.morphia.entities.TestEmbeddedValidation#testCreateEntityWithBasicDBList) and see how it differs from your situation?

**Comment by mdoh** [comment]
I' ve seen your tests and I' m already on running these on my machine

**Comment by mdoh** [comment]
Your TestEntity has a different data object. As you can see on the sample above it was:

```
public void setData(List<?> data) {
	Objects.requireNonNull(data, "data");
	this.data = new BasicDBList();
	this.data.addAll(data);
} 
```

Because of that it can not find it in MappedClass

```
    public MappedField getMappedField(final String storedName) {
        for (final MappedField mf : persistenceFields) {
            for (final String n : mf.getLoadNames()) {
                if (storedName.equals(n)) {
                    return mf;
                }
            }
        }

        return null;
    }
```

**Comment by evanchooly** [comment]
I was guessing that'd be the difference.  You really shouldn't be using `BasicDBList` directly.  Can you change your model?

**Comment by mdoh** [comment]
If I do so I get warnings: Parameterized types are treated as untyped Objects and a java.lang.ClassCastException: com.mongodb.BasicDBObject cannot be cast to java.util.List
	at org.mongodb.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:74) ~[morphia-1.3.0-SNAPSHOT.jar:na]

Why should I avoid using BasicDBList?
