### ISSUE TITLE
UpdateOperations addAll failing with Objects

### ISSUE THREAD

**Issue by agiannone** [mongodb/morphia#962]
Calling UpdateOperations addAll with a list of objects causes ClassMapBasedObjectSerializer to throw a "json can't serialize type" RuntimeException.

The reason is a change made between release 1.1.0 and 1.2.0 in the UpdateOpsImpl. The ADD_TO_SET_EACH works correctly as it passes the list of values into the add() method as-is, allows the values to be mapped using the mapper and then does the following:

        if (UpdateOperator.ADD_TO_SET_EACH.equals(op)) {
            val = new BasicDBObject(UpdateOperator.EACH.val(), val);
        }

This works because the objects are added post mapping. The PUSH operation on the other hand, calls the add() method like so: 

`add(UpdateOperator.PUSH, fieldExpr, new BasicDBObject(UpdateOperator.EACH.val(), values), true);`

The BasicDBObject is considered a pass-through object by the mapper which means the values don't get mapped and the Mongo driver is then unable to serialize them.

If the add method was called as such (like the addToSet is):

`add(UpdateOperator.PUSH_EACH, fieldExpr, values, true);`

And once mapped, you did:

        if (UpdateOperator.PUSH_EACH.equals(op)) {
            val = new BasicDBObject(UpdateOperator.EACH.val(), val);
        }

Then the problem would be fixed.

**Comment by evanchooly** [comment]
I think i just accidentally fixed this issue (albeit slightly differently).  Can you check master again and see if the issue remains?

**Comment by agiannone** [comment]
I haven't had a chance to try the master code yet but I did scan through the class and it looks like the push() method is now applying the mapping before EACHing the values. Once I get a chance to check I'll confirm 100% but in principal, it should be fixed...
