### ISSUE TITLE
'gradle install' does not build Java driver jars

### ISSUE THREAD

**Issue by Steve-Hand** [mongodb/morphia#967]
Running 'gradle install' does not build Java driver jar

$ gradle install
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes
:buildSrc:jar
:buildSrc:assemble
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses
:buildSrc:test
:buildSrc:check
:buildSrc:build
Building with the 3.x java driver
:morphia:compileJava
/Users/shand/Documents/Development/morphia/morphia/src/main/java/org/mongodb/morphia/mapping/MapperOptions.java:10: warning: [deprecation] DatastoreProvider in org.mongodb.morphia.mapping.lazy has been deprecated
import org.mongodb.morphia.mapping.lazy.DatastoreProvider;
                                       ^
/Users/shand/Documents/Development/morphia/morphia/src/main/java/org/mongodb/morphia/query/UpdateOpsImpl.java:65: warning: [deprecation] addAll(String,List<?>,boolean) in UpdateOperations has been deprecated
    public UpdateOperations<T> addAll(final String field, final List<?> values, final boolean addDups) {
                               ^
  where T is a type-variable:
    T extends Object declared in interface UpdateOperations
2 warnings
:morphia:processResources UP-TO-DATE
:morphia:classes
:morphia:jar
:entityscanner-plug:compileJava
:entityscanner-plug:processResources UP-TO-DATE
:entityscanner-plug:classes
:entityscanner-plug:jar UP-TO-DATE
:util:compileJava UP-TO-DATE
:morphia:javadoc
/Users/shand/Documents/Development/morphia/morphia/src/main/java/org/mongodb/morphia/aggregation/AggregationElement.java:27: warning - @return tag has no arguments.
1 warning
:entityscanner-plug:javadoc
:entityscanner-plug:javadocJar
:entityscanner-plug:sourcesJar UP-TO-DATE
:entityscanner-plug:signArchives SKIPPED
:entityscanner-plug:install
:guice-plug:compileJava
:guice-plug:processResources UP-TO-DATE
:guice-plug:classes
:guice-plug:jar UP-TO-DATE
:guice-plug:javadoc
:guice-plug:javadocJar
:guice-plug:sourcesJar UP-TO-DATE
:guice-plug:signArchives SKIPPED
:guice-plug:install
:logging-slf4j:compileJava
:logging-slf4j:processResources UP-TO-DATE
:logging-slf4j:classes
:logging-slf4j:jar UP-TO-DATE
:logging-slf4j:javadoc
:logging-slf4j:javadocJar
:logging-slf4j:sourcesJar UP-TO-DATE
:logging-slf4j:signArchives SKIPPED
:logging-slf4j:install
:morphia:javadocJar
:morphia:sourcesJar
:morphia:signArchives SKIPPED
:morphia:install
:no-proxy-deps-tests:compileJava UP-TO-DATE
:no-proxy-deps-tests:processResources UP-TO-DATE
:no-proxy-deps-tests:classes UP-TO-DATE
:no-proxy-deps-tests:jar UP-TO-DATE
:no-proxy-deps-tests:javadoc UP-TO-DATE
:no-proxy-deps-tests:javadocJar UP-TO-DATE
:no-proxy-deps-tests:sourcesJar UP-TO-DATE
:no-proxy-deps-tests:signArchives SKIPPED
:no-proxy-deps-tests:install
:validation:compileJava
:validation:processResources UP-TO-DATE
:validation:classes
:validation:jar UP-TO-DATE
:validation:javadoc
:validation:javadocJar
:validation:sourcesJar UP-TO-DATE
:validation:signArchives SKIPPED
:validation:install

BUILD SUCCESSFUL

Total time: 21.384 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html

$ find ./ -name "*.jar"
.//buildSrc/build/libs/buildSrc.jar
.//entityscanner-plug/build/libs/morphia-entityscanner-plug-1.3.0-SNAPSHOT-javadoc.jar
.//entityscanner-plug/build/libs/morphia-entityscanner-plug-1.3.0-SNAPSHOT-sources.jar
.//entityscanner-plug/build/libs/morphia-entityscanner-plug-1.3.0-SNAPSHOT.jar
.//gradle/wrapper/gradle-wrapper.jar
.//guice-plug/build/libs/morphia-guice-plug-1.3.0-SNAPSHOT-javadoc.jar
.//guice-plug/build/libs/morphia-guice-plug-1.3.0-SNAPSHOT-sources.jar
.//guice-plug/build/libs/morphia-guice-plug-1.3.0-SNAPSHOT.jar
.//logging-slf4j/build/libs/morphia-logging-slf4j-1.3.0-SNAPSHOT-javadoc.jar
.//logging-slf4j/build/libs/morphia-logging-slf4j-1.3.0-SNAPSHOT-sources.jar
.//logging-slf4j/build/libs/morphia-logging-slf4j-1.3.0-SNAPSHOT.jar
.//morphia/build/libs/morphia-1.3.0-SNAPSHOT-javadoc.jar
.//morphia/build/libs/morphia-1.3.0-SNAPSHOT-sources.jar
.//morphia/build/libs/morphia-1.3.0-SNAPSHOT.jar
.//no-proxy-deps-tests/build/libs/morphia-no-proxy-deps-tests-1.3.0-SNAPSHOT-javadoc.jar
.//no-proxy-deps-tests/build/libs/morphia-no-proxy-deps-tests-1.3.0-SNAPSHOT-sources.jar
.//no-proxy-deps-tests/build/libs/morphia-no-proxy-deps-tests-1.3.0-SNAPSHOT.jar
.//validation/build/libs/morphia-validation-1.3.0-SNAPSHOT-javadoc.jar
.//validation/build/libs/morphia-validation-1.3.0-SNAPSHOT-sources.jar
.//validation/build/libs/morphia-validation-1.3.0-SNAPSHOT.jar

**Comment by jyemin** [comment]
I wouldn't expect it to.  The Java driver is a pre-built dependency of morphia that is downloaded as part of the Gradle build.  You'll find the driver in ~/.m2/repository/org/mongodb/mongo-java-driver.

**Comment by Steve-Hand** [comment]
Thanks for the update.
