### ISSUE TITLE
$elemMatch multiple criteria support

### ISSUE THREAD

**Issue by elogunov** [mongodb/morphia#970]
Correct me if I am wrong but as I can see current Morphia implementation of `$elemMatch` (i.e. `FieldEnd#hasThisElement`) doesn't support [multiple criteria for array elements](https://docs.mongodb.com/manual/tutorial/query-documents/#specify-multiple-criteria-for-array-elements) or [multiple criteria for array of documents](https://docs.mongodb.com/manual/tutorial/query-documents/#specify-multiple-criteria-for-array-of-documents).
So there is no way to create such query using morphia:
`db.restaurants.find({grades : { $elemMatch:{"score":{$gt : 80 , $lt :100}}}})`
[stackoverflow question](https://stackoverflow.com/questions/37650166/how-to-write-the-following-query-in-morphia)

I didn't find any linked issues here.

**Comment by evanchooly** [comment]
If you can build and test the 'hasThisElement' branch, I have a fix that I think will get you what you need.  Building on the existing tests, this is what the test for the new `elemMatch()` method looks like:

```java
        Query<Keyword> query = getDs()
            .createQuery(Keyword.class)
            .filter("keyword = ", "Oscar")
            .filter("score = ", 12);
        assertNull(getDs().find(PhotoWithKeywords.class)
                          .field("keywords")
                          .elemMatch(query)
                          .get());
```
