### ISSUE TITLE
BasicDAO#update does not exist with createIfMissing parameter

### ISSUE THREAD

**Issue by toonsevrin** [mongodb/morphia#980]
http://mongodb.github.io/morphia/1.3/javadoc/org/mongodb/morphia/dao/BasicDAO.html does not contain the method update(Query<T> query, UpdateOperations<T> operations, boolean createIfMissing), while the Datastore class does contain this method.

This missing feature remains in all versions as of this date.

**Comment by evanchooly** [comment]
This method is being deprecated/replace with an Option providing this functionality
