### ISSUE TITLE
set collectionName value at runTime

### ISSUE THREAD

**Issue by roeiham** [mongodb/morphia#986]
hay.
Is there a way to edit the CollectionName at runTime instead of compile time (@Entity("collevtionName")).
the reason for that -->  my app need to "tell" me in property file (for instance) the collection name.
so i cant know it at compile time

10x

**Comment by evanchooly** [comment]
You can pass the collection name to methods on `Datastore` (you might need to cast to `AdvancedDatastore` in some cases) rather than relying on the mapped collection name.

In the future, please use the [mailing list](https://groups.google.com/forum/#!forum/morphia) for questions.
