### ISSUE TITLE
hasThisElement() hard codes a 'false' for the not parameter

### ISSUE THREAD

**Issue by evanchooly** [mongodb/morphia#988]
This means that the operation can not be "not"ed.

https://github.com/mongodb/morphia/blob/c7bd85f43451d9a4dfea5b2a2bb614369c32331f/morphia/src/main/java/org/mongodb/morphia/query/FieldEndImpl.java#L145-L145

**Comment by ipavkovicAtOtto** [comment]
What about
this line:
https://github.com/mongodb/morphia/blob/master/morphia/src/main/java/org/mongodb/morphia/query/FieldEndImpl.java#L133

shouldn't this be !not ?

**Comment by evanchooly** [comment]
You're probably right.  just filed https://github.com/mongodb/morphia/issues/1107.
